### ISSUE TITLE
Some examples are broken

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#100]
For example, `examples/R/data` doesn't compile anymore. It breaks with:
```
error[E0599]: no method named `namesAndValues` found for enum `extendr_api::Robj` in the current scope
  --> src/lib.rs:19:43
   |
19 |     if let Some(names_and_values) = input.namesAndValues() {
   |                                           ^^^^^^^^^^^^^^ method not found in `extendr_api::Robj`
```

<details>

```
clauswilke ~/github/extendr/extendr-api/examples/R/data> R CMD INSTALL .
* installing to library ‘/Users/clauswilke/Library/R/4.0/library’
* installing *source* package ‘data’ ...
** using staged installation
** libs
/Library/Frameworks/R.framework/Resources/share/make/shlib.mk:6: warning: overriding commands for target `data.so'
Makevars:9: warning: ignoring old commands for target `data.so'
rm -Rf data.so ../target/release/libdata.a entrypoint.o ../target
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c entrypoint.c -o entrypoint.o
echo BUILDING STATLIB
BUILDING STATLIB
cargo build --release --manifest-path=../Cargo.toml
   Compiling proc-macro2 v1.0.24
   Compiling libR-sys v0.2.0
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.56
   Compiling extendr-engine v0.1.11 (/Users/clauswilke/github/extendr/extendr-engine)
   Compiling lazy_static v1.4.0
   Compiling quote v1.0.8
   Compiling extendr-macros v0.1.11 (/Users/clauswilke/github/extendr/extendr-macros)
   Compiling extendr-api v0.1.11 (/Users/clauswilke/github/extendr/extendr-api)
   Compiling data v0.1.0 (/Users/clauswilke/github/extendr/extendr-api/examples/R/data)
error[E0599]: no method named `namesAndValues` found for enum `extendr_api::Robj` in the current scope
  --> src/lib.rs:19:43
   |
19 |     if let Some(names_and_values) = input.namesAndValues() {
   |                                           ^^^^^^^^^^^^^^ method not found in `extendr_api::Robj`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `data`

To learn more, run the command again with --verbose.
make: *** [../target/release/libdata.a] Error 101
ERROR: compilation failed for package ‘data’
* removing ‘/Users/clauswilke/Library/R/4.0/library/data’
```

</details>

In general, I think we should move the examples elsewhere, e.g. into the integration tests. Since we don't automatically test examples, they may break at any moment.

**Comment by jbabyhacker** [comment]
The `examples/R/classes` example doesn't work either. It compiles, but doesn't run. The symbols can be manually loaded with dyn.load() and then called with .Call in order to allocate the object, then set and get a string. However, the R class code in `examples/R/classes/R/lib.R` doesn't make the R class even with manually sourcing the file. I am running R 4.0.3 on Ubuntu 20.04.
```R
myperson = Person$new()
Error: object 'Person' not found
```

**Comment by clauswilke** [comment]
As far as I can tell, in the classes example the build structure is broken. It needs registration routine forwarding similar to the hello example (with corresponding changes to `Makevars`):
https://github.com/extendr/extendr/blob/62f3365950dd488f5642bffae2df24c4ecffa94e/extendr-api/examples/R/hello/src/entrypoint.c#L4-L8

**Comment by clauswilke** [comment]
I fixed the build structure in classes (#106) but the example code still doesn't work properly. The `Person` symbol does not get registered properly. (The `aux_func` symbol does.) I assume this requires additional work on the modules macro. Paging @hobofan: Is this something you wanted to look into?

**Comment by andy-thomason** [comment]
I am hoping to revise the class structure to generate classes as environments a la R6 classes.

I'm just adding environment and function support for this purpose.

Is you have noticed, I've normalised many of the function names (such as namesAndValues).

We will still need to export doc strings for methods, but I'm not sure how to do this for functions
in environments.

As from my wrappers PR #105 we'll have many more tools available.

**Comment by andy-thomason** [comment]
It would be nice if the integration tests used paths (or at least have a test that uses paths).

This would allow us to locally test the integration.

**Comment by clauswilke** [comment]
@andy-thomason:

> It would be nice if the integration tests used paths (or at least have a test that uses paths).

I'm not sure what you're referring to. If you're referring to the dependency statements in `Cargo.toml`, I'm not aware of any way to use relative paths in the integration tests. The best approach is to temporarily point to the branch on github where you're doing your development.

If you're referring to something else, could you explain in a little more detail? I'm happy to expand the scope of the integration tests.

**Comment by jbabyhacker** [comment]
I got the registration working with R6 classes in my own code. I can correct the example if you want.

**Comment by clauswilke** [comment]
@jbabyhacker Yes, could you prepare a PR?

**Comment by yutannihilation** [comment]
Can we close this issue?

**Comment by andy-thomason** [comment]
I think so now.

**Comment by yutannihilation** [comment]
Thanks!
