### ISSUE TITLE
Should extendr provide ALTREP-aware implementations?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#117]
This introduction to cpp11 is interesting to read. Especially, this part made me wonder whether extendr can (or should) provide ALTREP-aware implementation.

https://speakerdeck.com/jimhester/cpp11-welding-r-and-c-plus-plus?slide=64

**Comment by clauswilke** [comment]
I think the answer is both it can and it should, but somebody needs to implement it.

Here is a video version of the talk. I found the slides alone not that informative.
https://www.youtube.com/watch?t=4&v=_kq0N0FNIjA

**Comment by yutannihilation** [comment]
Thanks, I'll watch it.

**Comment by andy-thomason** [comment]
I was planning a redesign of IntegerIter and friends which could choose the ALTREP version IFF the object is ALTREP.

Using only INTEGER_ELT is likely to be costly (I'll have to check).

We currently do this with StrIter which  cops with both character vectors and factors.

**Comment by andy-thomason** [comment]
I am also planning to bring in Int, Real and Logical wrapper types to make things symmetrical.

So r!(Int(1..=10000)) could return an ALTREP object.

**Comment by yutannihilation** [comment]
Closed by #250

**Comment by yutannihilation** [comment]
Ah, no, sorry. I was a bit confused.
