### ISSUE TITLE
Add rextendr use case to integration tests

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#127]
The current integration tests test whether we can use extendr code in an R package, but they don't test whether we can call `rust_source()` or `rust_function()` from rextendr. I think we should add such a test, to make sure we don't accidentally break rextendr down the road.

cc @Ilia-Kosenkov

**Comment by Ilia-Kosenkov** [comment]
PR #173 introduced a new CI step that duplicates `R CMD check` procedure also for the latest version of {rextendr}.
{rextendr}'s dynamically-generated rust libraries are linked to the dev version of `extendr-api` that is tested by the CI.

This solution ensures that only one {rextendr} test codebase exists, and that any new features added to and tested by {rextendr}  are also automatically tested by `extendr` CI.
