### ISSUE TITLE
Compiling rust using the Rtools toolchain (mingw) on Windows?

### ISSUE THREAD

**Issue by CGMossa** [extendr/extendr#13]
I huge barrier to entry is the whole needing a compiler thing.
With the new Rtools4.0 I believe it might be doable to configure rustup/rust to specifically
build for the target that may be built using the compiler in Rtools.

I'll have to investigate this further. Let me know if anyone has already (or is already) doing this. 
A wiki-page on it could be nice.

**Comment by andy-thomason** [comment]
This looks like a much better option. Running R and Rust on Windows has never been easy.
Perhaps we could lobby Rtools to include a cargo install.

I've tried as much as possible to keep to vanilla, stable Rust. We problems with
the rust arrow library as it was nightly only but if you come across compatibility issues
please raise them.

Thomas has been working on the Mac side of things and helping with defining the API.

**Comment by andy-thomason** [comment]
Did you make any progress with this? We might be able to get help from the R community on this.

The R package will help for installing tools and libs.

**Comment by clauswilke** [comment]
Just commented on this issue over here: https://github.com/extendr/extendr/pull/10#issuecomment-724454539

Compiling on Windows is actually quite easy once you hook everything up with the R package build system.

**Comment by clauswilke** [comment]
Closing this as compiling on Windows mostly works. For specific problems that remain, please open new issues detailing those problems one-by-one.

**Comment by yutannihilation** [comment]
Let me leave a comment for future reference.

> Perhaps we could lobby Rtools to include a cargo install.

It's just sending a pull request to [r-windows/rtools-packages repo](https://github.com/r-windows/rtools-packages) according to this document: [System Libraries in Rtools40](https://github.com/r-windows/docs/blob/master/rtools40.md). Currently libR-sys requires Windows users to install new MSYS2 for clang, but we might be able to make clang available on Rtools' MSYS2 via pacman.

**Comment by CGMossa** [comment]
I've tried to install clang on Rtools' MSYS2 installation. It is locked to
a specific repository that
do not have clang as part of it. Thus, it doesn't suffice with just cargo
on Rtools40, we also
need clang to be added to the rtools package repository. See here:
https://github.com/r-windows/rtools-packages

**Comment by yutannihilation** [comment]
> we also need clang to be added to the rtools package repository.

Thanks, yes, that's what I mean. But, I'm not sure if we really need cargo to be included in Rtools. Rust can be installed easily by just following the instruction on the official website.

Should we reopen this issue and keep discussing the best setup on Windows?

**Comment by clauswilke** [comment]
@yutannihilation I suggest to move this discussion into a new issue for libR-sys, and make it specifically about necessary changes in Rtools. extendr is the wrong repo for this issue in my opinion.

**Comment by yutannihilation** [comment]
Sure, I will.
