### ISSUE TITLE
Exporting classes with lifetime annotation

### ISSUE THREAD

**Issue by dfalbel** [extendr/extendr#131]
I have a `impl` that I'd like to export that includes lifetime annotations, eg:

```
struct Person<'a> {
    pub name: &'a String,
}

#[extendr]
impl<'a> Person<'a> {
    fn new() -> Self {
        Self { name: &"".to_string() }
    }

    fn set_name(&mut self, name: &str) {
        self.name = &name.to_string();
    }

    fn name(&self) -> &str {
        self.name.as_str()
    }
}
```

Compilation of this file fails with:

```
custom attribute panicked

help: message: `"init__Person  \'a __new"` is not a valid identifier
```

It seems to me that this happens because this only happens a invalid function name is generated here:

https://github.com/extendr/extendr/blob/master/extendr-macros/src/lib.rs#L319-L321

Do you think it's fixable by tweaking this line to strip those invalid characters? I'd be happy to contribute a PR if this sounds like a reasonable solution.

**Comment by clauswilke** [comment]
Yes in principle. I think the correct approach is to change the macro code that originally extracts the function name. It should be written to ignore template arguments.

**Comment by clauswilke** [comment]
Now looking more carefully, that's this line I suppose:
https://github.com/extendr/extendr/blob/bb6e856aa11a030b485c2af15343343f99562e75/extendr-macros/src/lib.rs#L320

**Comment by clauswilke** [comment]
I'm not that familiar with quote and syn, so I don't know off the top of my head how to do this. Probably @andy-thomason knows.

**Comment by clauswilke** [comment]
Related, though the inverse problem: https://stackoverflow.com/questions/55271857/how-can-i-get-the-t-from-an-optiont-when-using-syn

**Comment by dfalbel** [comment]
This goes way beyond what I know about Rust, but I have tried to put something here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=756ab5cd1400db74e6112323b8f555e5

AFAICT this we should be able to extract a string from this `ident` structure giving the name of the `impl` without the template args, but I couldn't find a way to do it...

**Comment by clauswilke** [comment]
I edited your example. You can just replace `ident` with `ident.to_string()` to extract the name into a string.

**Comment by clauswilke** [comment]
To be clear: I replaced this:
```rust
    println!("{:#?}!", ident)
```
with this:
```rust
    println!("Identifier: {}", ident.to_string()) 
```
and the output is:
```
Identifier: Foo
```

**Comment by yutannihilation** [comment]
Here's my attempt based on @dfalbel's one (it was very useful, thanks!):

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc65438ddc5e8443a064a7292e8255e2

> AFAICT this we should be able to extract a string from this `ident` structure giving the name of the `impl` without the template args, but I couldn't find a way to do it...

At first, it seemed simple as `Path` has `get_ident()` method,

https://docs.rs/syn/1.0.58/syn/struct.Path.html#method.get_ident

But, this doesn't work because, in the case of `Person<'a>`, the path is NOT ident as it doesn't satisfy the third point of the following definition:

> A path is considered an ident if:
> *    the path has no leading colon,
> *    the number of path segments is 1, and
> *    the first path segment has no angle bracketed or parenthesized path arguments.

Besides, this made me wonder if we should handle more cases e.g.

```
#[extendr]
impl<'a> foo::Person<'a> {
  ...
}

#[extendr]
impl<'a> bar::Person<'a> {
  ...
}
```

**Comment by dfalbel** [comment]
@clauswilke 
> `println!("Identifier: {}", ident.to_string()) `

I completely missed that! Thanks!

@yutannihilation Learned a lot from your code! Thanks! It seems that it makes sense to support that, although I don't know how namespacing would be handled in the R wrappers generators in the future.

Do you want me to write a PR using that function to generate the name instead of the current `quote!`? As in here:

```
let self_ty_name = quote! {#self_ty}.to_string(); 
```

**Comment by yutannihilation** [comment]
> using that function to generate the name instead of the current `quote!`

Yeah, I guess we should not rely on `quote!`. While the approach you proposed

> tweaking this line to strip those invalid characters

might be easier to implement and probably works in all the cases, I think we should rather throw errors on non-supported cases to avoid confusion. In order to do this, I think we need some function like the one I wrote (though I'm not sure my function is good enough).

I too have no idea how namespacing could be supported, so let's not support it for now. You can just pick `ident` from `path.segments[0]` and convert it to a string by `to_string()`. A pull request for this would be appreciated.

**Comment by clauswilke** [comment]
Yes, agreed. We can tackle namespaces once somebody comes across a concrete use case where it's needed. This should clarify what the right design decisions might be.

**Comment by andy-thomason** [comment]
Much of this has now been done in extendr_macros.

We have a function which gets the base name of an ident.

Impl processing checks the parameters of the impl including lifetime ones.

One of the problems of lifetime is that the only really useful
one is `'static`.

Objects wrapped in `Robj`s should be considered `'static` and it may not be possible to convert
objects with local lifetime to `'static` without boxing them first.

Once boxed, lifetimes essentially become static and the object can be wrapped in a R object.
