### ISSUE TITLE
Consider making the init functions public

### ISSUE THREAD

**Issue by dfalbel** [extendr/extendr#140]
Can we consider making `init__` functions public? I mean here:

https://github.com/extendr/extendr/blob/10d0ab8a64ab4fafb125d69cf555f08b5b090593/extendr-macros/src/lib.rs#L274

and here:

https://github.com/extendr/extendr/blob/10d0ab8a64ab4fafb125d69cf555f08b5b090593/extendr-macros/src/lib.rs#L412

The use case is to be able split the implementation in multiple files. With this one could have a file named `utils.rs` with:

```
use extendr_api::*;

#[extendr]
pub fn hello () -> String {
    "hello world".to_string()
}
```

and then export the hello function in `lib.rs` with:

```
use extendr_api::*;
mod utils;
use utils::*;

extendr_module! {
    mod helloextendr;
    fn hello;
}
```

If this is undesirable, Is there any approach for splitting the implementation in multiple files?

**Comment by clauswilke** [comment]
Maybe use `pub(crate)` or `pub(super)`?

**Comment by clauswilke** [comment]
However, PR #128 is doing away with init functions, so maybe you could review it and see whether it requires modifications to allow splitting the implementation into multiple files? I think generally it's a good idea to be able to do this.

**Comment by dfalbel** [comment]
Ok, I reviewed #128 . A similar approach would work - just making the below functions public allows exporting functions implemented in other modules.

https://github.com/extendr/extendr/blob/dc7c647e6c135789a556013f171ee373a8bbae33/extendr-macros/src/lib.rs#L329

and 

https://github.com/extendr/extendr/blob/dc7c647e6c135789a556013f171ee373a8bbae33/extendr-macros/src/lib.rs#L484

**Comment by andy-thomason** [comment]
Whilst the meta__ functiions are not public, the get_xxx_metadata functions, which call them, are.

Thus you should be able to pub use them.

However, the `extendr_module!` macro currently assumes that the DLL name is the same as the module name
as the `R_init_xxx` function name is DLL-specific.

We could add a syntax to chain metadata:

```
extendr_module! {
  mod dll_name;
  use my_submodule;
}
```

This could add my_submodule's metadata to the main dll metadata.
Omitting the "mod" would prevent the R_init_ function from being generated.

Now the registration is done entirely from metadata, many more possibilities arise.

**Comment by clauswilke** [comment]
Is this addressed now or does something remain to be done?

**Comment by dfalbel** [comment]
No, #160 addressed this. Closing

**Comment by andy-thomason** [comment]
If you all approve, I'll add a use statement to the extendr module so you
can export from inside other modules.

**Comment by clauswilke** [comment]
@andy-thomason I'm not sure I understand what it is you want to do. I suggest you just submit a PR.
