### ISSUE TITLE
Some tests are not conditionally compiled

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#144]
Currently the integration tests trigger a note that the compiled code contains non-API entry points:
https://github.com/extendr/extendr/pull/141/checks?check_run_id=1755212957#step:14:90

This isn't reported as an error, so tests seem to pass, but it would actually prevent us from submitting a package to CRAN, so it needs to be fixed.

One case where we have tests without conditional compilation is here:
https://github.com/extendr/extendr/blob/f43d2539e8ac0d5dcd562aa1d2282369528ae1a2/extendr-api/src/robj_ndarray.rs#L59-L61

There may be others. These can be difficult to find. It would be good to have some sort of automated test for these, so they don't sneak in to the code base unnoticed.

**Comment by yutannihilation** [comment]
IIUC, we need to drop the dependency on extendr-engine. I think we need to remove this line

https://github.com/extendr/extendr/blob/daee5c88842b0ec226c32ae9472244b6c6a8a63e/tests/extendrtests/src/rust/Cargo.toml#L30

and make all tests in extendr-api using `extendr_engine::start_r()` as optional.

https://github.com/extendr/extendr/blob/daee5c88842b0ec226c32ae9472244b6c6a8a63e/extendr-api/src/robj/tests.rs#L5

**Comment by clauswilke** [comment]
> IIUC, we need to drop the dependency on extendr-engine. I think we need to remove this line

I believe that until extendr-engine is on crates.io, we need this line to keep cargo happy, since extendr-api depends on extendr-engine.

However, other things we can do to improve things is to move extendr-engine into dev-depenencies, then every test that isn't conditionally compiled will break compilation for downstream crates.

**Comment by clauswilke** [comment]
We have figured out that the problem is generated by the new `test!` macro defined here:
https://github.com/extendr/extendr/blob/daee5c88842b0ec226c32ae9472244b6c6a8a63e/extendr-api/src/rmacros.rs#L277-L291
which uses the `test()` function defined here:
https://github.com/extendr/extendr/blob/daee5c88842b0ec226c32ae9472244b6c6a8a63e/extendr-api/src/functions.rs#L380-L392

In my opinion, at least the `test()` function needs to move into extendr-engine, and possibly the `test!` macro also. This is very simple: If we ever want to be able to use extendr code in R packages on CRAN, then we cannot have any engine code in extendr-api.

We also have to make sure we don't let the tail wag the dog here. We cannot have engine code in the api. That's a hard requirement. On the other hand, `test!` is a convenience function for making documentation and tests simpler and easier to read. If some additional hoops need to be jumped through, it has to be on the testing side. We can't make a primary use case (write R packages using Rust) more difficult or complex just so writing documentation becomes easier.

I think this can be resolved relatively easily. I'll make a PR.

**Comment by clauswilke** [comment]
Fix was easier than I thought. See #150.

**Comment by yutannihilation** [comment]
> I believe that until extendr-engine is on crates.io, we need this line to keep cargo happy, since extendr-api depends on extendr-engine.

No, because extendr-api itself declares the dependency on extendr-engine with `path` specified, it doesn't matter. Actually, you can remove this and see it passes the checks.
https://github.com/extendr/extendr/blob/394a0ff5b70dc8be24efe4c47fc92b6f6c5a6a44/extendr-api/Cargo.toml#L19

I think it doesn't matter to extendr-api how extendrtests specifies extendr-engine. Maybe you confuse it with `[patch.crates-io]` section...?

**Comment by yutannihilation** [comment]
But anyway it seems it doesn't matter to avoid "non-API call" warning whether we keep it or remove it. So, I'm fine with either.

**Comment by clauswilke** [comment]
I'll remove it if it's not required.
