### ISSUE TITLE
Delete examples in extendr-api/examples? 

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#154]
Can we delete the examples in `extendr-api/examples`?
https://github.com/extendr/extendr/tree/master/extendr-api/examples/R

Most of them currently don't work (#100), and almost all cases are now covered in integration tests in `extendrtests`. And anything that isn't yet in `extendrtests` (`ndarray` code) should be moved there anyways.

The README should probably point to `extendrtests` rather than `extendr-api/examples` anyways.

**Comment by Ilia-Kosenkov** [comment]
I support this decision, I was thinking about opening this issue yesterday myself.

Those examples do not reflect the `extendr` way. But we should perhaps create a set of easy to use examples that people can install and test from R and put it in some 'examples' folder in the root of the repo.

**Comment by clauswilke** [comment]
We have a separate repo for examples, we just need to add some:
https://github.com/extendr/extendr-examples

We also have this:
https://github.com/extendr/helloextendr

**Comment by andy-thomason** [comment]
Absolutely. Delete away, in master if necessary.
