### ISSUE TITLE
Cross-compiled testing is incomplete

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#155]
Cross-compiled testing does not work. This currently only affects Windows builds (where we do cross-compile), and possibly affects other projects, including libR-sys.

The concept is extraordinarily simple and I don't know why we missed that: it is an issue of toolchain vs target.
Cargo cannot run tests if the toolchain is incompatible with the target.
To illustrate on windows we use `x86_64-msvc` to build for `x86_64-gnu` and `i686-gnu`, which is compiler- (and in one case architecture-) incompatible,
https://github.com/extendr/extendr/runs/1770983091?check_suite_focus=true#step:8:75
https://github.com/extendr/extendr/runs/1770983091?check_suite_focus=true#step:8:98

Runs only like 13 or 14 tests each,
Here is Ubuntu which builts for the same host:
https://github.com/extendr/extendr/runs/1770983030?check_suite_focus=true#step:8:228
127 or so tests.

Simple solution: Do not cross-compile at all. This may resolve an issue with Windows and rtools usage if we use different toolchain for different targets.
This may also uncover underlying problems in code, I might have spotted two failed tests in full `32-bit` Windows test suite of extendr-api.

**Comment by andy-thomason** [comment]
Is it necessary to check cross-compilation?

I'm guessing that on Windows, users rely on pre-built binaries. How does CRAN distribute Windows packages?

**Comment by Ilia-Kosenkov** [comment]
@andy-thomason,
It depends if we want to fully support both arches on Windows and if CRAN can swallow it as is.
If I am able to, I'll provide evidence of tests failing when correctly tested.

Btw, right now because of cross-compilation, we test improperly both `x86_64` and `i686` on Windows.

**Comment by clauswilke** [comment]
The way R packages are set up it basically requires cross-compilation on Windows. We may have to test both, cross-compilation and native compilation. (We test cross-compilation implicitly though when we're building extendrtests, so that may be sufficient.)

**Comment by Ilia-Kosenkov** [comment]
Resolved via #157.
