### ISSUE TITLE
[CI] Define a wrapper of cargo to throw error nicely

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#158]
After googling around, I think it might be an option to define something like

``` ps1
# We cannot specify `cargo` in function `cargo`, otherwise it will go to infinite recursion
$cargo_path = (Get-Command -Name cargo -CommandType Application).Path

if (!$cargo_path) {
  Throw "cargo not found"
}

# The basic idea is from https://stackoverflow.com/a/48877892
function cargo {
  # to prevent 2> redirections from triggering a terminating error.
  $ErrorActionPreference = 'Continue'

  & $cargo_path $args[-0]
  if ($LASTEXITCODE) {
    # Instead of Throw, we can use Write-Error to throw nicer error message
    # c.f. https://docs.microsoft.com/powershell/scripting/learn/deep-dives/everything-about-exceptions?view=powershell-7.1
    Write-Error -Message "cargo failed with status code $LASTEXITCODE (args: $args)" -ErrorAction Stop
  }
}
```

so that we can just write `cargo build/test` instead of always placing the `if` statement at the tail like this

``` ps1
            cargo build ...
            if (!$?) { 
              echo "::error::Build extendr-api for $target target" ;
              throw "Last exit code $LASTEXITCODE"
            }
```

But, of course this probably decrease the readability of the CI results as it's difficult to include a friendly error message like `::error::Build` or `$target` above. So, I'm not sure if this is good or bad at the moment.

**Comment by andy-thomason** [comment]
This seems nicer. We  may end up doing more iterating on CI like the last PR as time goes on!

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation,
I took the liberty of adopting and experimenting with your solution (though with some modifications).
https://github.com/Ilia-Kosenkov/extendr/blob/try-cargo/try-cargo.ps1
It should correctly wrap cargo execution into `"::group::"`, and a special pwsh named parameter `-ActionName` allows to pass a string which is then displayed in all debug messages.
This can then be used in CI:
https://github.com/Ilia-Kosenkov/extendr/blob/try-cargo/.github/workflows/test.yml
The amount of boilerplate code reduced significantly and cargo commands look nice:
```pwsh
try-cargo +$toolchain test --features feature --target $target '--' --nocapture $ActionName "Testing something"
```

The only caveat is that powershell treats `--` as a special symbol, so it should be wrapped into `'--'` to be treated correctly.

Here is how logs may look like with `try-cargo`. Notice Windows-i686 error and how it is displayed everywhere, including summary:
https://github.com/Ilia-Kosenkov/extendr/actions/runs/519195944

**Comment by yutannihilation** [comment]
@Ilia-Kosenkov 
Wow, cool! Thanks. I was hoping we can shadow `cargo` to prevent from using bare `cargo` mistakenly, but, as there's already this difference (sorry, I didn't `--` won't work...), having a different name sounds a good idea.

> The only caveat is that powershell treats `--` as a special symbol, so it should be wrapped into `'--'` to be treated correctly.

Just one thing, to me, `try-` sounds like it would gracefully fail, so I prefer something more frightening (no idea at the moment, though, sorry). Except for this, it looks perfect.

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation,
Feel free to suggest a better name :) 
If #157 gets approved, we can rewrite it to `*-cargo`.

The only problem is importing this function. It does not seem to be preserved across steps.
From my understanding, `pwsh` is executed as `pwsh --command "command"`, so anything we import stays in that scope.
Environment variables set explicitly (not using CI syntax, but rather `$env:MY_VAR=5`) persist across steps, but not imported function. So the only solution I found is to declare the function in a script file and then import it at each step where cargo is invoked via `. .\try-cargo.ps1`. If you happen to know how to make this function survive multiple steps, let me know.

**Comment by yutannihilation** [comment]
Yeah, I'll try to invent a new name until then...

> It does not seem to be preserved across steps.

Maybe we can define the function in `profile.ps1`? c.f. https://docs.microsoft.com//powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1

**Comment by yutannihilation** [comment]
Sorry, probably it doesn't work. Please ignore...

I think `Install-Module` should work, but I don't understand how to create a module and a local repository.

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation,
Did you make any progress with powershell function importing? 
If not, perhaps we can stick to sourcing the script file where necessary.
If we can agree on some name, it would be nice to integrate this script into CI to reduce the amount of boilerplate wrappers we have. I like `try-cargo` though it is indeed not suitable for something that errors. Yet I would like to keep the name as close to plain `cargo` as possible. Perhaps `run-cargo`? To be honest, I am tempted to suggest [`freight`](https://www.thesaurus.com/browse/cargo) or another synonym to replace `cargo` :), but we will have to explain what it does.
`freight test --target i686-gnu -- --nocapture`

**Comment by clauswilke** [comment]
I suggest naming as obviously as possible, e.g. `cargo-wrapper` or `ci-cargo` or `ci-cargo-wrapper`.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
actually `ci-cargo` sounds good and it is concise and close to the original `cargo`, I like that.

**Comment by yutannihilation** [comment]
No progress, sorry. I think sourcing is good in that it's very straightforward, so let's use it.
Among the candidates appeared here, I like `run-cargo`, but have no objection to `ci-cargo`.
