### ISSUE TITLE
question: is there already a way to create a R STRSEXP?

### ISSUE THREAD

**Issue by lebensterben** [extendr/extendr#16]
I'm not able to find a function that provide the API to directly returns a `STRSXP`, that is a string vector, or a list of `CHARSXP`, from Rust side.

For example, say on Rust side I have created `foo: Vec<Cstring>` and wish to transfer it to R's C interface,

The first edition of [Advanced R](http://adv-r.had.co.nz/C-interface.html) provided some information:
```R
abc <- cfunction(NULL, '
  SEXP out = PROTECT(allocVector(STRSXP, 3));

  SET_STRING_ELT(out, 0, mkChar("a"));
  SET_STRING_ELT(out, 1, mkChar("b"));
  SET_STRING_ELT(out, 2, mkChar("c"));

  UNPROTECT(1);

  return out;
')
abc()
```

I guess roughly what I need is the following

```rust
use libR_sys::*;
use std::ffi::CString;

fn some_function(in: Vec<CString>) -> SEXP {
    let out = Rf_protect(Rf_allocVector(STRSXP, foo.len());

    for (idx, cstring) in foo.into_iter().enumerate() {
        SET_STRING_ELT(out, idx, Rf_mkchar(cstring.into_raw()));
    }

    Rf_unprotect(1);

    return out
}
```

Is this correct?
Do you think we can incorporate this functionality to easily convert `Vec<CString>` or `Vec<String>` to `STRSXP`(and consuming the vector)?

**Comment by andy-thomason** [comment]
You can convert a str or string RObj with

```
let my_str = "hello";
let robj = Robj::from(my_str);
```

Or you can just return a string from a function.

I'll need to check whether we have vector, slice or iterator support.

**Comment by andy-thomason** [comment]
This shows the need for some documentation and a cookbook.

**Comment by andy-thomason** [comment]
Whilst you can use libR_sys directly. I would like it if no one had to.

**Comment by andy-thomason** [comment]
I've added a conversion from [String] and [&str] to RObj.

https://github.com/extendr/extendr/commit/6f3e203dfc71f25a39c6eb7e94dfc460db37c8f2

I hope that this helps.

Thanks for helping us fill in the gaps.
