### ISSUE TITLE
Use traits for Robj and implement protection.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#165]
Sooner or later we will have to implement our own protection system for Robj.

For example a hash table for the SEXP value giving an index into a List of Pairlists.

The hash table also includes a reference count to avoid double deletion.

When the refcount atomically reaches zero (Robj::Owned drops) then we remove the SEXP from the protection list.

We should also make a Rref object type and implement all current Robj methods as
traits, grouping them by type - IntegerTraits, RealTraits, EnvTraits etc.

Rref can be used to expose SEXPs in Lists allowing us to index lists. They should be read-only.

We could also do specialised versions of Rref:

Rmut/RobjMut - mutable SEXP objects with IntegerMutTraits etc.

**Comment by clauswilke** [comment]
See also #27.

**Comment by clauswilke** [comment]
Is this issue still relevant? If it has been partially addressed, I suggest closing it and replacing with more focused specific TODOs.

**Comment by andy-thomason** [comment]
This is less relevant now we have type-specific wrappers.

It may be good to make writable methods like set_attribute require a
mutable reference.
