### ISSUE TITLE
Remove specific R macros.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#166]
Many of the rmacros set should be retired in favour of wrappers.

The c! macro which does call!("c", ...) is not necessary and is very inefficient.

Likewise rep!

We should have a DataFrame wrapper.

rep! can be generated by an iterator:

r!(Int(iter::repeat(4).take(100)))

**Comment by clauswilke** [comment]
If you plan on doing this, you should probably do it soon, before we release 0.2. Or alternatively, turn into convenience macros that just call the underlying wrapper code.
