### ISSUE TITLE
Failed R CMD check will not be uploaded

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#171]
In one of the previous PRs `rcmdcheck` was updated and `check_dir` was set to `"../../../"`, which is actually *outside* of repo's root.
This was done to reference `extendr-*` crates using relative paths.
https://github.com/extendr/extendr/blob/f235216793607e59d7d87877fcf927e08a4bd654/.github/workflows/test.yml#L171

The problem is here
https://github.com/extendr/extendr/blob/f235216793607e59d7d87877fcf927e08a4bd654/.github/workflows/test.yml#L174-L179

If the check fails, artifacts are uploaded from `./check/`, which is no longer produced.
In fact, because check dir is now outside of repo's root, artifacts contaminate the folder outside of extendr's workspace, which is not good. Also, because it is `../../../` and not `../../../check_dir`, artifacts are on the same level as `extendr` repo folder. If I run rcmdcheck on my local machine, then the `../` folder will look like:
```
extendr
extendrtests.Rcmdcheck
extendrtests_0.1.0.tar.gz
```
And I have to remember to delete these artifacts every time.

**Comment by clauswilke** [comment]
Yes, the path needs to be updated.

Unfortunately we're somewhat constrained in where we can run the check by the folder structure that Rcmdcheck imposes. It makes two nested subfolders before it creates the folder in which it actually places the package source code. If we want checking artifacts inside of `extendr` we need to move `extendrtests` one additional subfolder down.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke,
I think I found a better folder/path structure, if I make it work, I'll make a PR
