### ISSUE TITLE
"cannot find attribute `extendr` in this scope"

### ISSUE THREAD

**Issue by bovee** [extendr/extendr#18]
I just stumbled across this repo and it's really cool! Thanks!

I was trying to get a toy example running and I hit this error. I think it's fixed already because I switched my `Cargo.toml` from `extendr-api = "0.1.3"` to `extendr-api = { git = "https://github.com/extendr/extendr" }` and it works, but I'm making this issue in case anyone else hits it too.

**Comment by lebensterben** [comment]
you get the name wrong. it's "extendr"

**Comment by andy-thomason** [comment]
Thanks for bringing this to our attention. We may need to document the git Carg.toml method in the README.

The API is still somewhat unstable and evolving but any feedback is welcome.
