### ISSUE TITLE
R CMD check results not uploaded

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#183]
I noticed in this failed run
https://github.com/extendr/extendr/pull/182/checks?check_run_id=1952491229
that the step that uploads results is not triggered correctly:
https://github.com/extendr/extendr/blob/ddef053a00ca751921f36f7c98805e85c77000fc/.github/workflows/test.yml#L248-L260
I believe I messed up with the conditions when wrote this, can anyone take a look and help me diagnose this?

**Comment by clauswilke** [comment]
I'm not sure I can be of help, other than to say that I've written similar code in the past and it also didn't work. Checking individual steps for success in this manner doesn't seem to work, even though one would think that it should. It's possible that on failure you never even get to this step, though I don't understand how the `if: failure()` blocks work.

**Comment by yutannihilation** [comment]
It seems the `if` field needs to be

``` yaml
   if: failure() && steps.rextendr_check.outcome != 'success' 
```

(or `always()`?) according to this page: https://qiita.com/t0yohei/items/9285e61f8358de7f60a7 (Sorry, in Japanese...)

Actually, the document implies that we need to include some status function other than `success()`.

> If your if expression does not contain any of the status functions it will automatically result with `success()`. 
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation,
Ah, ok, this makes sense now. Would you like to do this?

**Comment by yutannihilation** [comment]
Here it is! #185

Btw, I found `!= 'success'` triggers even when it's not executed, so maybe this is almost the same as just specifying `failures()`?

![image](https://user-images.githubusercontent.com/1978793/108858704-cbd1d900-762f-11eb-85f8-362b69d4065b.png)
