### ISSUE TITLE
Serde for R objects

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#186]
I've been reading up on the Serde interface which might provide a better
method of conversion to/from R objects.

We would need to implement Deserialize and Serialize for R objects
and find a solution that works with the existing mechanism until we are
confident it works.

This would enable us to use serde_derive to generate wrappers for complex
Rust types.

This is a bigger challenge that I first thought and I may need some help.

**Comment by jbabyhacker** [comment]
It may be possible to do this by using a combination of reticulate and serde-pickle. Basically you would serialize your R structure to a pickle format using reticulate, then deserialize it with serde-pickle.

https://rstudio.github.io/reticulate/
https://crates.io/crates/serde-pickle

**Comment by andy-thomason** [comment]
Serde interfaces require a bit of work and there is no shortcut to doing it properly.

Serialisation is not so bad, but deserialisation is much more complex.
We also want to make it zero-copy if possible.

https://serde.rs/impl-serialize.html
https://serde.rs/impl-deserialize.html

**Comment by andy-thomason** [comment]
The upside is that many types support Serde and a Serde wrapper or attribute
would open up a large set of interfaces.

**Comment by malcolmbarrett** [comment]
Would implementing these open the gates a bit more to wrapping other types in serde, e.g. converting TOML, YAML, JSON, etc to R objects? I think a (separate) package that is a reliable and general serialized format library might be useful despite the existence of R packages that cover specific types (yaml is stuck on YAML 1.1 because of its dependency, TOML only has so-so support in R, and converting between formats only has so-so support, mostly via blogdown, which is a weird package to support that functionality).

**Comment by andy-thomason** [comment]
The intention was to be able to convert objects to/from R objects by implementing

```
  serde_r::from_r(...);
```
And
```
  serde_r::to_r(...)
```

Anything that supports/derives serde could then be converted to/from R.

But you suggestion is also interesting to manually write a serde that takes a general
R object and interfaces with serde_json and friends.

**Comment by andy-thomason** [comment]
I was working on an independent serde for the R serialisation format
that could work stand-alone. That is partly why I became involved with this project.

**Comment by malcolmbarrett** [comment]
Very interesting! Yes, if ever you want to explore that type of package, I'd be happy to collaborate

**Comment by andy-thomason** [comment]
I have a prototype for R data serialisation here:

https://github.com/andy-thomason/rdata

It does not require the R libraries.

We could massage this into a Serde interface.
