### ISSUE TITLE
Should we export unsafe functions (e.g. protect and unprotect)?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#197]
On #196, we found clippy warns that there's `# Safety` section missing from unsafe functions' doc. I think we should add this, not only because clippy warns, but also because the users will probably need some safety advice to use these functions properly. I think I don't have enough knowledge to write up this, so let me just file this here.

```
warning: unsafe function's docs miss `# Safety` section
  --> extendr-api/src/ownership.rs:24:1
   |
24 | / pub unsafe fn protect(sexp: SEXP) {
25 | |     let mut own = OWNERSHIP.lock().expect("protect failed");
26 | |     own.protect(sexp);
27 | | }
   | |_^
   |
   = note: `#[warn(clippy::missing_safety_doc)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc

warning: unsafe function's docs miss `# Safety` section
  --> extendr-api/src/ownership.rs:29:1
   |
29 | / pub unsafe fn unprotect(sexp: SEXP) {
30 | |     let mut own = OWNERSHIP.lock().expect("unprotect failed");
31 | |     own.unprotect(sexp);
32 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc
```

**Comment by andy-thomason** [comment]
In fact I have deliberately not documented these functions to deter their use.

They should probably be pub (crate) and clippy may then be happy.

**Comment by andy-thomason** [comment]
There is a good argument to void all unsafe functions in the public API.

The exception to this is `libR-sys` which is *all* unsafe.

**Comment by andy-thomason** [comment]
Nice work, anyway.

**Comment by clauswilke** [comment]
I'm quite confident that we need these unsafe functions in the public interface. There will always be use cases where somebody needs to call some C functions that we haven't covered in extendr (for example, when calling C functions from extension packages). It would be unfortunate if people would have to reimplement these unsafe helper functions because extendr doesn't export them.

**Comment by yutannihilation** [comment]
@clauswilke
Are you okay with closing this issue? I personally feel it's fine at least for now and we can file a new one when the need for those unsafe functions actually arises.

**Comment by clauswilke** [comment]
Yes, that's fine.

**Comment by yutannihilation** [comment]
I see, thanks for confirming.
