### ISSUE TITLE
Modify call! macro to parse the initial string into a R expression object.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#206]
The call! macro currently treats the first string as a symbol.

```
call!("+", 1, 2)
```

It could parse the string into an R language expression allowing a much larger range of operations
or take an Robj if not a quoted string.

```
call!("fred::jim", 1, 2)
call!(my_ojbect, 1, 2)
```

**Comment by clauswilke** [comment]
Could we implement this for 0.3.0? I think it would address my concerns about not having a simple way of calling functions in extension packages.
