### ISSUE TITLE
Fast versions of built-in functions.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#207]
We can generate better approximations to log, exp, powf and R stats functions
using polynomial approximations.

I am working on a crate "doctor_syn" which is aimed at generating the polynomials
for these functions at compile time.

The resulting polynomial expansions are usually just as accurate as the libm equivalents
but up to two hundred times faster on good hardware because they vectorise.

**Comment by andy-thomason** [comment]
We could also add parallel versions of functions to the Real datatype (iterator and wrapper of a REALSXP type).

**Comment by clauswilke** [comment]
This feels a bit out of scope to me. Wouldn't it be better to have something like this in a separate crate?

**Comment by yutannihilation** [comment]
I too feel this is out of the scope of this repo, but it would be great to have it under extendr org.
