### ISSUE TITLE
When and how will we drop support for 32-bit Windows?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#210]
It turned out it's only a matter of time before we drop the support as R will drop it,

> It is planned that the 4.1.x series will be the last to support 32-bit Windows, with production of binary packages for that series continuing until early 2023.
(<https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.html>)

and, R 4.2 is supposed to be released on the next spring.

> The overall release schedule is to have annual x.y.0 releases in Spring, with patch releases happening on an as-needed basis.
(<https://developer.r-project.org/>)

One year. I feel it's not very near, but not very far future. So, I believe it's not too early to discuss how to let our support for 32-bit Windows sunset nicely, though I have no idea at the moment.

**Comment by Ilia-Kosenkov** [comment]
Right now there should be no problem with 32-bit support (except for maybe one-two disabled tests).
We can probably leave things as is until R-devel hits 4.2, at which point we can gradually disable 32-bit pipelines.

I wonder if R is going to provide ARM builds, there are Mac and Windows laptops running ARM already on the market.

**Comment by andy-thomason** [comment]
It would be a blessed relief to drop Win32. I remember Win16 living on like the zombie that
refused to die!

They have finally decommissioned the 32 bit Viglen machines from the NHS in the UK which will
wipe out a large tranche of the userbase.

I do like the short function definitions. `\(x) x + 1`.

They have updated C++ to C++14, It will be a great day when they bundle `cargo`.

**Comment by yutannihilation** [comment]
>  We can probably leave things as is until R-devel hits 4.2, at which point we can gradually disable 32-bit pipelines.

I agree, at least at the moment. Hope we won't suffer from 32-bit Win related issues until v4.2...

> I remember Win16 living on like the zombie that refused to die!

Oh, I didn't know Win16. I'm afraid Win32 might also become such a zombie (c.f. https://twitter.com/dvaughan32/status/1383431385755516928), but I'm really happy that we don't need to devote ourselves to terminating them.

**Comment by yutannihilation** [comment]
I think we can consider this now. R 4.3 should be only about half a year away.

**Comment by eitsupi** [comment]
I think this has been done via the 0.6.0 release.

**Comment by CGMossa** [comment]
Perfect! Thanks @eitsupi, closing this then.
