### ISSUE TITLE
CI failure on master

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#211]
https://github.com/extendr/extendr/runs/2360651290#step:10:122

```
  stderr:
  Error: Error: cannot add binding of 'myvar' to the base environment
  Execution halted
  
  test src/rmacros.rs - var (line 40) ... FAILED
```

**Comment by malcolmbarrett** [comment]
This may have to do with recent changes in R devel to lock the base env https://github.com/wch/r-source/commit/26165fd368d3f55f4535e5b6d0628e9dfa9caa17

**Comment by yutannihilation** [comment]
Ah, thanks! I remember I saw it on R-devel's NEWS. Then we can just fix this test to use a newly created empty env. 

https://github.com/extendr/extendr/blob/7b8112ed0aed8d5e59bf1e2c04aeb82483db51b0/extendr-api/src/rmacros.rs#L44-L45

But, I also feel base env is not what we want for `current_env()` here. I'm not immediately sure how this should be fixed...

**Comment by malcolmbarrett** [comment]
rlang's definition of `current_env()` is just `parent.frame()`, so maybe that's a better option

**Comment by yutannihilation** [comment]
I think it makes sense when it's used with R code, so it's probably different in the case of Rust (or C/C++).

**Comment by yutannihilation** [comment]
What `current_env()` does is basically `R_GlobalContext->sysparent`.

https://github.com/extendr/extendr/blob/7b8112ed0aed8d5e59bf1e2c04aeb82483db51b0/extendr-api/src/functions.rs#L84-L86

> ```
> /* Return the current environment. */
> SEXP R_GetCurrentEnv() {
>     return R_GlobalContext->sysparent;
> }
> ```
https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/main/context.c#L795-L798

According to the doc,

> ```
>  *	sysparent	the environment the closure was called from
> ```
https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/main/context.c#L46

so this is probably intended to be called from another frame, but probably it's not the case when it's used in Rust code?

**Comment by andy-thomason** [comment]
`current_env()` will be set by R when calling a function.

This means that `var!` will access variables in your calling function first.

Unfortunately, it is not easy to test this outside of R as there is no way I know to create a calling
context frame.

**Comment by andy-thomason** [comment]
I have been thinking of how we can wrap a closure in an R object without registering a function...

This may or may not be possible.

**Comment by andy-thomason** [comment]
I was sure that I disabled this test in the interim.

**Comment by yutannihilation** [comment]
> This means that `var!` will access variables in your calling function first.

Sorry, I misunderstood the intention of the test. I see.

Let's disable the test again with some TODO comment (or just file an issue).

**Comment by andy-thomason** [comment]
Yes. I'll try to figure something out. It may be the `catch_r_errors()` will build a context.

**Comment by yutannihilation** [comment]
The test failure is already disabled by https://github.com/extendr/extendr/commit/2b94948b433811ebb7455cf12233f311e7f91693 (thanks Andy), so this isn't a blocker for the release of v0.3.0. Let's add some more comments so that we can remember why the test is disabled, and then close this issue for now, I'll try a pull request.

**Comment by yutannihilation** [comment]
Sorry, I accidentally pushed this to master directly, instead of creating a pull request... Anyway I added this TODO comment, so let's close this issue.

https://github.com/extendr/extendr/commit/5f6a1453ca2e0c88335e4e4513b77046005592d1
