### ISSUE TITLE
Developer's guide

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#212]
(Came from a discussion on the Discord)

I think extendr has a few topics that developers need to know before starting their contributions. For example,

* Procedural macro
* R internals

So, it's probably good to have some "Developer's guide" (`MAINTAINERS_GUIDE.md`, or a new file?) and list up some learning resources on it. I guess it's easier to use a wiki first so that everyone can write casually, and eventually commit it to the repository itself.

**Comment by andy-thomason** [comment]
Looks like a good idea.

I would like to get started on a long form documentation for extendr.

I'm going to be teaching Rust online for the next few days and can
help anyone who wants to learn some more.

**Comment by Ilia-Kosenkov** [comment]
@andy-thomason, in what form, at what UTC time?

**Comment by andy-thomason** [comment]
The lectures are for a private client, but I'll do some similar talks for my Oxford Rust group soon.

My next public speaking engagement is for Cardiff Rust on the 17th. https://www.meetup.com/rust-and-c-plus-plus-in-cardiff/

If you would like, I can pair up with you to do a quick 1:1 after next week.

**Comment by Ilia-Kosenkov** [comment]
@andy-thomason, thank you, I'll save the date of your public talk.
Speaking of 1 on 1, perhaps if there are other extendr contributors interested in this, we can make some sort of an online meetup -- not only social things but also development?

**Comment by andy-thomason** [comment]
I'll try to organise something.

I think that @dfalbel and others may be interested.

I can make it very gentle!

I'm going to be quite busy until next week, however.

Andy.

**Comment by dfalbel** [comment]
I am definitely interested!

**Comment by CGMossa** [comment]
I'm also earger to get more tools to contribute to this thing.

**Comment by CGMossa** [comment]
Developer's guide hasn't happened. We need to revive this project at a later date when the community is larger, and a clear scope can be made. Closing for now.

**Comment by multimeric** [comment]
I don't think we need to close issues such as this if they're unresolved. There's no harm in them hanging around as potential future directions for contributors.

**Comment by CGMossa** [comment]
I know it seems a little bit hastily to do this. But these stale conversations are not good for anyone. I'd rather close them. Reopen them. See if the new ones yield contributors, ideas, thoughts, or anything. But having an issue up with smart conversation, of people that are mostly in-active is not healthy.
