### ISSUE TITLE
Simplify copyright notice

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#214]
Currently our copyright notice individually lists people who have made contributions. The Linux foundation discourages this practice: https://www.linuxfoundation.org/en/blog/copyright-notices-in-open-source-software-projects/

I suggest we simplify the copyright notice. We have already done this in rextendr.

**Comment by andy-thomason** [comment]
This is a bit tricky as I am obliged to explicitly mention Genomics PLC as a copyright holder.

I've fudged this by adding a CONTRIBUTORS.md (and adding Ilya and Daniel).
