### ISSUE TITLE
Calling R functions in extension packages

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#216]
I would like to have an example (and possibly additional API features, to make the sample simpler) to call a function in an R extension package from Rust. As an example, consider this R code:

```r
tibble::tibble(a = 5, b = "hello")
```
I know we can use the `R!` macro but that's rather high overhead. Instead, I'd like to have code that retrieves the function object and then creates the call and executes it.

In C, we would do something like the following:
```c
SEXP ns, fun;

PROTECT(ns = get_namespace("tibble")); 
PROTECT(fun = findFun(install("tibble"), ns));

// construct and evaluate call
...

UNPROTECT(2);
```

The example for this should live somewhere in the extendr API documentation.

**Comment by andy-thomason** [comment]
I'm working on a PR for this where the first parameter of the call! macro is evaluated rather like the R! macro.

This should generate either a function, special or builtin which should be callable.

In reality, almost all R objects are callable.

Example:

```
   call!("data.frame", a=r!(1), b=r!(2))?;
   call!("`+`", r!(1), r!(2))?;
```

These translate into:

```
    eval_string("xxx")?.call(pairlist!(...))?
```

Some of the tests are still failing, but I'm hopeful of doing a push this evening.

**Comment by andy-thomason** [comment]
Of course:

```
    call!("tibble::tibble", a = 5, b = "hello")
```

is also possible...

**Comment by clauswilke** [comment]
This would work for now, but if at all possible I'd rather not call `eval_string()` on every function call. It will make callbacks from Rust to R very slow. Is there no way to just retrieve the function object directly, without calling eval?

It would also be super useful to be able to cache a function object, if it's a function we need to call many times.

**Comment by clauswilke** [comment]
(Maybe a simple option would be to build the cache into `call!()`, so it calls `eval_string()` only once each time it encounters a new function name?)

**Comment by andy-thomason** [comment]
I was planning to cache the parsing result of `eval_string` as that should be constant.

We could also cache the *result* of `eval_string`, but that is not always what we desire.

A function `eval_string_once` might do the job.

**Comment by andy-thomason** [comment]
I could also use an arbitrary Robj as the first parameter.

let fred = R!(fred)?;
call!(fred, 1, 2 , 3);

This would enable you to cache the function yourself and would be faster than using
a hash map.

**Comment by clauswilke** [comment]
> I could also use an arbitrary Robj as the first parameter.

I think this is fine, but we'd still need some sort of function lookup mechanism, even if under the hood it calls `eval_string` and uses caching. E.g.:

```
let tibble = get_R_function!("tibble::tibble")?;
call!(tibble, a = 1, b = 2);
```

I wouldn't want to have to think about caching every time I need a function call.

**Comment by andy-thomason** [comment]
Just using R! will fetch the function.

```
let tibble = R!("tibble::tibble")?;
call!(tibble, a = 1, b = 2);
```

The expensive part is likely to be protecting the pairlist building against multi-thread access.

`Pairlist::from-pairs` uses `single_threaded` which I need to profile. It may be Ok, however.

```
    pub fn from_pairs<NV>(pairs: NV) -> Self
    where
        NV: IntoIterator,
        NV::IntoIter: DoubleEndedIterator,
        NV::Item: SymPair,
    {
        crate::single_threaded(|| unsafe {
            let mut num_protects = 0;
            let mut res = R_NilValue;
            for nv in pairs.into_iter().rev() {
                let (name, val) = nv.sym_pair();
                let val = Rf_protect(val.get());
                res = Rf_protect(Rf_cons(val, res));
                num_protects += 2;
                if !name.is_unbound_value() {
                    SET_TAG(res, name.get());
                }
            }
            let res = Pairlist {
                robj: new_owned(res),
            };
            Rf_unprotect(num_protects as i32);
            res
        })
    }

```

In future iterations, we could use the appropriate `RF_lang<N>` constructor.

**Comment by clauswilke** [comment]
> Just using R! will fetch the function.

Yes, but then we're back to calling eval every time we need a function call.

**Comment by andy-thomason** [comment]
We could cache the functions in static variables.

```
call!(fred, 1, 2, x)

static FRED : SEXP = std::ptr::null();

if !FRED.is_null() {
  FRED = R!(fred)?.get(); }
  V1 = r!(1)?.get();
  V2 = r!(2)?.get();
}

Ok(new_owned(RF_eval(Rf_lang4(FRED, V1, V2, x.get()), R_GlobalEnv))
```

Or something similar.

**Comment by clauswilke** [comment]
Actually, thinking some more about it, now I'm not sure caching will work at all. Consider this R example:

``` r
f <- function(x) x
g <- f

f <- function(x) 2*x

identical(f, g)
#> [1] FALSE
```

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

A Rust implementation with caching would find that `f` and `g` are identical in the last line.

**Comment by andy-thomason** [comment]
Yes. The caching would have to be optional.

**Comment by andy-thomason** [comment]
Some things, like symbols and literals, can always be cached.

**Comment by andy-thomason** [comment]
We can add attributes to proc macros like this:

```
#[caching_enabled]
call!("fred",1, 2, 3)?;
```

**Comment by clauswilke** [comment]
Somehow I feel this is all rather complicated. Is there any reasons why we can't have Rust equivalents to `get_namespace()` and `findFun()` that I would use in C?

**Comment by andy-thomason** [comment]
We do have these functions. 

pub fn find_namespace<K: Into<Robj>>(key: K) -> Result<Environment>

and

pub fn find_function<K: TryInto<Symbol, Error = Error>>(&self, key: K) -> Result<Robj> {

**Comment by andy-thomason** [comment]
But worth noting that like the C versions they call R code and may throw an R error.

**Comment by clauswilke** [comment]
Apologies if I'm repetitive, but I feel we just keep missing each other. `find_function()` doesn't take a namespace argument and instead works in a given environment. Maybe we need to add something like `find_function_in_namespace()`?

I'd like to do the equivalent of this C code:
```
SEXP ns, fun;

PROTECT(ns = get_namespace("tibble")); 
PROTECT(fun = findFun(install("tibble"), ns));

// construct and evaluate call
...

UNPROTECT(2);
```

**Comment by yutannihilation** [comment]
I too am sorry to be repetitive, but I'd also add macro doesn't work when we want to supply variable length of arguments dynamically (c.f., https://github.com/extendr/extendr/issues/195#issue-836534329). IMHO, in regard to calling functions, we should not expect too much on macro.

**Comment by andy-thomason** [comment]
The most efficient way will always be to get the function object and keep it.

In a package, you can make a context struct with a few Robj functions in it.

In a loop, you can get the function object in advance.

There is a function to get the namespace registry (I'll have to look it up).
Given this, you can get a namespace and anything in it.

Alternatively, you can just use:

```
let myfun : Function = R!(mynamespace::myfun)?.into();
```

Do this once and cache it.

Now we can call it with:

```
myfun.call(pairlist!(a=1, 2, c=3))
```

We can't get around the macro unless we drop the named parameters.

```
myfun.call((1, 2, 3))
```

The official call overload is still in beta in Rust. So we may need to shift this
with time so you can do:

```
myfun(1, 2, 3)
```

We could also have a macro to generate wrappers for namespaced calls:

```
[extendr(external="fred::foo")]
fn foo(x: i32, y: &str);
```

For example.

**Comment by clauswilke** [comment]
Ok, I've now figured out two ways that work. I'll benchmark them against `R!()` next.

``` r
library(rextendr)

rust_eval(
  code = r"-(
    let tibble_ns = find_namespace("tibble")?;
    let tibble_sym = r!(Symbol::from_string("tibble"));
    let tibble = tibble_ns.find_function(tibble_sym)?;
    tibble.call(pairlist!(a=1, b=2))
 )-",
 patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr"))
)
#> ℹ build directory: '/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T//Rtmpm22796/filefb532fdd83a2'
#> ✓ Writing '/private/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T/Rtmpm22796/filefb532fdd83a2/target/extendr_wrappers.R'.
#> # A tibble: 1 x 2
#>       a     b
#>   <int> <int>
#> 1     1     2

rust_eval(
  code = r"-(
  let tibble_sym = r!(Symbol::from_string("tibble"));
  let tibble = tibble_sym.clone().double_colon(tibble_sym)?;
  tibble.call(pairlist!(a=1, b=2))
  )-",
  patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr"))
)
#> ℹ build directory: '/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T//Rtmpm22796/filefb532fdd83a2'
#> ✓ Writing '/private/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T/Rtmpm22796/filefb532fdd83a2/target/extendr_wrappers.R'.
#> # A tibble: 1 x 2
#>       a     b
#>   <int> <int>
#> 1     1     2
```

<sup>Created on 2021-07-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by clauswilke** [comment]
Ok, it seems like @andy-thomason was correct. Using the `R!` macro is quite efficient. I see no meaningful difference to the other approaches or to calling regular R code.

``` r
library(rextendr)

rust_function(
  code = r"-(
fn f1() -> Result<Robj> {  
    let tibble_ns = find_namespace("tibble")?;
    let tibble_sym = r!(Symbol::from_string("tibble"));
    let tibble = tibble_ns.find_function(tibble_sym)?;
    Ok(tibble)
}
)-",
 patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr"))
)
#> ℹ build directory: '/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T//RtmpHLzShh/filefc097e9a202a'
#> ✓ Writing '/private/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T/RtmpHLzShh/filefc097e9a202a/target/extendr_wrappers.R'.

rust_function(
  code = r"-(
fn f2() -> Result<Robj> {
    let tibble_sym = r!(Symbol::from_string("tibble"));
    let tibble = tibble_sym.clone().double_colon(tibble_sym)?;
    Ok(tibble)
}
  )-",
  patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr"))
)
#> ℹ build directory: '/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T//RtmpHLzShh/filefc097e9a202a'
#> ✓ Writing '/private/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T/RtmpHLzShh/filefc097e9a202a/target/extendr_wrappers.R'.

rust_function(
  code = r"-(
fn f3() -> Result<Robj> {
    let tibble = R!("tibble::tibble")?;
    Ok(tibble)
}
  )-",
  patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr"))
)
#> ℹ build directory: '/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T//RtmpHLzShh/filefc097e9a202a'
#> ✓ Writing '/private/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T/RtmpHLzShh/filefc097e9a202a/target/extendr_wrappers.R'.

f4 <- function() tibble::tibble

microbenchmark::microbenchmark(f1, f2, f3, f4)
#> Unit: nanoseconds
#>  expr min lq  mean median uq  max neval
#>    f1  31 32 49.23     33 33 1599   100
#>    f2  31 32 38.41     33 33  528   100
#>    f3  31 32 35.24     33 33  265   100
#>    f4  30 32 34.67     33 33  206   100
```

<sup>Created on 2021-07-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by multimeric** [comment]
Can we close this issue as it seems like there's no concrete action items? The consensus seems to be that `R!` is fine for this purpose.
