### ISSUE TITLE
Update impl_try_from_scalar! to check limits and rounding.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#223]
Currently, `impl_try_from_scalar!` uses "as" to convert between scalar types.

This doesn't do type checking.

We could maybe use TryFrom on scalar types to do the conversion.

We could add an error type of CouldNotConvert(Robj) in case this fails.

So if we do:

```
#[extendr(use_try_from = true)]
fn test_i32(val: i32) -> i32 {
    val
}


// Then this should fail with Error::CouldNotConvert
new_owned(wrap__test_i32(r!(1.5).get()))

```

Likewise for i16 and r!(32768)

**Comment by clauswilke** [comment]
Agreed. Is it possible to somehow generate a meaningful error message, such as `Input value 1.5 cannot be converted to i32`?

**Comment by andy-thomason** [comment]
The display implemenation for the error is here:

https://github.com/extendr/extendr/blob/2103979ab085376194b1f51a5a20b28e2f165691/extendr-api/src/error.rs#L76-L137

This converts the error into a string and we should make these errors as readable as possible.

Currently, each of these errors takes a Robj that represents the error.

We could define our error as:

`CouldNotConvert(Robj, &str)`

Where the second parameter is the type name.

The Display line then becomes:

```
   Error::CouldNotConvert(robj, typename) => write!(f, "Input Value {} could not be converted to {}", robj, typename),
```

**Comment by andy-thomason** [comment]
A small PR with just one type conversion would be a good starter here.

**Comment by yutannihilation** [comment]
Sorry, maybe I don't understand the strategy of this issue.

> We could maybe use TryFrom on scalar types to do the conversion.

Is this suggesting to use `TryFrom`, instead of `as`, to convert between Rust's primitive types (e.g., `f64` to `i32`)...? Or, is this just saying that we can implement `TryFrom` for scalar `Robj` with various checkings, so that we can use it around? If the former, `TryFrom` is implemented only for int-to-int conversion (c.f. <https://doc.rust-lang.org/std/convert/trait.TryFrom.html>), so I'm a bit confused.

**Comment by clauswilke** [comment]
I thought the idea was to implement `TryFrom` for scalar `Robj` types.

**Comment by andy-thomason** [comment]
In:

https://github.com/extendr/extendr/blob/be761f31141a1bc34c0774041407e9c0f4e722ff/extendr-api/src/robj/try_from_robj.rs#L16-L28

We could replace the `v[0] as Self` with v[0].try_into()?

This would require a conversion from the respective errors into our Error type also.

This code on playground shows how this works:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1e7b38b47cecf4323bc8c7b9cec7bb44

**Comment by yutannihilation** [comment]
> We could replace the `v[0] as Self` with v[0].try_into()?

Yeah, but I meant this is only meaningful for checking the limits on int-to-int conversion. To check the rounding on float-to-int conversion (i.e. let the conversion from `1.5` to a int type fail), we need other implementation than `TryFrom` provided by std, if I understand correctly.

**Comment by clauswilke** [comment]
My assumption was we wouldn't do any automatic conversion from float to int. Do you think that's too restrictive, considering that the basic numeric datatype in R is a float?

**Comment by yutannihilation** [comment]
Oh, I just thought we follow vctrs' rule here. Sorry, I might forget the discussion on this topic.

**Comment by clauswilke** [comment]
I don't really know what vctrs does. You're probably right that we should convert if no rounding is needed.

**Comment by brendanrbrown** [comment]
I understood the original post, and the follow-up playground example, to be asking for something like this dummy example

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bfcc6f6115fb748a64e666e335911f12

the [vctrs behavior](https://vctrs.r-lib.org/reference/vec_cast.html) converts successfully if truncating to integer doesn't change the value. clearly, i don't yet have much experience with writing Robj conversions but perhaps something like the example above might work here as well.

**Comment by clauswilke** [comment]
Yes, I think it would be possible to implement something like this.

**Comment by andy-thomason** [comment]
For floats it is not quite enough to check that the number is an integer.

The simplest way is to check the round trip.

```
if myfloat as i32 as f64 == myfloat {
  Ok(myfloat as i32)
}
```

This also excludes NaNs.

Note that strange things will happen when the mantissa is maxed out.
Then `a + 1 == a` as floats cannot represent large integers precisely.
This is unavoidable.

**Comment by andy-thomason** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=54946889564256c0bcb86374844e47b5

**Comment by clauswilke** [comment]
> The simplest way is to check the round trip.

Amazing that the compiler doesn't optimize this away. Is it guaranteed to never get removed in an optimization?

**Comment by andy-thomason** [comment]
Anything float is hard to optimise as the arithmetic is not associative (ie. a + (b + c) != (a + b) + c)

The exception is "fast math" options which are not global optimisations in Rust.

f64 can represent everything up to 2**53 as an integer and even integers up to 2**54 etc.
but this cannot be statically analysed unless using constants.
