### ISSUE TITLE
Integration tests for TryFrom conversions.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#224]
We should update the integration tests to cover the full spectrum of types.

If necessary add more tests than we have conversions for, to act as incentive to add more conversions.

We may also want to check that ALTREP types are converted correctly.

See https://github.com/extendr/extendr/tree/master/tests/extendrtests

**Comment by clauswilke** [comment]
To provide a better pointer to where in the code this lives.

The Rust test functions are defined here:
https://github.com/extendr/extendr/blob/2103979ab085376194b1f51a5a20b28e2f165691/tests/extendrtests/src/rust/src/lib.rs#L19-L49

And tests from R are then called here:
https://github.com/extendr/extendr/blob/2103979ab085376194b1f51a5a20b28e2f165691/tests/extendrtests/tests/testthat/test-type-conversion.R#L1-L37

I wrote this set of tests mostly to demonstrate how writing tests works. They are clearly not exhaustive.

@brendanrbrown This might be a good issue for a first PR.

**Comment by brendanrbrown** [comment]
just to confirm that i'll make a PR for this --- shouldn't take too long.

**Comment by andy-thomason** [comment]
I'm going to migrate more tests to the tests directory in time.

Feel free to make more source files.

Just a small PR would be great for a first one, we can expand on this.
