### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by waynelapierre** [extendr/extendr#23]
I feel like the library name extendr sounds confusing and unclear. Is it possible to just call it as something similar to RustR?

**Comment by andy-thomason** [comment]
The intention is quite different from RCpp and R-rust and a few other abandoned RCpp-alikes already exist.

RCpp and R-rust require in-depth knowledge of the R-internals API and we wish to make life
a lot easier than that. Rust is a very flexible language and can embed other languages within
itself (like R) using procedural macros.

The lower case name ending in 'r' is a convention used by dplyr and tidyr.
