### ISSUE TITLE
Forward DEP_* environmental variables from libR-sys crate

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#237]
https://github.com/extendr/libR-sys/issues/67#issuecomment-882137017

**Comment by yutannihilation** [comment]
After reading the related documents, I feel this is impossible, or at least inappropriate. These `DEP_` environmental variables are exclusively for "*-sys" packages, which are dedicated to linking to system libraries.

https://doc.rust-lang.org/cargo/reference/build-scripts.html#-sys-packages:

> Any package named foo-sys should provide two major pieces of functionality:
> 
> * The library crate should link to the native library libfoo. This will often probe the current system for libfoo before resorting to building from source.
> * The library crate should provide declarations for functions in libfoo, but not bindings or higher-level abstractions.


> Other -sys packages can take advantage of the `DEP_NAME_KEY=value` environment variables to better integrate with other packages.

While we probably can specify `link` in `Cargo.toml` to provide `DEP_*` environmental variables, 

* extendr-api doesn't satisfy the definition of "*-sys" package.
* we cannot link to "R" as the name is already used in `libR-sys`; I got this error: 
> failed to select a version for `libR-sys`. (...snip...) the package `libR-sys` links to the native library `R`, but it conflicts with a previous package which links to `R` as well: package `extendr-api v0.2.0

Is this that non-sys crates are not allowed to expose the differences between the versions of underlying C libraries...?

**Comment by clauswilke** [comment]
I think it would be possible (and preferable) in extendr to turn these environmental variables into cfg attributes that then can be used by downstream libraries. I've seen other libraries do this, but I don't recall where right now. I also don't know how this is done.

**Comment by yutannihilation** [comment]
Oh, can `cfg` attributes be forwarded to downstream? If so, it's nice. I'll investigate.

**Comment by clauswilke** [comment]
I think we'd want something like this: https://crates.io/crates/rustversion

**Comment by andy-thomason** [comment]
Thomas did something like this in a much earlier PR.

**Comment by andy-thomason** [comment]
I've been reading http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/cargo/reference/config.html

You can set vars like

```
CARGO_FOO_BAR=x
```

To get
```
foo.bar = x
```

It would be interesting to try this.

**Comment by yutannihilation** [comment]
> I think we'd want something like this: https://crates.io/crates/rustversion

This look nice!

> You can set vars like
> 
> ```
> CARGO_FOO_BAR=x
> ```
> 
> To get
> 
> ```
> foo.bar = x
> ```

The document says this is how to override the key in cargo configuration, so I think this is a bit different than what we want here?

**Comment by clauswilke** [comment]
Maybe this is helpful: https://doc.rust-lang.org/cargo/reference/build-script-examples.html#conditional-compilation

**Comment by yutannihilation** [comment]
I think it's the case when the crate directly depends on a "*-sys" crate. To export it to downstream, we need to form it as macros, if I understand correctly.
