### ISSUE TITLE
Graphics engine

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#239]
libR-sys now has bindings for Graphics engine (https://github.com/extendr/libR-sys/pull/71). I guess we are interested in providing the corresponding interface in extendr-* family crate. Should it be implemented within extendr-api crate? Or, do we need to create a new one (e.g. extendr-graphics)?

**Comment by clauswilke** [comment]
Yeah, I've been wondering this also. A separate crate would be nice, but I think we're running into the issue of unsafe functions (#197). Maybe somebody just needs to start and see how it goes.

I will eventually need to call functions such as `GEcurrentDevice()`, `GEStrMetricI()`, or `GEfromDeviceWidth()`.

**Comment by yutannihilation** [comment]
Thanks. Do you know some simple example of C/C++ code using graphics engine? I think we should start from mimicking it in Rust.

**Comment by andy-thomason** [comment]
Not a lot easilly searchable.

There is a lot of code in the R source code that illustrates it.

As usual, there are no comments :)

**Comment by andy-thomason** [comment]
Anyone for asteriods?

**Comment by clauswilke** [comment]
Here's a simple function looking up string metrics:
https://github.com/clauswilke/sinab/blob/955d38cfb1dc1833433548ff638baf315daa4a4d/src/render_device.c#L221-L242
That's my main use case at this time.

And here's an even simpler function that returns the height of the current graphics device, in inches:
https://github.com/clauswilke/sinab/blob/955d38cfb1dc1833433548ff638baf315daa4a4d/src/render_device.c#L244-L248

Overall, GraphicsEngine.h does actually have some amount of comments, and also many functions are pretty obvious. For example, look at all the drawing functions. Seems pretty clear how to draw a circle or a line.
https://github.com/wch/r-source/blob/trunk/src/include/R_ext/GraphicsEngine.h#L405

**Comment by andy-thomason** [comment]
It would be a fairly mechanical job to write traits for these types.

Would be want an abstraction for units, or just keep the interface 1:1?

How does R Studio render graphics? Does it convert to SVG or some other intermediate?
Can we do more than the **cairo** inspired interface it presents and support **webgpu**
for example?

**Comment by clauswilke** [comment]
> Would be want an abstraction for units, or just keep the interface 1:1?

I would keep the interface 1:1. Most users will not even interact with the graphics engine directly but rather use higher-level interfaces such as grid. Anybody who does want to interact with the graphics engine will likely want to think about low-level details and thus want a 1:1 mapping of the interface to Rust.

> Can we do more than the cairo inspired interface it presents and support webgpu
for example?

That would mean writing a new graphics device (not engine). I would stay away from that at this time.

**Comment by yutannihilation** [comment]
Thanks for the examples.

> I would keep the interface 1:1.

Does this mean the users can just use libR-sys directly? Are there still any motivation to create a dedicated crate for graphics engine?

**Comment by clauswilke** [comment]
Maybe the question is what 1:1 means. I'd want an interface that closely mirrors the C interface but that doesn't require me to write any unsafe Rust code. You'd need wrappers for graphics devices, graphics context, etc. That's a fair amount of code that otherwise every user of this header file would have to reimplement themselves.

**Comment by yutannihilation** [comment]
Makes sense, thanks for clarification.

**Comment by andy-thomason** [comment]
I'm training a class of Rust developers for the next few days.
I'll look at a high level abstraction layer for this when I'm less busy.

I also noticed that you have added Altrep to libR_sys, we should think about abstractions there.

**Comment by andy-thomason** [comment]
I was planning to start a PR for this.

Do any of you have experience using this API?

**Comment by clauswilke** [comment]
> Do any of you have experience using this API?

Only to the extent of the code examples linked in this comment: 
https://github.com/extendr/extendr/issues/239#issuecomment-885656586

**Comment by andy-thomason** [comment]
I've been doing some considerable reading over the weekend.

I'll try to get something simple done during the week without attempting to wrap the entire API.

**Comment by andy-thomason** [comment]
The design at present has wrappers for the device and the context.

The context also includes a 3x2 transformation matrix which simplifies working in units
other than device coordinates.

I've also added a Color struct with methods for constructing colours including the CSS predefined-colours.

I've tested this with the postscript and X11 drivers so far and it is working well.

How to handle the GEmode() calls is an interesting question and we may use a guard pattern
to generate a writable graphics context:

```
dev
  .begin().
  .line(...)
  .circle(...);
```

Rather than the curren:

```
  dev.mode_on();
  dev.line(...)
  dev.circle(...);
  dev.mode_off();
```

**Comment by clauswilke** [comment]
FYI, the R C API has various functions for color manipulation, including to convert R color names to color codes:
https://github.com/wch/r-source/blob/fe48e067ef26e160aa4b629d998a25ef6401577a/src/library/grDevices/src/colors.c#L1373

It's part of the graphics device code. (The graphics engine sits on top of the graphics device.)
