### ISSUE TITLE
Return type i64, u64, and u32 should be converted to REALSXP

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#240]
While we now can use `use_try_from = true` for type-checking, `TryFrom` is implemented one-way (R to Rust), if I understand correctly

I'm wondering what should happen in this case.

``` r
rextendr::rust_function(r"(
fn f() -> i64 {
  i64::MAX
}
)",
  patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr")),
)
#> ℹ build directory: '/tmp/RtmpR1VmHe/file161681b33c70a'
#> ✓ Writing '/tmp/RtmpR1VmHe/file161681b33c70a/target/extendr_wrappers.R'.

f()
#> [1] -1
```

<sup>Created on 2021-07-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by andy-thomason** [comment]
This is definitely incorrect.

It looks like it is truncating the i64 value to i32.

The result should be 2**63 as it is the closest
f64 value to 2**63-1. But we may also refuse to
convert as 2**63-1 is not representable and generate
a NA.

**Comment by andy-thomason** [comment]
The conversion to r objects is done via the `ToNumericValue` trait.

The i64 and u64 implementations should return `REALSXP` instead of `INTSXP`.

Definitely a bug.

**Comment by andy-thomason** [comment]
```
impl_integer_tvv!(i8);
impl_integer_tvv!(i16);
impl_integer_tvv!(i32);
impl_integer_tvv!(i64); <- should be to_real_tvv!(i64)
impl_integer_tvv!(u8);9
impl_integer_tvv!(u16);
impl_integer_tvv!(u32);
impl_integer_tvv!(u64); <- should be to_real_tvv!(U64)
```

**Comment by yutannihilation** [comment]
Thanks for taking a look, I got it. I guess `u32` is also the case.

**Comment by andy-thomason** [comment]
Yes, good thinking.

We do do usize already as a real.
