### ISSUE TITLE
Full ALTREP support

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#256]
I am much of the way to providing full ALTREP support.

We can now implement an ALTREP class using only two trait methods:

```
            #[derive(Debug, Clone)]
            struct MyCompactIntRange {
                start: i32,
                len: i32,
                step: i32,
            }

            impl AltrepImpl for MyCompactIntRange {
                fn length(&self) -> usize {
                    self.len as usize
                }
            }

            impl AltIntegerImpl for MyCompactIntRange {
                fn elt(&self, index: usize) -> i32 {
                    self.start + self.step * index as i32
                }
            }

            let mystate = MyCompactIntRange { start: 0, len: 10, step: 1 };

            let class = Altrep::make_altinteger_class::<MyCompactIntRange>("cir", "mypkg");
            let obj = Altrep::from_state_and_class(mystate, class);

            assert_eq!(obj.len(), 10);
            assert_eq!(obj.sum(true), r!(45.0));
            assert_eq!(obj.as_integer_slice().unwrap(), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
```

I would like to extend this to closures. Something like:

```
    Altrep::from_integer_fn(10000, |i| i * 10 + 100)
```

Unfortunately, the R headers have been significantly truncated without providing public support
back in July.

https://github.com/wch/r-source/commit/86b4a0641e889808ce204e28dd8bd19bbd1c8cbb

This will mean that direct dispatch to ALTREP methods will not be available
and we can't use many methods like the sum, min, max.

**Comment by andy-thomason** [comment]
I am debating whether to reinstate the AltVecImpl trait which matched with the methods.
I merged this into AltrepImpl for simplicity.

At present, only vector Altrep types are supported, but It would be great to have Closures,
Lists and Environments, for example.

**Comment by clauswilke** [comment]
> This will mean that direct dispatch to ALTREP methods will not be available
and we can't use many methods like the sum, min, max.

Just a reminder: I don't think the intent was to remove critical functionality. Maybe there's a different way to achieve the same goals, or maybe a point should be made to reinstate these functions? There was a request on r-devel for comments related to these changes.

**Comment by andy-thomason** [comment]
They are available via the interpreter `R!("sum(x)")`, but this is less than ideal method.

They should have Rf_variants to be useful.

```
Rf_sum(SEXP)
Rf_min(SEXP)
Rf_max(SEXP)
```
