### ISSUE TITLE
Compilation of "hello" example fails when using extendr from crates.io

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#28]
In the "hello" example package, if I use the `extendr` crate from crates.io by modifying my `Cargo.toml` file as follows:

    [dependencies]
    #extendr-api = {path = "../../../../extendr-api"}
    extendr-api = "0.1.3"

then compilation fails. rustc can't find the `extendr` attribute in this code fragment:

```Rust
#[extendr]
fn hello() -> &'static str {
    "hello"
}
```

Full compilation log is in the details.

<details>

```
==> R CMD INSTALL --no-multiarch --with-keep.source hello

rm -Rf hello.so ../target/release/libhello.a empty.o
* installing to library ‘/Users/clauswilke/Library/R/4.0/library’
* installing *source* package ‘hello’ ...
** using staged installation
** libs
/Library/Frameworks/R.framework/Resources/share/make/shlib.mk:6: warning: overriding commands for target `hello.so'
Makevars:9: warning: ignoring old commands for target `hello.so'
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c empty.c -o empty.o
echo BUILDING STATLIB
BUILDING STATLIB
cargo build --release --manifest-path=../Cargo.toml
    Updating crates.io index
   Compiling libc v0.2.80
   Compiling memchr v2.3.4
   Compiling proc-macro2 v1.0.24
   Compiling autocfg v1.0.1
   Compiling version_check v0.9.2
   Compiling cc v1.0.62
   Compiling glob v0.3.0
   Compiling unicode-xid v0.2.1
   Compiling log v0.4.11
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.2.1
   Compiling quick-error v1.2.3
   Compiling regex-syntax v0.6.21
   Compiling cfg-if v0.1.10
   Compiling unicode-width v0.1.8
   Compiling termcolor v1.1.0
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling bindgen v0.53.3
   Compiling vec_map v0.8.2
   Compiling shlex v0.1.1
   Compiling rustc-hash v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling lazycell v1.3.0
   Compiling syn v1.0.48
   Compiling rawpointer v0.2.1
   Compiling ndarray v0.13.1
   Compiling extendr-api v0.1.3
   Compiling thread_local v1.0.1
   Compiling humantime v1.3.0
   Compiling textwrap v0.11.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling num-complex v0.2.4
   Compiling nom v5.1.2
   Compiling matrixmultiply v0.2.3
   Compiling clang-sys v0.29.3
   Compiling aho-corasick v0.7.15
   Compiling atty v0.2.14
   Compiling which v3.1.1
   Compiling clap v2.33.3
   Compiling quote v1.0.7
   Compiling regex v1.4.2
   Compiling env_logger v0.7.1
   Compiling cexpr v0.4.0
   Compiling libloading v0.5.2
   Compiling extendr-macros v0.1.2
   Compiling libR-sys v0.1.9 (/Users/clauswilke/github/libR-sys)
   Compiling hello v0.1.0 (/Users/clauswilke/github/extendr/extendr-api/examples/R/hello)
error: cannot find attribute `extendr` in this scope
 --> src/lib.rs:3:3
  |
3 | #[extendr]
  |   ^^^^^^^

warning: unused import: `extendr_api::*`
 --> src/lib.rs:1:5
  |
1 | use extendr_api::*;
  |     ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted

error: could not compile `hello`.

To learn more, run the command again with --verbose.
make: *** [../target/release/libhello.a] Error 101
ERROR: compilation failed for package ‘hello’
* removing ‘/Users/clauswilke/Library/R/4.0/library/hello’
* restoring previous ‘/Users/clauswilke/Library/R/4.0/library/hello’

Exited with status 1.
```

</details>

By comparison, if I use the local source for the crate, as it is set up in the github repo, then compilation completes without issues. (There's a problem with the package function, though, but that's a different issue: #29)

<details>

```
==> R CMD INSTALL --no-multiarch --with-keep.source hello

* installing to library ‘/Users/clauswilke/Library/R/4.0/library’
* installing *source* package ‘hello’ ...
** using staged installation
** libs
rm -Rf hello.so ../target/release/libhello.a empty.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c empty.c -o empty.o
/Library/Frameworks/R.framework/Resources/share/make/shlib.mk:6: warning: overriding commands for target `hello.so'
Makevars:9: warning: ignoring old commands for target `hello.so'
echo BUILDING STATLIB
BUILDING STATLIB
cargo build --release --manifest-path=../Cargo.toml
    Updating crates.io index
   Compiling libc v0.2.80
   Compiling memchr v2.3.4
   Compiling proc-macro2 v1.0.24
   Compiling autocfg v1.0.1
   Compiling cc v1.0.62
   Compiling version_check v0.9.2
   Compiling unicode-xid v0.2.1
   Compiling glob v0.3.0
   Compiling lazy_static v1.4.0
   Compiling log v0.4.11
   Compiling bitflags v1.2.1
   Compiling regex-syntax v0.6.21
   Compiling cfg-if v0.1.10
   Compiling quick-error v1.2.3
   Compiling unicode-width v0.1.8
   Compiling termcolor v1.1.0
   Compiling strsim v0.8.0
   Compiling bindgen v0.53.3
   Compiling vec_map v0.8.2
   Compiling ansi_term v0.11.0
   Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
   Compiling shlex v0.1.1
   Compiling peeking_take_while v0.1.2
   Compiling syn v1.0.48
   Compiling ndarray v0.13.1
   Compiling rawpointer v0.2.1
   Compiling extendr-api v0.1.3 (/Users/clauswilke/github/extendr/extendr-api)
   Compiling thread_local v1.0.1
   Compiling humantime v1.3.0
   Compiling textwrap v0.11.0
   Compiling num-traits v0.2.14
   Compiling num-complex v0.2.4
   Compiling num-integer v0.1.44
   Compiling nom v5.1.2
   Compiling clang-sys v0.29.3
   Compiling matrixmultiply v0.2.3
   Compiling aho-corasick v0.7.15
   Compiling atty v0.2.14
   Compiling which v3.1.1
   Compiling quote v1.0.7
   Compiling clap v2.33.3
   Compiling regex v1.4.2
   Compiling cexpr v0.4.0
   Compiling env_logger v0.7.1
   Compiling libloading v0.5.2
   Compiling extendr-macros v0.1.2 (/Users/clauswilke/github/extendr/extendr-macros)
   Compiling libR-sys v0.1.9 (/Users/clauswilke/github/libR-sys)
   Compiling hello v0.1.0 (/Users/clauswilke/github/extendr/extendr-api/examples/R/hello)
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o hello.so empty.o -L../target/release -lhello -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
    Finished release [optimized] target(s) in 1m 12s
installing to /Users/clauswilke/Library/R/4.0/library/00LOCK-hello/00new/hello/libs
** R
** byte-compile and prepare package for lazy loading
No man pages found in package  ‘hello’ 
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (hello)
```

</details>

**Comment by clauswilke** [comment]
I've figured out what the problem is. The code of `extendr_macros` on crates.io doesn't match the code in the git repo. To show this, I've copied the entire `lib.rs` file from crates.io below, in the details. You can see that it defines a macro `export_function` but no macro `extendr`. I also note that the version of `extendr_macros` on crates.io (and in the github repo) is listed as 0.1.2, when the version of `extendr_api` is 0.1.3. Maybe all that is needed to fix this is to update the version of `extendr_macros` and re-publish on crates.io?

<details>
extern crate proc_macro;
use proc_macro::TokenStream;
use syn::{parse_macro_input, parse_quote, ItemFn, FnArg, Expr};
use syn::punctuated::Punctuated;
//use syn::parse::Parse;
use syn::Token;
use quote::{quote, format_ident};

//type CompileError = Box<dyn std::error::Error>;

// All arguments are SEXP for .Call in R.
fn translate_formal(input : &FnArg) -> FnArg {
    match input {
        FnArg::Typed(ref pattype) => {
            let pat = &pattype.pat.as_ref();
            return parse_quote!{ #pat : extendr_api::SEXP };
        },
        _ => ()
    }
    panic!("Exported function argument must be a primitive or Robj.");
}

// Convert SEXP arguments into native types if we can.
fn translate_actual(input : &FnArg) -> Expr {
    match input {
        FnArg::Typed(ref pattype) => {
            let pat = &pattype.pat.as_ref();
            let ty = &pattype.ty.as_ref();
            return parse_quote!{ extendr_api::unwrap_or_throw(from_robj::<#ty>(&new_borrowed(#pat))) };
        },
        _ => ()
    }
    panic!("Exported function argument must be a primitive or Robj.");
}

#[proc_macro_attribute]
/// Generate bindings for a single function.
pub fn export_function(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let func = parse_macro_input!(item as ItemFn);
    let func_name = &func.sig.ident;
    let wrap_name = format_ident!("__wrap__{}", func_name);

    let formal_args : Punctuated<FnArg, Token![,]> = func.sig.inputs.iter()
        .map(|input| {
            translate_formal(input)
        }).collect();

    let actual_args : Punctuated<Expr, Token![,]> = func.sig.inputs.iter()
        .map(|input| {
            translate_actual(input)
        }).collect();

        //println!("export_function func: {:#?}", func);

    let expanded = quote! {
        // #[allow(dead_code)]
        #func

        #[no_mangle]
        pub extern "C" fn #wrap_name(#formal_args) -> extendr_api::SEXP {
            use extendr_api::{from_robj, new_borrowed};
            unsafe {
                extendr_api::Robj::from(#func_name(#actual_args)).get()
            }
        }
    };
    
    //println!("res: {}", expanded);
    TokenStream::from(expanded)
}

</details>

**Comment by clauswilke** [comment]
Thinking about the right order of doing things, so we end up with fully functioning crates on crates.io: Maybe first merge the libR-sys PR (https://github.com/extendr/libR-sys/pull/7), which will increase the version of libR-sys. Then publish that on crates.io. Then increase the version dependency in extendr, and then increase extendr-{api, macros} versions to 0.1.4.

**Comment by andy-thomason** [comment]
Thanks for your hard work, @clauswilke  and others.

**Comment by andy-thomason** [comment]
I've updated some of the documentation and switched the docs to docs.rs.

Please let me know if this work for everyone.

A CI test on Appveyor or Azure would be a useful thing to keep this working.

**Comment by clauswilke** [comment]
Sounds good to me.

**Comment by clauswilke** [comment]
Just to be sure it doesn't fall through the cracks: extendr-macros needs a version bump also, here:
https://github.com/extendr/extendr/blob/8114138f483c8f31de3f3524826d147a11e0ae1e/extendr-macros/Cargo.toml#L3
and here:
https://github.com/extendr/extendr/blob/8114138f483c8f31de3f3524826d147a11e0ae1e/extendr-api/Cargo.toml#L13

**Comment by andy-thomason** [comment]
I've created a PR for this and will publish the crate.

**Comment by clauswilke** [comment]
I believe this is fixed now.
