### ISSUE TITLE
Implement "Doubles" wrapper

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#280]
Given the work on "Integers" in #274 I would like one of our contributors to make a PR
for the "Doubles" equivalent.

@Ilia-Kosenkov might be a good fit!

What do you think?

**Comment by Ilia-Kosenkov** [comment]
Sure, I can do that within a day or two.

**Comment by andy-thomason** [comment]
Excellent.

I'm very keen to avoid monopolising the development...

We should merge the Integers work.

Any comments would be welcome.
