### ISSUE TITLE
Proposal: Introduce `paste` dependency in `extendr-api`

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#283]
### Description
[`paste`](https://crates.io/crates/paste) is a very simple yet useful tool for advanced macros creation.
While I do not claim to be an expert on Rust and especially on macros, it seems the standard `macro_rules!` lacks certain features, while `proc_macro` is too over-engineered for the majority of cases.
`paste` allows simple manipulation with the tokens, including *concatenation* of identities using `paste!` macros and special syntax of `[< ... >]`.
### Justification
In `extendr`, when working with, e.g., `R` vectors, a lot of functions and types are named using the underlying `SEXP` type name. `R` functions have typical prefixes/suffixes of the form `REAL`, `INT`, etc. With the help of `paste`, all of these cases can be covered by providing one argument to `extendr` macros, which is then used to generate function names (like `as_real_slice`, `as_int_slice`). `paste` allows for limited control of capitalization, so it has potential to simplify already existing macros, like these ones (`Add` and `add` can be represented by a single parameter):
https://github.com/extendr/extendr/blob/7e9cac34187d333abd83b79b0e13887249fb7d42/extendr-api/src/scalar/rint.rs#L178-L184

If `paste` allows us to construct function and type names on the fly, we can work with vector types and their counterparts entirely through macros, duplicating **no** code.

As mentioned above, `paste` is much easier than `proc_macro`, and can be easily integrated into existing `macro_rules!` macros.

`paste` has no external dependencies (as far as I can tell, see its [`Cargo.toml`](https://github.com/dtolnay/paste/blob/master/Cargo.toml)), so it should not bloat `extendr` dependency tree.

### Drawbacks
**+1** dependency

**Comment by yutannihilation** [comment]
This sounds good to me.

One more possible drawback of relying macro heavily is build time. I bet 99% this won't make the build massively slow, because the amount of code in extendr is modest. So, we can forget this, but let me leave this comment just in case we found some problem related to the build time.

c.f. "Compilation Model: Macros And Pipelining" section of https://matklad.github.io/2021/09/04/fast-rust-builds.html

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation, yeah, I perfectly understand. But I am not sure we can avoid macros usage. We need to emit a certain amount of boilerplate code, and we either write it ourselves or use macros to generate it. I believe while we use `macro_rules!` we slight modifications, it is still reasonable. And it definitely saves us time and effort and reduces copy-paste mistakes.

In #284 I do use `paste` at later stages to simplify some code, and almost all of the implementations of `Rfloat`, `Rint`, `Integers`, `Doubles` are generated using a fixed set of macros with no code repetition. I predict we can (with small modifications) expand these macros to other basic types (providing `R` API does not break its naming conventions).

**Comment by clauswilke** [comment]
Yeah, let's avoid premature optimization. If macros make the code substantially simpler and easier to read then they're worth it. If at some point in the future we run into performance issues we can think about it then.

**Comment by andy-thomason** [comment]
We should be able to swap in `concat_ident!` at some point in the future.

**Comment by Ilia-Kosenkov** [comment]
Implemented in #284
