### ISSUE TITLE
Add support for `+=` family of operators to scalar types

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#285]
Currently, we only provide binary infix operators like `*` `+` `-`  `/`:
https://github.com/extendr/extendr/blob/7e9cac34187d333abd83b79b0e13887249fb7d42/extendr-api/src/scalar/rint.rs#L3
Their counterparts have to be implemented separately, e.g. using `std::ops::AddAssign` trait.

I propose for each `Rtype` implement traits for at least (`Rtype`, `type`) pairs, which will allow (if I am not mistaken) code like this:
```rust
let mut x : Rint = Rint(42);
x += 1;
```

Should be easy after #284 improves macros used for generating operators.

**Comment by multimeric** [comment]
Closed via #291.
