### ISSUE TITLE
Extend support for `NA`

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#286]
We have `IsNA` trait that allows checking if the object is `NA`.
A useful extension would be to provide `pub fn na() -> Self`.
If `Self` is acceptable as a return type (it is a valid `Rust` code, but I wonder if it is good from design perspective), then something like the following will work
[Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=pub%20trait%20IsNA%20%7B%0A%20%20%20%20fn%20is_na(%26self)%20-%3E%20bool%3B%0A%20%20%20%20fn%20na()%20-%3E%20Self%3B%0A%7D%0A%0Astruct%20Rint(i32)%3B%0Astruct%20Rfloat(f64)%3B%0A%0Aimpl%20IsNA%20for%20Rint%20%7B%0A%20%20%20%20fn%20is_na(%26self)%20-%3E%20bool%20%7B%0A%20%20%20%20%20%20%20%20self.0%20%3D%3D%20i32%3A%3AMIN%0A%20%20%20%20%7D%0A%20%20%20%20fn%20na()%20-%3E%20Self%20%7B%0A%20%20%20%20%20%20%20%20Rint(i32%3A%3AMIN)%0A%20%20%20%20%7D%0A%7D%0A%0Aimpl%20IsNA%20for%20Rfloat%20%7B%0A%20%20%20%20fn%20is_na(%26self)%20-%3E%20bool%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20Arbitrary%20value%0A%20%20%20%20%20%20%20%20self.0%20%3D%3D%20100500f64%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20fn%20na()%20-%3E%20Self%20%7B%0A%20%20%20%20%20%20%20%20Rfloat(100500f64)%0A%20%20%20%20%7D%0A%7D%0A%0A%0Afn%20main()%20%7B%0A%20%20%20%20assert!(Rfloat%3A%3Ana().is_na())%3B%0A%20%20%20%20assert!((%3CRint%20as%20IsNA%3E%3A%3Ana()).is_na())%3B%0A%7D%0A%0A)

```rust
assert!(((Rint as IsNA)::na()).is_na());
```

So, the trait should look like this
```rust
pub trait IsNA {
    fn is_na(&self) -> bool;
    fn na() -> Self;
}
```

Potential blockers: it is unclear to me what types implement `IsNA` right now. We need to make sure we can reliably construct `NA` for each type that implements this trait.

Potential benefits:
With the implementation of `IsNA::na()` and `default::Default::defaut()` we will be able to operate on both default values and `NA`s in a type-agnostic way.

**Comment by clauswilke** [comment]
This sounds great to me, but wouldn't the trait maybe be better named `NA` or `HasNA`? I read it as a trait that provides an `NA` implementation and a check for that implementation.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke, I did not address the naming here, feel free to chose any name. 

We can have a separate trait for just creating `NA`, but I do not fully understand Rust trait inheritance, so not sure if it will work as expected.

So we can add it to the existing one and probably rename it as you have suggested.

**Comment by clauswilke** [comment]
I have to admit that Rust traits are still somewhat unclear to me, so I wouldn't know what is the right course of action. Maybe @andy-thomason could weigh in.

**Comment by andy-thomason** [comment]
We have a number of NA related traits for R objects:

* Is the object a singleton NA (ie. NA_REAL or some such) is_na()
* Does the object contain any NA values? has_nas().
* What is the correct NA for this type? na()

Having a trait for NA-related issues seems like a good idea and IsNa is maybe not the correct name.

I am pretty happy with this.
