### ISSUE TITLE
Should we participate in hacktoberfest?

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#292]
Following a request to grant `hacktoberfest-accepted` label by the author of this PR https://github.com/extendr/extendr/pull/291#issuecomment-933883650 , I triggered a short discussion on the Discord.

There are both positive and negative sides of the hacktoberfest event:
1. It allows to get some extra publicity and draw in new contributors
2. New developers can help sort out simple issues and speed up API polishing, leaving more time for maintainers to dive deep into the architectural problems
3. Because of its competitive nature, hacktoberfest may increase the number of garbage PRs -- little to no meaningful changes for the sake of getting a label and boosting developer's stats
4. Even though the rules are improved this year, hacktoberfest can put additional pressure onto the team through the garbage Issue/PR traffic

A short summary of rules:
1. ❌ To participate, we can mark issues with `hacktoberfest`, which is similar to `good first issue`, `up for grabs`, etc. This declares our explicit intention to be part of the event. *Rejected because there is not enough time to manage activities related to the event, and extra traffic generated by PRs.*
2. ✔ We can mark some PRs as `hackroberfest-accepted` whether we participate explicitly or not. The rules do not forbid this, and this is what happened with #291. *Accepted on per PR basis.*

@yutannihilation expressed one point of view in the Discord, so I invite everyone interested in the topic to discussion.

**Comment by yutannihilation** [comment]
Thanks for summarizing! To be clear, I think I have no right to comment on this issue, as nowadays I don't have much time for reviewing the pull requests on this repo (sorry for this). Joining Hacktoberfest probably means, to some extent, we are promising to review the related pull requests before the end of the Hacktoberfest to let the contributors get the rewards. But, I'm afraid I won't be able to help much on this. Joining Hacktoberfest itself should be a good thing, though.

**Comment by clauswilke** [comment]
No strong opinion either way, other than I also don't have a lot of additional free capacity and wouldn't want to promise to review any particular PR.

**Comment by yutannihilation** [comment]
Sorry I couldn't support this this time. Hope we can do better next year...!
