### ISSUE TITLE
Complexs

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#294]
Are we happy with this name?

Use num_complex on a feature switch to implement this.
```
struct Rcomplex {
   inner: num_complex::Complex
}

impl Deref for Rcomplex {
   fn deref(&self) -> num_complex::Complex {
      self.inner
   }
}
```

**Comment by clauswilke** [comment]
Yes, it's good. See also:
https://github.com/extendr/extendr/blob/master/design_specifications/marshaling_rules.md#rust-counterparts

**Comment by Ilia-Kosenkov** [comment]
https://github.com/extendr/libR-sys/blob/c184e9de8683fa36bef03a2f95bce4ed91ebe769/bindings/bindings-linux-x86_64-R4.1.rs#L2778-L2783

**Comment by andy-thomason** [comment]
`num_complex::Complex<f64>` should map to the R complex datatype.

A vector cast to this type should behave as expected.
