### ISSUE TITLE
cargo test fails extendr-api

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#31]
When trying to run `cargo test` for `extendr-api`, I get a segfault. Is this OS X specific or does the same problem show up on other platforms? I note that the "hello" example builds and runs fine.

```
clauswilke ~/github/extendr/extendr-api> cargo test
   Compiling extendr-api v0.1.4 (/Users/clauswilke/github/extendr/extendr-api)
    Finished test [unoptimized + debuginfo] target(s) in 1.76s
     Running /Users/clauswilke/github/extendr/target/debug/deps/extendr_api-6486cbe7629caf2f

running 7 tests
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/clauswilke/github/extendr/target/debug/deps/extendr_api-6486cbe7629caf2f` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by clauswilke** [comment]
Well, it seems to succeed on Travis: https://travis-ci.org/github/extendr/extendr/builds/744744955
So maybe OS X specific.

@CGMossa Does it work for you on Windows?

**Comment by lebensterben** [comment]
can you try:

[profile.test]
codegen-units=1

**Comment by clauswilke** [comment]
@lebensterben Makes no difference.

**Comment by lebensterben** [comment]
Same here:
```
extendr/extendr-api ::  master is  v0.1.4 via  v1.50.0-nightly ~ 13s 
𝛌 cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running /tmp/extendr/target/debug/deps/extendr_api-8a21d25a9c80c630
/tmp/extendr/target/debug/deps/extendr_api-8a21d25a9c80c630: error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory
error: test failed, to rerun pass '--lib'
```

**Comment by lebensterben** [comment]
After fixing the libR.so missing problem, I get the same SIGSEGV error:
```
cargo test        
    Finished test [unoptimized + debuginfo] target(s) in 0.04s
     Running /tmp/extendr/target/debug/deps/extendr_api-8a21d25a9c80c630

running 7 tests
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/tmp/extendr/target/debug/deps/extendr_api-8a21d25a9c80c630` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by clauswilke** [comment]
The crash happens in this line:
https://github.com/extendr/extendr/blob/8114138f483c8f31de3f3524826d147a11e0ae1e/extendr-api/src/robj.rs#L1273

I'll see if I can figure out how the code gets there.

**Comment by lebensterben** [comment]
So it panics when calling `R_PreserveObject`.
Also a very interesting finding:
```
thread 'args::tests::test_args' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', extendr-api/src/args.rs:116:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which comes from the line
```
assert_eq!(lang!("+", x = 1, y = 1).eval().unwrap(), Robj::from(2));
```

Keep running the tests again and again, I see more interesting errors:
```
Error: SET_VECTOR_ELT() can only be applied to a 'list', not a 'NULL'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Fatal error: unable to initialize the JIT

thread 'args::tests::test_args' panicked at 'called `Result::unwrap()` on an `Err` value: "R eval error"', extendr-api/src/args.rs:116:44
```

Well, the memory management seems to be buggy.

**Comment by clauswilke** [comment]
@lebensterben Are you on OS X also? It's curious that things work just fine on Linux. I wonder whether it's bugs in the code or a problem with the toolchain. I believe we're using a different LLVM to generate the bindings and to compile the code. Maybe there's an incompatibility?

**Comment by lebensterben** [comment]
>@lebensterben Are you on OS X also? It's curious that things work just fine on Linux. I wonder whether it's bugs in the code or a problem with the toolchain. I believe we're using a different LLVM to generate the bindings and to compile the code. Maybe there's an incompatibility?

@clauswilke Linux

**Comment by clauswilke** [comment]
Ok. For sure calling R from multiple threads is not safe and should not be done. We may have to enforce single-threaded use throughout. Where in the CI test is single threading enforced? I'm still somewhat new to Rust and don't know all the ins and outs.

**Comment by clauswilke** [comment]
Ah, I see: `cargo test -- --nocapture --test-threads=1`. With this command the tests complete without issues.

**Comment by clauswilke** [comment]
Closing this issue as segfaults under multi-threaded use are expected. The only fix is to not run multiple threads all talking to R at the same time.

**Comment by lebensterben** [comment]
well I think this is a very serious issue.
- first this should be clearly documented.
- second, why this causes SIGSEGV is still not clear.

> a call to R_PreserveObject adds an object to an internal list of objects not to be collects, and a subsequent call to R_ReleaseObject removes it from that list. This provides a way for objects which are not returned as part of R objects to be protected across calls to compiled code: on the other hand it becomes the user’s responsibility to release them when they are no longer needed (and this often requires the use of a finalizer).

Unlike R_protect and R_unprotect where the order of protection and unprotection matters and is clearly documented, R_PreserveObject and R_ReleaseObject seems like agnostic for the order.

**Comment by clauswilke** [comment]
It is well documented, though (from [here](https://cran.r-project.org/doc/manuals/R-exts.html#OpenMP-support)):

> Calling any of the R API from threaded code is ‘for experts only’ and strongly discouraged. Many functions in the R API modify internal R data structures and might corrupt these data structures if called simultaneously from multiple threads.

You simply can't predict what's going to happen when you access the R API from multiple threads at the same time.

For related examples, see here: https://github.com/rdotnet/rdotnet/issues/7 or here: https://cran.r-project.org/web/packages/RcppThread/vignettes/RcppThread-vignette.pdf
