### ISSUE TITLE
Graphics API additions in R 4.2

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#315]
It seems there will be some more APIs.

https://github.com/extendr/libR-sys/pull/83/files#diff-5ef2ffb0c92c21a03a84b0789542aa2a69dd595c3566a897eb0bbf36664cb3ac

**Comment by andy-thomason** [comment]
Cool. These need to go in on a `cfg` switch as they are version dependent.

Any volunteers?

**Comment by yutannihilation** [comment]
Some more additions by https://github.com/extendr/libR-sys/pull/84

**Comment by yutannihilation** [comment]
I'll address in #366. Sorry for the duplication.
