### ISSUE TITLE
Dealing with input character vectors that may contain NAs

### ISSUE THREAD

**Issue by dhersz** [extendr/extendr#316]
Hi. First of all, thank you for the hard work you have been putting on these crates/packages.

I'm having a hard time creating a function that receives a (character) vector that might have some NAs as input. I read that the proper way of dealing with NAs is by using `Option<_>`, but I cannot assign this type to the function argument:

``` r
library(rextendr)

rust_function(
  "fn string_test(x: Vec<Option<String>>) -> Vec<Option<String>> {
    println!(\"{:?}\", x);
    x
  }"
)
#> ℹ build directory: '/tmp/RtmpebXMOj/file6e815618fd6c'
#> Error: Rust code could not be compiled successfully. Aborting.
```

The error message here is not that useful, but this is the compilation error I'm getting:

```
error[E0599]: no function or associated item named `from_robj` found for struct `Vec<Option<std::string::String>>` in the current scope
 --> src/lib.rs:2:1
  |
2 | #[extendr]
  | ^^^^^^^^^^ function or associated item not found in `Vec<Option<std::string::String>>`
  |
  = note: this error originates in the attribute macro `extendr` (in Nightly builds, run with -Z macro-backtrace for more info)
```

But `Vec<String>` cannot deal with NAs either, as the snippet below shows:

```r

rust_function(
  "fn another_string_test(x: Vec<String>) -> Vec<String> {
    x
  }"
)
#> ℹ build directory: '/tmp/RtmpebXMOj/file6e815618fd6c'
#> ✔ Writing '/tmp/RtmpebXMOj/file6e815618fd6c/target/extendr_wrappers.R'.

another_string_test(c("oi", NA))
#> Error in string_test(c("oi", NA)): Input vector cannot contain NA's.
```

What also confuses me a bit is that I can use `Vec<Option<String>>` at the output type of the function:

```r
rust_function(
  "fn yet_another() -> Vec<Option<String>> {
    vec![Some(\"oi\".to_string()), None]
  }"
)
#> ℹ build directory: '/tmp/RtmpPPNPuT/file7ac73ba53a43'
#> ✔ Writing '/tmp/RtmpPPNPuT/file7ac73ba53a43/target/extendr_wrappers.R'.

yet_another()
#> [1] "oi" NA
```

By the way, I'm sorry if this is already documented somewhere or discussed in another issue, but I couldn't properly fit it in existing discussions. https://github.com/extendr/extendr/issues/286 seems to deal with the design of the NA-related traits, and while https://github.com/extendr/extendr/issues/313 seems to suggest an implementation that could solve this issue, I feel like this post would diverge from that issue's main topic.

Cheers!

**Comment by andy-thomason** [comment]
If you have the latest version of extendr-api (from github) there are a number of new wrappers including
`Strings` which will accept an R `STRSXP` object.

The `Strings` object exposes a slice of `Rstr` objects which are wrappers around the `CHARSXP` R object.

Rstr supports the `CanBeNA` trait that lets you test the NA state of the strings.

You can return a Strings object and build one from string-like Rust objects and closures using collect.

**Comment by andy-thomason** [comment]
See the tests for some examples:

https://github.com/extendr/extendr/blob/master/extendr-api/tests/vector_tests.rs#L3-L36

**Comment by dhersz** [comment]
This is great @andy-thomason, thank you very much and sorry for overlooking this!

**Comment by andy-thomason** [comment]
No worries. Its all very new an lacks documentation!

Thanks for giving it a go.
