### ISSUE TITLE
AltrepImpl::get_region() returns NULL

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#326]
I created a repository to show the problem. While `get_region()` definitely works in the tests within extendr, it won't work when used in an R package.

https://github.com/yutannihilation/extendrAltintTest

``` r
# get the ALTREP integer vector of the sequence from 0 to 10
x <- get_intrange()

# works
x[3]
#> [1] 2

# won't work yet
x[2:3]
#> NULL
```

**Comment by yutannihilation** [comment]
@andy-thomason 
This is the problem I commented on https://github.com/extendr/extendr/issues/310#issuecomment-950250792. Do you have any idea about the cause?

**Comment by andy-thomason** [comment]
There is not default implementation at present. There is a function that does this generally in later R versions, but it
is version dependent. We could also do a much more altrep-aware version that fetches blocks with get_region()
and maps them to the destination as well as supporting other indexing schemes.

**Comment by yutannihilation** [comment]
> There is not default implementation at present.

Oh, I didn't know this, thanks...

**Comment by yutannihilation** [comment]
I think I now have a bit better understanding. What I should have implemented was `extract_subset()`. I still not sure how `get_region()` is used (for example, I couldn't find any usages of `INTEGER_GET_REGION()` in the code of base R), but this isn't the problem on our side. It's great if we can provide a better default implementation, but let's revisit it when necessary. This issue is probably too small to discuss at this stage.
