### ISSUE TITLE
Testing an `extendr_module` in Rust

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#329]
Let's say we have the same example from the readme, where we have:

```rust
// Macro to generate exports
extendr_module! {
    mod classes;
    impl Person;
    fn aux_func;
}
```

I want to then write tests for this in Rust, so I've added:

```rust
#[cfg(test)]
mod test {
    use super::*;

    #[rstest]
    fn test_person(){
    test! {
            R!("
                classes::new()
            ");
        }
    }
}
```
Which gives me:
```
Error in loadNamespace(x) : there is no package called ‘classes’
```

Just wondering how to do this?

**Comment by yutannihilation** [comment]
Let me confirm first, is `classes` an R package name and `new()` an R function? If so, I think you need to install the R package first, so probably it should be tested on R's side.

**Comment by multimeric** [comment]
This is a contrived example, but I'm imagining that the entire readme example is included in the same module:

```rust
use extendr_api::prelude::*;

struct Person {
    pub name: String,
}

#[extendr]
impl Person {
    fn new() -> Self {
        Self { name: "".to_string() }
    }

    fn set_name(&mut self, name: &str) {
        self.name = name.to_string();
    }

    fn name(&self) -> &str {
        self.name.as_str()
    }
}

#[extendr]
fn aux_func() {
}


// Macro to generate exports
extendr_module! {
    mod classes;
    impl Person;
    fn aux_func;
}
```

**Comment by multimeric** [comment]
How can I "install" the R package when everything I'm doing so far is within Rust?

**Comment by yutannihilation** [comment]
I meant you cannot install the R package within Rust. If you want to test R code, it should be done on R's side.

**Comment by multimeric** [comment]
Could we not create the package namespace using the R API?

**Comment by yutannihilation** [comment]
Sorry, I think I don't get your point... Even if you can create the namespace programmatically, if `new()` is an R function, you need the corresponding R code, which you probably generated by `rextendr::document()` on an R session. Again, I think you should write R test code within the R package.

If you meant to test the Rust code, I think you don't need `R!( )` (or `r!( )` might be what you want).

**Comment by multimeric** [comment]
Okay, I guess that extendr is really set up with the intention to actually generate the R package on the filesystem and then install it.

In theory I believe it should be possible to have some kind of macro that uses the machinery underlying `rextendr::document()` to create the R package in-memory and load it into the interpreter session created using `test! {}`, and then test it.

**Comment by yutannihilation** [comment]
Hmm, you might be right. In my opinion, if it's intended to be provided as an R package, it should be tested as an R package. extendr can mimic the R's behavior to some extent, but it might not be perfect and there's no guarantee that it works on a real R session. I'll wait for other maintainers' comments.

**Comment by multimeric** [comment]
No, you're probably right, and I'm just thinking about this in a rigid way. There's no particular reason I can't test this using R.

**Comment by clauswilke** [comment]
Yes, I agree with @yutannihilation. It doesn't make sense to test export to R outside of the context of an R package to which things are being exported.

**Comment by multimeric** [comment]
Fair enough.
