### ISSUE TITLE
`data.frame` wrappers and converters

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#330]
I had a quick look through the current repo, and it doesn't seem like we have an explicit handling for data frames. 

I quickly tested it using:
```rust
let df = R!("iris");
dbg!(df);
```
```rust
Ok(
    r!(List::from_pairs(
        Zip { 
            a: ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species"], 
            b: [r!([...]), r!([...]), r!([...]), r!([...]) r!([...])] 
        }
    )).set_class(["data.frame"]
)
```
So I guess we're treating it as an R list of vectors, which is pretty reasonable.

Two thoughts though:

* Firstly, I'm wondering if we could use the guaranteed properties of a data frame to simplify this conversion. For example, names are guaranteed to be unique, so we could losslessly convert to a hashmap
* Secondly, I've been happily using Polars as my Rust data frame library. I'm wondering if there is interest in a feature-gated conversion between Polars and R data frames, in the same way we are doing for `ndarray`

**Comment by clauswilke** [comment]
I don't exactly understand what the specific request/suggestion is. Could you be more specific? What exactly is the feature that is missing? And if there is more than one, maybe open a separate issue for each?

**Comment by multimeric** [comment]
I'm really not sure how to make this clearer:

* Can we make the default R type for a data frame be a hash map?
* Can I write a wrapper class that converts an R `data.frame` into a Polars `DataFrame`?

**Comment by clauswilke** [comment]
> Can we make the default R type for a data frame be a hash map?

Do you mean Rust type? And wouldn't it make more sense to write an abstract wrapper and then leave how the wrapper stores the data as an implementation detail?

> Can I write a wrapper class that converts an R `data.frame` into a Polars `DataFrame`?

Sure, but note that this entirely separate from your point one and thus deserves a second issue.

**Comment by multimeric** [comment]
> Do you mean Rust type? And wouldn't it make more sense to write an abstract wrapper and then leave how the wrapper stores the data as an implementation detail?

Yes I meant Rust. Maybe you're right, but I vaguely remember there being discussion about how users have to manually convert to hash map because it's normally a lossy conversion.

> Sure, but note that this entirely separate from your point one and thus deserves a second issue.

Okay, I'll create a new issue.

**Comment by multimeric** [comment]
In retrospect this is probably such a niche request that's satisfied well enough either by the existing `List` conversion or by #331.
