### ISSUE TITLE
Customizing method names in Rust and R

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#332]
I have a struct with a certain constructor function. Say:

```rust
struct Foo<T> {
    bar: T
}

impl<T> Foo<T> {
    fn new(data: T) -> Self {
        Foo { bar: data }
    }
}
```

Now, I can't `extendr` this `impl` block because it's generic, so I make an R-specific version *as well*:

```rust
use extendr_api::prelude::*;
#[extendr]
impl Foo<f64> {
    fn new(data: f64) -> Self {
        Foo { bar: data }
    }
}
```

The compiler then gives me:
```
duplicate definitions for `new`
```

However, I do actually want the Rust and R APIs to have the same function/method names, for consistency. Is it possible to either:
* Mangle the name of the `extendr`-ized function in Rust, such that the macro outputs `fn __extendr_new` or something in Rust but keeps the `new()` function name in R, or
* Manually let me mangle the name in Rust to prevent duplication, but then specify the R function name, so: 
    ```rust
    #[extendr(r_name = "new")]
    fn r_new(data: f64) -> Self {}
    ```

**Comment by Ilia-Kosenkov** [comment]
I see two issues here:

**Comment by multimeric** [comment]
> First, why there are two new definitions? It is unclear to me.

There's a difference between my first two blocks of Rust code. In the first block, we have a generic type `T`, which I want for my Rust API, but extendr does not support (it will throw a compiler error). As a consequence, I *must* define a second constructor which has a fixed type, in order for extendr to work. I suppose this could be fixed by allowing an extendr option that fixes the type e.g. `#[extendr(T = f64)]`, but this would be very complex and I can't see it happening any time soon.

**Comment by multimeric** [comment]
In the short term I have worked around this issue by using the above code, and then in R creating an R function `new()` which wraps the auto-generated rextendr R function `r_new()`, but this isn't exactly ideal.

**Comment by andy-thomason** [comment]
To make this work, we need to add options to `extendr_function` here:

https://github.com/extendr/extendr/blob/master/extendr-macros/src/extendr_function.rs#L25-L43

Currently the function name comes from here:

https://github.com/extendr/extendr/blob/master/extendr-macros/src/wrappers.rs#L21

But could come from an `Option<String>` in `Opts`.

**Comment by andy-thomason** [comment]
I think we need this...

**Comment by andy-thomason** [comment]
Shall I assign it to you, @Ilia-Kosenkov or I can do this myself.

**Comment by Ilia-Kosenkov** [comment]
Not me, I failed Logicals and still owe Complexes implementation. I am happy to consult and help with testing though.

**Comment by andy-thomason** [comment]
> Not me, I failed Logicals and still owe Complexes implementation. I am happy to consult and help with testing though.

Don't underestimate your abilities! Your contributions have been very welcome.

I'll pop in there and raise a PR if you will help me to review.

**Comment by andy-thomason** [comment]
I've implemented this version

```rust
#[extendr(r_name = "new")]
fn r_new(data: f64) -> f64 {}
```

In a new PR.

This also allows us to use "." in R names.

```rust
#[extendr(r_name = "my.groovy.function")]
fn my_groovy_function(data: f64) -> f64 {}
```
We haven't yet figured out how to `impl` traits and generic functions/methods
and so the only work-around is to write a wrapper function as described.

We could look as a mechanism for polymorphic wrapper generation so that a
single R function calls one of many Rust functions depending on type.
