### ISSUE TITLE
Derive a conversion trait from Rust struct to R list

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#333]
So the existing way that `extendr` handles Rust structs seems to be by creating an `env` with a pointer to the struct, and then providing wrapper functions for the methods in the annotated `impl` block. This is a great baseline behaviour, but sometimes I want a different behaviour from my structs; to convert them recursively into an R data structure. For instance, if my function has a complicated result struct, rather than forcing my users to call getter functions, I would rather just convert the whole result struct into some native R types.

For this reason I'm wondering if we should create a `derive` attribute, such that we can:

```rust
#[derive(extendr_list)]
struct Foo {
    a: str
    b: usize
}
```

Which would expand to:

```rust
impl TryFrom<Foo> for Robj {
    fn try_from(value: Foo) -> Result<Robj, Error> {
            let mut ret = List::new(2);
            ret.set_elt(0, value.a.into())?;
            ret.set_elt(1, value.b.into())?;
            ret.as_robj_mut().set_names(["a", "b"])?.as_list()?
    } 
}
```
(there might be a more idiomatic way to create a named list but I don't know it)

**Comment by andy-thomason** [comment]
I am busy implementing serde::Serializer for Robj.

This should allow you to use any serde derived type to generate R objects as well as
to convert them to JSON etc.

Serialize is not ideal as it doesn't deal with vectors very efficiently. So a more specific
object converter would be a good idea. There was some discussion of derive(TryFrom)
in the Rust community.

The code above can be done very simply with the new list! macro.
```
list!(a=value.a, b=value.b)
```

**Comment by multimeric** [comment]
Yes, I found out about that great macro recently. Is there any merit in me adding a derive macro that implements `TryFrom<T> for Robj` for any struct using that macro?

**Comment by andy-thomason** [comment]
Absolutely!

I can give some help if you like.

It needs to go in `extendr_macros` where we have entrypoints for macros already.

**Comment by andy-thomason** [comment]
It may be a little more stable than the components that it references.

**Comment by multimeric** [comment]
What does that mean?

**Comment by andy-thomason** [comment]
Macros are dependent on the API matching them. If the API changes, we
need to update the macros.

Don't worry, though just give it a try.
