### ISSUE TITLE
Make use_try_from the default.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#336]
```rust
#[extendr(use_try_from = true)]
fn test_rint(val: Rint) -> Rint {
    val
}
```

Should just be 

```rust
#[extendr]
fn test_rint(val: Rint) -> Rint {
    val
}
```

**Comment by multimeric** [comment]
Note: this issue means replacing *all* instances of the `FromRobj` trait with `TryFrom`: https://github.com/extendr/extendr/blob/f27bda063040e0302747bece860c094c623a03be/extendr-macros/src/wrappers.rs#L300-L307
