### ISSUE TITLE
`impl TryFrom<&Robj>` for all types and allow &Robj etc. as inputs.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#337]
In addition to `TryFrom<Robj>` we should also impl `TryFrom<&Robj>` for all types.

In the case:

```rust
fn polymorphic_int(v: Rint) {

}

fn polymorphic_float(v: Rfloat) {

}


fn polymorphic(val: Robj) {
    if let Ok(v) = Rint::try_from(val.clone()) {
        polymorphic_int(v);
    } else if let Ok(v) = Rfloat::try_from(val) {
        polymorphic_float(v);
    }
}
```

It would be nice to drop the clone and use &Robj for the input.

**Comment by multimeric** [comment]
I think we could write an attribute macro for doing this, whereby we implement the trait on the reference type and it automatically creates a copy of that conversion trait for the owned type.

**Comment by CGMossa** [comment]
Internally, this has been done throughout. There might be missing impls here or there, but these were largely adressed. Closing this issue for now. 

A potential follow-up issue is maybe providing downstream users with such a macro.
