### ISSUE TITLE
Was something changed on Windows setup after Rust 1.57.0?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#339]
@Ilia-Kosenkov 
Sorry to bother you, recently I got a new Windows machine and set up the Rust and Rtools, but I got this error on trying to compile an R package using extendr. As our CI keep passing, I think the problem is on my setup, but I'm curious what's wrong.

Though I don't understand anything about the error, as it says "BCryptGenRandom", I suspect this commit https://github.com/rust-lang/rust/commit/1ed123828c97d9f7e031a9caee02e340295ef21e  introduced in Rust 1.57 might affect. Have you ever seen this error? Do you use Rust 1.57? 

```
==> Rcmd.exe INSTALL --no-multiarch --with-keep.source foo

* installing to library 'C:/Users/Yutani/Documents/R/win-library/4.1'
* installing *source* package 'foo' ...
** using staged installation
** libs
rm -Rf foo.dll ./rust/target/x86_64-pc-windows-gnu/release/libfoo.a entrypoint.o
/mingw64/bin/gcc  -I"C:/PROGRA~1/R/R-41~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c entrypoint.c -o entrypoint.o
cargo +stable-msvc build --target=x86_64-pc-windows-gnu --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target
    Finished release [optimized] target(s) in 0.58s
/mingw64/bin/gcc -shared -s -static-libgcc -o foo.dll tmp.def entrypoint.o -L./rust/target/x86_64-pc-windows-gnu/release -lfoo -lws2_32 -ladvapi32 -luserenv -LC:/PROGRA~1/R/R-41~1.2/bin/x64 -lR
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./rust/target/x86_64-pc-windows-gnu/release/libfoo.a(std-57e8ea4e1cfb36e3.std.0253c85e-cgu.0.rcgu.o): in function `std::sys::windows::rand::hashmap_random_keys':
/rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\sys\windows/rand.rs:10: undefined reference to `BCryptGenRandom'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\sys\windows/rand.rs:10: undefined reference to `BCryptGenRandom'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'foo'
* removing 'C:/Users/Yutani/Documents/R/win-library/4.1/foo'

Exited with status 1.
```

**Comment by Ilia-Kosenkov** [comment]
Hi, yes, I saw that. For some reason some of my projects now require, I think -lbcrypt or something like that. I am away from my PC right now, so if you gogle the issue with BCryptGenRandom, you will get an answer. I think it may be required if you invoke rng from Rust.

**Comment by yutannihilation** [comment]
Oh, thanks! Actually, adding `-lbcrypt` solved the error. So, should we include `-lbcrypt` in the default `Makevars.win` generated by rextendr? I was seeing this error with a bare package, which is made only by `usethis::create_package()` + `rextendr::use_extendr()`. I didn't intend to use rng.

**Comment by Ilia-Kosenkov** [comment]
I don't know honestly. It may trigger some warnings if we link unused library, or lead to compilation error like in your case. I will research it

**Comment by yutannihilation** [comment]
It seems this is now reproducible on our CI, so I guess `-lbcrypt` is needed if the user uses Rust >1.57.

https://github.com/yutannihilation/rextendr/runs/4495809508?check_suite_focus=true#step:11:218

> It may trigger some warnings if we link unused library, or lead to compilation error like in your case.

So, maybe we need to dynamically determine whether or not to include it, depending on the Rust version installed...? Anyway, I'd like to wait for your confirmation (no hurry at all!).

**Comment by Ilia-Kosenkov** [comment]
Actually, here is an answer why it is using random (likely). I did notice it in the original message:
````std::sys::windows::rand::hashmap_random_keys```

**Comment by yutannihilation** [comment]
Ah, I see. So, `-lbcrypt` is now required as long as we use std, which means every time, right?

**Comment by Ilia-Kosenkov** [comment]
Not std, my guess is anything that uses rand, like hashmap.

**Comment by yutannihilation** [comment]
Yeah, I meant, `Hashmap` is in `std::collection`, and I thought, even if we would eliminate the use of it, choosing staticlib means the built result contains all the dependencies including std. I'm not familiar with the details about how the dependencies are resolved, so sorry if I'm wrong here.

Anyway, extendr uses `HashMap` at least at the moment.

**Comment by Ilia-Kosenkov** [comment]
I think we will have to include `lbcrypt` anyway, but it seems that the linking issue arises only if we invoke methods that actually reference `rand`. Perhaps you can make a PR in `{rextendr}`?

**Comment by yutannihilation** [comment]
Sorry, it seems this link to the commit in question was broken. Fixed now.

> I suspect this commit [rust-lang/rust@1ed1238](https://github.com/rust-lang/rust/commit/1ed123828c97d9f7e031a9caee02e340295ef21e) introduced in Rust 1.57

The followings might be also useful to see the details:

* https://github.com/rust-lang/rust/pull/84096
* https://github.com/rust-random/getrandom/issues/65#issuecomment-753634074
