### ISSUE TITLE
Create S4 (or maybe S3) wrapper classes

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#340]
Something I've noticed with the current class wrapping behaviour it that it doesn't produce particularly idomatic R code. For instance if we have:

```rust
struct Foo {
   bar: usize
}

#[extendr]
impl Foo{
    fn new(bar: usize) -> Self {
        Foo { bar }
    }
    fn get_bar(&self) -> usize {
        self.bar
    }
}
```

We will get code that is used as follows:

```R
instance = Foo$new(4)
bar = instance$get_bar()
```

Now this isn't particularly idiomatic. Admittedly it works a lot like [R6 classes](https://r6.r-lib.org/reference/R6Class.html) but these aren't really even recommended by Hadley or any other body I know of (Bioconductor uses S4 afaik).

A more idiomatic R example would let us do:
```R
instance = foo()
get_bar(instance)
```
(arguably getting fields could be replaced by the `$` operator, but this is a stand-in for a complex method call).

***

Now I think an easy template to use for this in the R wrappers is:

```
setClass("foo", slots = c(pointer = "foo_pointer"))
setGeneric("get_bar")
setMethod("get_bar", signature(hot = "foo"), function(){
    .Call(wrap__Foo__get_bar)
})
```

**Comment by clauswilke** [comment]
The Rust object is an encapsulated object, so it makes sense to represent it as such on the R side as well. Your proposed alternative approach would create all sorts of issues. Most importantly, it would pollute the namespace.

https://adv-r.hadley.nz/oo-tradeoffs.html#s3-r6

**Comment by multimeric** [comment]
Certainly there are pros and cons of each class system. I think it the right choice may depend on the number of methods and how generic they are. In any case I'm doing this S4 approach internally, but was happy to contribute it to the code generator if there was interest. Perhaps behind an attribute flag?

**Comment by yutannihilation** [comment]
While using S4 feels too formal, I understand this request to some extent. To make things pipe-friendly, the developers need to implement wrappers by themselves, which is a bit tiresome.

But, it often requires some manual tweak on R's side for better ergonomics, so, at the moment, I can't decide whether it's a good idea or not to generate all the code automatically.

**Comment by multimeric** [comment]
Could it not be configured using a simple `#[extendr]` option?

**Comment by yutannihilation** [comment]
Yeah, I guess of course it's possible, but I feel uneasy that the code can be generated in multiple ways, which would make it hard for us to maintain.

**Comment by yutannihilation** [comment]
To be clear, what's in my mind is generating *wrappers of the wrappers* like the following, not S3/S4 wrappers directly.

``` r
Foo_new <- function(bar) {
  Foo$new(bar)
}

get_bar.Foo <- function(instance) {
  instance$get_bar()
}
```

This provides the interface you want.

``` r
instance = foo()
get_bar(instance)
```

And this is pipe-friendly.

``` r
foo() |>
  get_bar()
```

**Comment by multimeric** [comment]
It does, but why not call the Rust code directly in those S3/S4 wrappers?

**Comment by yutannihilation** [comment]
I think it needs to be an environment to have mutable semantics, not copy-on-modify.

**Comment by multimeric** [comment]
But doesn't R just see a pointer, and all the mutable state is in Rust memory? So from R's perspective it is immutable (unless I've misunderstood)

**Comment by andy-thomason** [comment]
Currently, we represent class objects as a Rust Box.

Although this is indeed a pointer, the underlying SEXP controls
the lifetime of the object, freeing the Box when the last reference
is collected.

We will be shifting to the more formal ExternalPtr<T> which itself
behaves like a Box, allowing dereferencing but with a greater
degree of safety.

There is also a basic S4 wrapper which gives access to the slots.

We have decided to stick to the r6-like syntax for the moment
as it is more popular. We have limited time and resources, but any
suggestions are welcome.

The metadata we capture from the function
signatures and attributes could be expressed in different ways
and you can always write your own wrappers manually.

In the future, we may express some traits like `Index` and `Display`
through s3 classes. Maybe something like:

```rust
extendr_module! {
  mod mymod;
  impl Index for myclass;
  impl Display for myclass;
}
```

Which would allow `myobj[[i]]` and `print(myobj)`.

**Comment by multimeric** [comment]
> There is also a basic S4 wrapper which gives access to the slots.

What do you mean by this?

**Comment by andy-thomason** [comment]
https://github.com/extendr/extendr/blob/master/extendr-api/src/wrapper/s4.rs

**Comment by andy-thomason** [comment]
The primary reason for this is to access S4 classes generated externally to extendr.

**Comment by multimeric** [comment]
Oh right, I misunderstood. This is a wrapper class for accessing S4 fields in Rust, but I'm after the opposite: an S4 wrapper that wraps a Rust struct for use in R.

**Comment by andy-thomason** [comment]
Have a look in metadata.rs at the current r6-like implementation.

It would be possible to parameterise this to emit S4 classes also.

**Comment by multimeric** [comment]
Yes so I would be happy to write this wrapper using this metadata, but it hasn't yet been confirmed that you would accept such a PR.

**Comment by andy-thomason** [comment]
I would be happy, as long as it is an option.

How do the others think about this?

**Comment by yutannihilation** [comment]
As I commented above, I'm slightly against the idea. I understand some of the users might prefer S4-ergonomics, but we shouldn't provide multiple options to achieve the same thing at this stage. If you are confident that we can maintain it sustainably, I don't have strong opinion.

**Comment by CGMossa** [comment]
This issue and discussion has reached a stalemate. I vote for closing. Andy noted that the current S4-approach should migrate to an `ExternalPtr`-implementation. I'll see if this is already done and create a new issue if not. Thanks everyone!
