### ISSUE TITLE
Mac OS intermittent build failure.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#354]
We occasionally get a brew install failure: 

==> Running `brew cleanup checkbashisms`...
Error: The operation was canceled.

Does anyone know why this might be?

**Comment by yutannihilation** [comment]
This one?

https://github.com/r-lib/actions/issues/435#issuecomment-1004901409

**Comment by yutannihilation** [comment]
It seems they are addressing the issue. Let's wait for it for a while, and revisit here when we still see the failures a lot.

https://github.com/r-lib/actions/issues/435#issuecomment-1005678816

**Comment by yutannihilation** [comment]
Ah, one important thing is that we should probably move to v2. I'll create a pull request for it.
