### ISSUE TITLE
`data.frame` wrapper

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#356]
Following on from #331 which got a bit sidetracked. There was some interest in a lightweight wrapper for creating and manipulating `data.frame`s using extendr.

The obvious option is to make a new wrapper similar to `List`, and move the shared list-related methods to a trait that is implemented by `List` and `DataFrame`.

Another suggestion that just occurred to me is that we could simply add a new method to `List`, which validates and converts a `List` to a `data.frame`. This would be very lightweight and lets us easily re-use all the creation/manipulation methods for the `List` wrapper. For example:

```rust
impl List {
    /// Validates that the list would make a valid data.frame, then converts it to one by
    /// setting the appropriate metadata.
    pub fn as_data_frame(&self) -> Result<()>{
        // Check all elements are vectors
        if !self.values().into_iter().map(|itm| itm.is_vector()).all(){
            return Err(Error::Other("Not all list elements are atomic vectors".into()));
        }

        // Check all vectors are the same length
        let sizes: HashSet<usize> = self.values().into_iter().map(|vec|vec.len()).collect();
        if sizes.len() > 0 {
            return Err(Error::Other("Not all vectors are the same size".into()))
        }

        // Set metadata
        self.set_attrib(class_symbol(), "data.frame")?;
        self.set_attrib(row_names_symbol(), (1..sizes[0]).into())?;
        Ok(())
    }
}
```

The thing is, this is basically is a Rust implementation of the R function `as.data.frame`, so you could argue that we should just call this instead. 

Happy to hear thoughts or suggestions.

**Comment by andy-thomason** [comment]
I was thinking of a DataFrame wrapper that has methods relating to DFs and can only contain a valid
DF.

Just a pedantic observation: using .min() and .max() on an iterator is perhaps a thousand times more
efficient than using a hashset! If min() == max() they are all the same length.

**Comment by andy-thomason** [comment]
We do have a `data_frame!` macro, curiously, although this should become a procedural
macro in due course. Currently, it just runs the corresponding R code.

**Comment by multimeric** [comment]
> I was thinking of a DataFrame wrapper that has methods relating to DFs and can only contain a valid DF

I would agree, except that what methods do we need over just a list? I suppose the indexing operators?

**Comment by andy-thomason** [comment]
It would be worth looking at the R implementation to see what one can do.

I guess there is also some overlap with **dplyr**

**Comment by multimeric** [comment]
What do you mean by the R implementation? The functionality of a `data.frame` is entirely due to its S3 methods like `[.data.frame`, `unique.data.frame` etc. But we get those for free as long as we give it the right S3 class and structure.

**Comment by andy-thomason** [comment]
```
35 results - 15 files

src/library/base/R/as.R:
  38  
  39: as.list.data.frame <- function(x,...) {
  40      x <- unclass(x)

  43  }
  44: as.vector.data.frame <- function(x, mode = "any") {
  45      x <- as.list.data.frame(x)

src/library/base/R/by.R:
  41  
  42: by.data.frame <- function(data, INDICES, FUN, ..., simplify = TRUE)
  43  {

src/library/base/R/dataframe.R:
    39  row.names <- function(x) UseMethod("row.names")
    40: row.names.data.frame <- function(x) as.character(attr(x, "row.names"))
    41  row.names.default <- function(x) if(!is.null(dim(x))) rownames(x)# else NULL

   123  
   124: is.na.data.frame <- function (x)
   125  {

   134  ## Provide for efficiency reasons (PR#17600):
   135: anyNA.data.frame <- function(x, recursive = FALSE)
   136      any(vapply(x, anyNA, NA, USE.NAMES = FALSE))
   137  
   138: is.data.frame <- function(x) inherits(x, "data.frame")
   139  

   151  
   152: t.data.frame <- function(x)
   153  {

   157  
   158: dim.data.frame <- function(x) c(.row_names_info(x, 2L), length(x))
   159  
   160: dimnames.data.frame <- function(x) list(row.names(x), names(x))
   161  

   176  
   177: as.data.frame <- function(x, row.names = NULL, optional = FALSE, ...)
   178  {

   191  
   192: as.data.frame.data.frame <- function(x, row.names = NULL, ...)
   193  {

  1219  
  1220: xpdrows.data.frame <- function(x, old.rows, new.rows)
  1221  {

  1258  
  1259: cbind.data.frame <- function(..., deparse.level = 1)
  1260      data.frame(..., check.names = FALSE)
  1261  
  1262: rbind.data.frame <- function(..., deparse.level = 1, make.row.names = TRUE,
  1263                               stringsAsFactors = FALSE,

  1529  
  1530: as.matrix.data.frame <- function (x, rownames.force = NA, ...)
  1531  {

  1606  
  1607: Math.data.frame <- function (x, ...)
  1608  {

  1621  
  1622: Ops.data.frame <- function(e1, e2 = NULL)
  1623  {

  1697  
  1698: Summary.data.frame <- function(..., na.rm)
  1699  {

  1709  
  1710: xtfrm.data.frame <- function(x) {
  1711      if(tolower(Sys.getenv("_R_STOP_ON_XTFRM_DATA_FRAME_")) %in%

src/library/base/R/eval.R:
  58  
  59: within.data.frame <- function(data, expr, ...)
  60  {

src/library/base/R/factor.R:
  120  
  121: droplevels.data.frame <- function(x, except = NULL, exclude, ...)
  122    {

src/library/base/R/format.R:
  239  
  240: format.data.frame <- function(x, ..., justify = "none")
  241  {

src/library/base/R/frametools.R:
  18  
  19: subset.data.frame <- function (x, subset, select, drop = FALSE, ...)
  20  {

  66  
  67: transform.data.frame <- function (`_data`, ...)
  68  {

src/library/base/R/matrix.R:
  142  ## t.default is <primitive>
  143: t.data.frame <- function(x)
  144  {

src/library/base/R/rowsum.R:
  31  
  32: rowsum.data.frame <- function(x, group, reorder = TRUE, na.rm = FALSE, ...)
  33  {

src/library/base/R/split.R:
  37  ## This is documented to work for matrices too
  38: split.data.frame <- function(x, f, drop = FALSE, ...)
  39  {

src/library/graphics/R/plot.R:
  387  
  388: plot.data.frame <- function (x, ...)
  389  {

src/library/stats/R/models.R:
  59  
  60: formula.data.frame <- function (x, ...)
  61  {

src/library/stats/R/nafns.R:
   59  
   60: na.omit.data.frame <- function(object, ...)
   61  {

  113  
  114: na.exclude.data.frame <- function(object, ...)
  115  {

src/library/utils/R/frametools.R:
  20  
  21: stack.data.frame <- function(x, select, drop=FALSE, ...)
  22  {

  59  
  60: unstack.data.frame <- function(x, form, ...)
  61  {

src/library/utils/R/str.R:
  26  ## FIXME: convert to use sQuote
  27: str.data.frame <- function(object, ...)
  28  {
```

**Comment by multimeric** [comment]
I'm not sure I quite understand your point. These methods are already implemented for us, so how do they impact the creation of a wrapper class?

**Comment by andy-thomason** [comment]
This was just a survey of what people expect to do with data frames.

More generally, one would probably want to do iterator operations on a dataframe.
The dataframe should deref to a List (which derefs to a slice of Robj).

An iterator of tuples would be nice, but tricky to specify.

```
fn do_something(df: &DataFrame) -> usize {
  df.iter::<(&str, f64)>().filter(|(name, age)| age < 50.0).count()
}
```

**Comment by andy-thomason** [comment]
`FromIterator` would also be nice:

```
  let df : Dataframe = (1..=100).map(|i| (i, format("{}", i)).collect();
```

Perhaps the DataFrame should have a tuple type parameter `DataFrame<(Strings, Integers)>`.

**Comment by andy-thomason** [comment]
Having the vector types would allow us to specify the tuples for iterators.

We would need a trait with an Item type.

```
Integers -> Rint
Doubles -> Rfloat
Logicals -> Rbool
Strings -> Rstr
List -> Robj
```

(These should be the element of the slice and the return type of the elt() method.)

Conversely, the element types need to map to their vector types.

Thus (Rstr, Rint) should map to DataFrame<(Strings, Integers)>.

**Comment by multimeric** [comment]
That would make for a helpful iterator API, but would put a large burden on the user exhaustively specifying the type of each column in order to use this wrapper struct.

**Comment by andy-thomason** [comment]
I agree.

`iter()` is a bit overloaded on the vector types ATM and comes for free in the deref.

We maybe should stick to.

Iterator function|purpose
--|--
`values()`|Iterator over values using the wrapped native type - columns for a DF.
`names()`|A Strings object containing names of elements (column names in the case of a DF).
`pairs()`|Iterator over names and values combined.

Dataframe iterator function|purpose
--|--
`columns()`|Iterator over columns of a DF (synonym for `values()`) or matrix (ndarray ref if enabled).
`rows<T>()`|Result of an Iterator over rows of a DF -> must match the format or matrix (ndarray ref if enabled).
`row_names()`|A vector object containing names.

Creation function|purpose
--|--
`from_values()`|Convert an iterator into a vector
`from_pairs()`|Convert an iterator or names/values into a vector
`from_rows<T>()`|Convert an iterator of tuples to a vector.
`set_row_names()`|Set the row names

**Comment by multimeric** [comment]
So most of these I feel can be borrowed from `List`. Only the row-related methods are specific to the `data.frame`. For this reason I'm thinking we should move the `List` methods into a `ListTrait` trait that is impl by both `List` and `DataFrame`.

**Comment by andy-thomason** [comment]
`values()`,  and `elt()` could share a `Vector` trait with all wrapper types. They have
an `Item` type which is a scalar (eg. Rint) or wrapper (eg. Rstr).

`names()` is currently in `Attributes`, but may be better off in `Vector` with `row_names()`.

**Comment by andy-thomason** [comment]
You can now treat a list and other vector types like a slice:

```
fn elem3(list: List) -> Robj {
  list[3].clone()
}
```

`DataFrame` would inherit this with the List deref.

**Comment by multimeric** [comment]
Just wanting to check that you think deref inheritance is the way to go here? I'm concerned that it's a bit of an anti-pattern: https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deref.md. Could we not also implement this "inheritance" by moving all the `List`-like behaviour into a trait that is implemented by both `List` and `DataFrame`?

**Comment by multimeric** [comment]
Closed by https://github.com/extendr/extendr/pull/393.
