### ISSUE TITLE
Add Rprintln macro

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#36]
It would be great if there was an `Rprintln!()` macro that would function exactly like regular `println!()` but use `Rprintf()` to send the output to R. In addition, it might be useful to add `REprintln!()` to replace `eprintln!()` for errors.

Relevant documentation from Writing R Extensions: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Printing

**Comment by dasmoth** [comment]
Yes, I think these are helpful too.

I've actually have an implementation at https://github.com/dasmoth/extendr/commit/cc210bbd5e041f5df9952146344782aee3dc571f (there's a couple of silly typos in there, but fixes are in the subsequent two commits).  That branch is somewhat out-of-date at this point, but cherry-picking the rprint! macros and their support functions should be straightforward.

**Comment by clauswilke** [comment]
Would you mind creating a PR? We just have to decide a naming convention, rprintln or Rprintln? I believe in other places we use capital R, even if it goes against standard Rust naming styles. In any case, we should consistently use upper or lower case R.

**Comment by dasmoth** [comment]
Sure, happy to sort that out.

Re: naming...  given rustc's relatively-forceful preference for lower case (think you'd need `#[allow(non_snake_case)]` for the upper case version), I'm inclined to stick with lower case.  Certainly, all the other exposed extendr API does so far.  Anyone else with an opinion?
