### ISSUE TITLE
[graphics] support interactive features

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#365]
A followup of #360 

- [ ] `locator`
- [ ] `eventEnv`
- [ ] `eventHelper`

**Comment by Stalkcomrade** [comment]
Do you have ideas on how the work on this might be started?

**Comment by yutannihilation** [comment]
Thanks for your interest. I expect this will be a straightforward task to wrap these methods like I do in #360. Do you have any particular usages in your mind? This probably isn't very exciting feature as most of the implementations are the responsibility of graphic device developers.

**Comment by Stalkcomrade** [comment]
Thank you. 
I do not have any particular use cases. I am just looking for something to pickup and try to work on this.

**Comment by yutannihilation** [comment]
I see. Unfortunately, this needs to wait for #360, but I found some difficulties on #360 so it might take some time... I'll ping you when the things are ready. Thanks for your help!

**Comment by yutannihilation** [comment]
@Stalkcomrade 
I think now the things are ready for developing this feature, while there's not good documentation to start with... Feel free to ask questions if you are still interested in this!

**Comment by Stalkcomrade** [comment]
@yutannihilation, thank you for letting me know!
I am interested in working on this. You did the heavy lifting =) 

I looked through the work you have done in #360. Also, skimmed through  https://github.com/wch/r-source/blob/9f284035b7e503aebe4a804579e9e80a541311bb/src/modules/X11/devX11.c

I do not think I clearly understand what is going on, but, at least,
- [ locator] 
should be quite easy to add (i.e., make a wrapper for X11_Locator as you did with other C functions).

The only thing I am not sure about is how to get x and y coordinates, but I will look again at the code.

**Comment by yutannihilation** [comment]
Thanks! It's fine to add these functions one by one. Honestly I too don't know how to use these APIs... You can add one by one. I was just hesitant to file too many issues.

> how to get x and y coordinates

It depends on the device, so you don't need to care about the details. You can catch the x and y coordinates from the user-implemented method and assign it to `x: *mut f64` and `y: *mut f64` just like this function does:

https://github.com/extendr/extendr/blob/d1fd227aee1d45c12d5eb9911620e84a70cb0474/extendr-api/src/graphics/device_driver.rs#L517-L530

**Comment by Stalkcomrade** [comment]
I wonder what would be the right way to write a test function for the locator (#389).
As far as I got, there should be functions simulating events on the canvas (like, mouse clicks?).

Any hint on what should I look at?

**Comment by Stalkcomrade** [comment]
@yutannihilation,  also added functions for `eventHelper`.
Could you review it?

I could not grasp how to deal with `eventEnv`.
At first, I thought that it should point to a special type of environment (like `R_GlobalEnv`).
But now It seems to me that it is only referenced handled internally later in `eventHelper` 

https://github.com/wch/r-source/blob/9f284035b7e503aebe4a804579e9e80a541311bb/src/include/R_ext/GraphicsDevice.h#L639

**Comment by yutannihilation** [comment]
It looks good! But, I need some time to get ready again for reviewing it, sorry. Feel free to ping me if I don't come back in a week...

> As far as I got, there should be functions simulating events on the canvas (like, mouse clicks?).

I think we don't need to simulate the user interaction for testing. The device can return immediately.

> I could not grasp how to deal with `eventEnv`.

I too didn't figure out, but it seems it's set by the user via `setGraphicsEventEnv()`.

https://stat.ethz.ch/R-manual/R-patched/library/grDevices/html/getGraphicsEvent.html

I set it to `empty_env` but it seems we can leave it as a null pointer because it's set in `GEcreateDevDesc` anyway. 

https://github.com/wch/r-source/blob/991248c1f0b3fc182d8e1030ffa6aa66c8bd1d90/src/main/devices.c#L512

Actually, only two graphics device implement `eventHelper`, but none of them set `eventEnv`.

* https://github.com/wch/r-source/blob/9f284035b7e503aebe4a804579e9e80a541311bb/src/modules/X11/devX11.c#L2971
* https://github.com/wch/r-source/blob/f09d3d7fa4af446ad59a375d914a0daf3ffc4372/src/library/grDevices/src/devWindows.c#L1758

**Comment by Stalkcomrade** [comment]
@yutannihilation, whenever you'll have some time, could you please have a quick review on #389?

**Comment by yutannihilation** [comment]
Sorry for the delay!

**Comment by yutannihilation** [comment]
Closed by #389
