### ISSUE TITLE
Error when using type Option<Robj> as a function's argument

### ISSUE THREAD

**Issue by daniellga** [extendr/extendr#368]
Hi, once again, thank you for this amazing crate.

I am trying to write a function of this kind where the r_arr argument (Robj type) should be an optional argument.

```
use extendr_api::prelude::*;

/// @export
#[extendr]
fn example_function(r_arr: Option<Robj>) -> () {
        if let Some(x) = r_arr {
            println!("success")
        } else {
            eprintln!("error")
        }
}
```

I think I saw in this repo `Option<Robj>` being used several times, however I keep getting the following error. Do you know why can't I use it?

```
error[E0599]: no variant or associated item named `from_robj` found for enum `Option` in the current scope
  --> src/lib.rs:99:1
   |
99 | #[extendr]
   | ^^^^^^^^^^ variant or associated item not found in `Option<extendr_api::Robj>`
   |
   = note: this error originates in the attribute macro `extendr` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Here is how extendr_api is in the Cargo.toml file:
```
[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr", features = ["ndarray"] }
```

**Comment by yutannihilation** [comment]
In my opinion, `Robj` can represent all R objects including `NULL`, so `Option<Robj>` doesn't seem to make sense as an interface between R and Rust. If you want to reject `NULL`, you can check `is_null()`.

Could you elaborate a bit? What do you want to achieve by wrapping it with `Option`?

**Comment by daniellga** [comment]
I was actually using it to make the argument from the R function optional, so the function would work with or without the r_arr argument when called from R. It would work like that: if called from R without the `r_arr` argument, R would translate it as `example_function(r_arr = NA)` and then call the rust counterpart.

It seemed pretty straight forward until I found this issue. Is there an easier way to make arguments optional when calling from R without getting missing args error in Rust?

**Comment by yutannihilation** [comment]
Thanks for the details, I guess what you want is this one?

https://github.com/extendr/extendr/pull/334

**Comment by daniellga** [comment]
Nice! It worked pretty well.I have no idea how his suggested example below would work (tried without success), but using NULL as default for Robj solves my problem.
```
#[extendr] 
fn fred(#[default="NULL"] x: Option<i32>) {
}
```

Calling from R:
```
> fred(3L)
> fred()
Error in fred() : expected an integer scalar
> fred(NULL)
Error in fred(NULL) : expected an integer scalar
```

**Comment by andy-thomason** [comment]
There is a `Nullable` wrapper explictly for NULL values, but enough confusion exists that when
we transition to TryFrom as the default, it would be worth making all the Option variants take Nulls
as well as NAs.
