### ISSUE TITLE
<Device>::polyline() segfaults

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#370]
If I add the following line to the graphics test,

``` rs
device.polyline([(0.0, 0.0), (0.0, 2.0), (2.0, 0.0)], &gc);
```

the test randomly fails with the following error.

```
(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

This seems to happen with `polygon`, `path` as well.

But I cannot reproduce this on a real R session... (So, I guess this won't be a problem when using in an R package)

``` r
rextendr::rust_eval(r"--(
use extendr_api::graphics::*;

R!("postscript()")?;

let dev = Device::current()?;
let mut gc = Context::from_device(&dev, Unit::Inches);

dev.polyline([(0.0, 0.0), (0.0, 2.0), (2.0, 0.0)], &gc);

R!("dev.off()")?;
)--", patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr")))
```

I tried adding `single_threaded()` around `GEPolyline()` but no luck. This probably needs some investigation.

**Comment by Ilia-Kosenkov** [comment]
I synchronized my fork of `extendr` with upstream, which triggered my version of CI. Linux runner failed with a segfault. Can it be related to this issue? https://github.com/Ilia-Kosenkov/extendr/runs/5111815197?check_suite_focus=true#step:11:127

> running 2 tests
  TextMetric { ascent: 0.269, descent: 0.007500000000000001, width: 0.278 }
  TextMetric { ascent: 0.269, descent: 0.11, width: 0.278 }
  TextMetric { ascent: 0.367, descent: 0.007500000000000001, width: 0.278 }
  TextMetric { ascent: 0.269, descent: 0.007500000000000001, width: 0.278 }
  TextMetric { ascent: 0.269, descent: 0.11, width: 0.278 }
  TextMetric { ascent: 0.367, descent: 0.007500000000000001, width: 0.278 }
  error: test failed, to rerun pass '-p extendr-api --test graphics_tests'
  
 > Caused by:
    process didn't exit successfully: `/home/runner/work/extendr/extendr/target/debug/deps/graphics_tests-73e67e753cc1b2b3 --nocapture` (signal: 11, SIGSEGV: invalid memory reference)
  Error: 'Testing for default target': cargo failed with code 101 (args: test  -- --nocapture)

**Comment by yutannihilation** [comment]
Probably yes. I think all these errors are because we run the tests parallelly. I should have added `--test-threads=1` to it as well.

**Comment by yutannihilation** [comment]
I'm closing this issue as the title was solved.
