### ISSUE TITLE
Add documentation for lang! macro

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#38]
It looks like the `lang!` macro is a core concept of how extendr works. Unfortunately, it's not clear to me what exactly it does, and the documentation is rather short:
https://github.com/extendr/extendr/blob/8114138f483c8f31de3f3524826d147a11e0ae1e/extendr-api/src/args.rs#L85-L87

It would be great if a bit more explanation could be added, and maybe 2-3 different examples of how it can be used.

**Comment by andy-thomason** [comment]
I'll try to get some time to do some documentation. A big documentation drive is required!

**Comment by andy-thomason** [comment]
I was hoping to make a procedural R! macro to replace the lang!(...).eval_blind() construct.

R!{data.frame(a=@vec![0, 1], b=@vec![3, 4])}

Where the syntax is as close to R as we are able with token streams
and @ precedes a rust expression.

**Comment by clauswilke** [comment]
I think this issue is addressed now.
