### ISSUE TITLE
How to return a collection of rust structs.

### ISSUE THREAD

**Issue by sstadick** [extendr/extendr#390]
Hello! I suspect I'm missing something simple, I have a function, registered with `#[extendr] / extendr_module!` that I would like to have return something like `Vec<Point>`. Is that possible at this time?

Contrived example:

```rust
struct Point {
    x: u32,
    y: u32,
}

#[extendr]
impl Point {
    fn get_x(&self) -> u32 { self.x }
    fn get_y(&self) -> u32 { self.y }
}

#[extendr]
fn get_points(place: String) -> Vec<Point> {
    let points: Vec<Point> = get_points_from_place(place);
    points
}

extendr_module! {
    impl Point;
    fn get_points;
}
```

This generates an error like:
```
 the trait `From<Vec<Point>>` is not implemented for `extendr_api::Robj`
```

**Comment by andy-thomason** [comment]
Hi @sstadick 

Sorry about the delay.

You should probably return a List directly and implement `From<Point> for Robj`.

Then you can return `List::from_values(get_points_from_place(place))`

I hope this helps.

**Comment by andy-thomason** [comment]
Something like:
```
impl From<Point> for Robj {
    fn from(point: Point) -> Self {
        r!([point.x, point.y])
    }
}
```

**Comment by andy-thomason** [comment]
Using R types like List, Integers and Doubles is often preferable to using `Vec`, which requires an extra allocation.

**Comment by sstadick** [comment]
Hi @andy-thomason thanks for getting back to me!

That makes sense - I was trying to use `from_values` but hadn't implemented `From<Point> for Robj`. 

What if I do actually want a `List` of of the underlying class though? I'd like to be able to call my defined methods on (things that are more complex than `get_x`). 

In my real code I'm executing a query on a data source, and gathering all the results, which are structs with defined impls on them. I want to pass back a the collection of results to R and still be able to call methods on elements in that collection.

**Comment by andy-thomason** [comment]
Interesting...

You can use a `List` of `ExternalPtr<Point>` but it is not going to be efficient as there is a large overhead on an R object.

With vectors of structures, it is best to convert them to structures of vectors:

```
struct Points {
    x: Doubles,
    y: Doubles,
}
```
and return `data_frame!(x=points.x, y=points.y)`

**Comment by sstadick** [comment]
I see. I think that makes sense. I'll try to re-think how I have things organized to fit that a little better. R is not my normal language and I'm not used to what is "normal" there just yet.
