### ISSUE TITLE
R 4.2 and Windows

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#396]
(An issue might not be the right place, but I'd like to post freshly rather than commenting an ongoing pull request or issue as this is long)

## Overview

R 4.2 is scheduled for April 22. There's several changes that we have to cope with, but we have little time left. 

### References

* release schedule: https://developer.r-project.org/
* NEWS: https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.html

## Windows-related changes in R 4.2

R 4.2 uses [Rtools42](https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html) (more precisely, rtools42-5038-5046.exe), which replaces Rtools40. The main point of Rtools42 is that it supports UCRT as the C runtime so that Windows can use UTF-8 as the native encoding at last.

### No 32-bit

Rtools42 doesn't contain the 32-bit toolchains and there will be no 32-bit Windows. This is a very good news to us, because compiling the 32-bit version had been a headache. On the other hand, this might make the setup a bit complex as long as extendr supports both R < 4.2 and R >= 4.2. We need to review

* the CI setup (it's probably fine as Rtools42 is officially supported by r-lib/actions)
* `rextendr::use_extendr()`

### Different toolchain

Rtools42 has a different structure than Rtools40. Currently we include

``` 
$env:RTOOLS40_HOME\mingw64\bin (for 64-bit)
```

But, it seems we need to use the following two instead ([ref](https://github.com/wch/r-source/blob/f09d3d7fa4af446ad59a375d914a0daf3ffc4372/src/library/profile/Rprofile.windows#L70-L71)).

``` 
$env:RTOOLS42_HOME\x86_64-w64-mingw32.static.posix\bin
$env:RTOOLS42_HOME\usr\bin
```

~~I experienced these problems as well, but couldn't reproduce it on my local any more. Not sure why...~~

#### Different linker path ([ref](https://github.com/extendr/extendr/pull/376#issuecomment-1039753473))

The default linker of the target `x86_64-w64-mingw32-gcc`, which exists in Rtools40 but not in Rtoos42. We need to change the linker (e.g. create `.cargo/config.toml` like below), otherwise either the compilation fails or it falls back to a wrong linker so that the binary gets linked to a wrong C runtime (i.e. MSVCRT).

``` toml
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32.static.posix-gcc.exe"
```

We can also inject this configuration via the corresponding environmental variable, `CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER`. See [the Cargo Book](https://doc.rust-lang.org/cargo/reference/config.html#environment-variables) about how this works.

#### No `libgcc_eh` and `libgcc_s` ([ref](https://github.com/extendr/extendr/pull/376#issuecomment-1040229923))

The default compilation setting of the target `x86_64-w64-mingw32-gcc` requires the following libraries, but these are not included in Rtools42.

* `libgcc_eh` (both on `stable-msvc` and `stable-gnu`)
* `libgcc_s` (on `stable-gnu`)

For `libgcc_eh`, we can simply copy `libgcc`, but we know nothing about `libgcc_s` yet.

### UTF-8 support

I think there's nothing we have to do here. extendr uses only UTF-8.

### API deprecation

I think some APIs disappeared, but we already addressed these, if I remember correctly.

### Should we switch to GNU toolchain?

The main reason we used the MSVC toolchain and do cross compilation is supporting the 32-bit version was weird. Now that we only have 64-bit, do we switch to GNU toolchain now?

If we choose this option, we probably need to add `Makevars.ucrt` to overwrite `TOOLCHAIN` in `Makevars.win`.

https://github.com/extendr/rextendr/blob/b9f4aa2f26d35381cbd2e9a00722742d7ad26c2c/inst/templates/Makevars.win#L2

### Should we use a custom target?

Another option would be to use the custom target

https://github.com/extendr/extendr/pull/376#issuecomment-1040631973

IMHO, we need more time to investigate, so it's a bit difficult for now as we have little time.

## Ongoing pull requests

* libR-sys: https://github.com/extendr/libR-sys/pull/103
* extendr: https://github.com/extendr/extendr/pull/376
* rextendr: https://github.com/extendr/rextendr/pull/187
* document about the toolchain setups: https://github.com/extendr/libR-sys/pull/94

**Comment by yutannihilation** [comment]
@Ilia-Kosenkov @andy-thomason
Let me confirm. While there are still some details I need to finish, do we all agree on this direction of using GNU toolchain for R >= 4.2 on Windows?

> Should we switch to GNU toolchain?

**Comment by yutannihilation** [comment]
Let's switch to the GNU toolchain.

**Comment by yutannihilation** [comment]
Now that all pull requests got merged, I think I finish this issue! Closing.

**Comment by CGMossa** [comment]
This is the last issue I see mention of libgcc_eh.
As is already stated, libgcc_eh is a requirement of the GNU host for building rust;
Thus if you're using rustup, you may find it:
`~\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\self-contained`
(that is if you `rustup toolchain install stable-gnu` or similar)
