### ISSUE TITLE
Getting involved.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#4]
Let me know if you are interested in getting involved with this project.

Leave a comment in this issue if you want to join in.

**Comment by CGMossa** [comment]
I want to join in :D

**Comment by CGMossa** [comment]
Thanks!

**Comment by andy-thomason** [comment]
We now have a Discord channel:

https://discord.gg/gNegZu

**Comment by lebensterben** [comment]
@andy-thomason this link is expired

**Comment by andy-thomason** [comment]
Hopefully, this one is more robust.

https://discord.gg/7hmApuc

**Comment by knapply** [comment]
> Hopefully, this one is more robust.

Confirmed. It works.

**Comment by andy-thomason** [comment]
Discord links have a short expiry, so give us a call if you want to join.

**Comment by andy-thomason** [comment]
More permanent discord link:

https://discord.gg/7hmApuc

**Comment by michelk** [comment]
I would like to get involved. 

Is it on the roadmap to call R from rust (e.g. for charting with ggplot)

**Comment by andy-thomason** [comment]
Hi @michelk . Sorry that I didn't see this earlier!

Yes, I would love to see some R packages wrapped in Rust.

We have some of the ggplot team present who could confirm details.

I can create a project to get things started.

I would imagine that:

[ ] Build a complete list of ggplot functions and data.
[ ] Design an idiomatic mapping from Rust to ggplot.
[ ] Build a first simple example of a ggplot run.
[ ] Provide output options, png, X11 etc.

A good rule would be to make it as famillar as possible to existing ggplot users
so that ggplot examples map easilly to ggplot-rs

Perhaps @clauswilke, @yutannihilation or @dfalbel might be able to comment.

**Comment by clauswilke** [comment]
It's low priority for me. I don't quite see the benefit of having a dedicated Rust interface to ggplot2 versus just calling ggplot2 code from an `R!` macro. And ggplot2 evolves, so you'd have to constantly make sure you're in sync with the mainline. And what about all the extension packages? Do you wrap all of them also?

In any case, doesn't hurt to experiment with this, so if somebody wants to try more power to them. It should be a separate crate though, not part of extendr-api.

**Comment by yutannihilation** [comment]
> I don't quite see the benefit of having a dedicated Rust interface to ggplot2 versus just calling ggplot2 code from an `R!` macro.

Maybe a wrapper crate makes it editor-friendly a bit? (e.g. code completion won't happen inside `R!` macros) But, I too don't see when it's meaningful to create a wrapper.

**Comment by yutannihilation** [comment]
But, it sounds interesting to show how to use graphic devices from Rust. I have no idea about how they work...

**Comment by andy-thomason** [comment]
I think there a good number of the rust-bio crew who would like to plot
results.

It is true that you can get a long way with r!, R! and call! but the point
about code
completion is a strong one.

**Comment by yutannihilation** [comment]
Ah, thanks, got it. So, what we need here is not 1:1 correspondence to ggplot2's functions, but some nice API to allow Rust users to generate nice plots, right? I think it won't be a single macro call since we probably need some conversion or transformation of data, so creating a wrapper for these steps makes sense to me, though I still don't see what the API should look like.
