### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#405]
The build is currently failing because `devtools` can't find `usethis`.

**Comment by yutannihilation** [comment]
I see this kind of installation problem on other repo, too. I think time will solve.

**Comment by yutannihilation** [comment]
It's fine now. It seems that was a temporary problem.

https://github.com/extendr/extendr/runs/6285666686?check_suite_focus=true

**Comment by andy-thomason** [comment]
Phew! Thanks @yutannihilation
