### ISSUE TITLE
Update version of `actions/cache`

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#414]
It seems we depend on [`actions/cache`](https://github.com/actions/cache) indirectly through [`setup-r-dependencies`](https://github.com/r-lib/actions/tree/v2/setup-r-dependencies) and we are currently using `v2` https://github.com/extendr/extendr/blob/7e41a09686066b11878e415eea8cb968c91399f2/.github/workflows/test.yml#L205-L216

I encountered an issue with this cache in my forked repo (e.g., [this](https://github.com/Ilia-Kosenkov/extendr/runs/6704483127?check_suite_focus=true#step:1:41)), so I found this issue https://github.com/actions/cache/issues/811.

From the discussion there I found out the latest version of `actions/cache` is [`3.0.3`](https://github.com/actions/cache/releases/tag/v3.0.3) (released quite recently), so perhaps it is time to switch to the newer version for us?

**Comment by Ilia-Kosenkov** [comment]
This is invalid, I incorrectly interpreted this field as a version of actions/cache, not the version of cache itself. I am closing this issue, sorry for unnecessary noise.

**Comment by yutannihilation** [comment]
I think you can send a pull request to update this line.

https://github.com/r-lib/actions/blob/9ea29bb8182371e811c469f947bc64ac054b557f/setup-r-dependencies/action.yaml#L61
