### ISSUE TITLE
Docs build error: `` error[E0432]: unresolved imports `libR_sys::DevDesc`, `libR_sys::R_GE_gcontext` ``

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#415]
See: https://docs.rs/crate/extendr-api/0.3.1/builds/567780

**Comment by yutannihilation** [comment]
The build should be reproducible on local with Docker: https://github.com/rust-lang/docs.rs/blob/master/README.md#build-subcommand

Other information about their build environment can be found on the docs: https://docs.rs/about/builds#failures-and-rebuilds

**Comment by yutannihilation** [comment]
I don't try to reproduce this yet, but I think I found the reason. docs.rs runs a Ubuntu 20.04,

https://github.com/rust-lang/crates-build-env/blob/8adee15db57330f64c2c49779210bbf0e646a1ca/linux/Dockerfile#L1

and the version of R is 3.6.

https://packages.ubuntu.com/focal/r-base-core

Why is this a problem? Well, we do have the precompiled bindings file for R 3.6 on libR-sys, but, since this was generated before we added support for graphics-related ones, this is unusable for `graphics` feature on extendr-api.

https://github.com/extendr/libR-sys/blob/master/bindings/bindings-linux-x86_64-R3.6.rs

So, I think we have several options:

1. Do nothing: as the problem is the build image is a bit too old, we can just wait until they switch to Ubuntu 22.04. But it's unclear when the day will come c.f. https://github.com/rust-lang/crates-build-env/issues/84
2. Remove `graphics` feature
3. Use `libR-sys/bindgen` feature
4. Remove or regenerate bindings for R 3.6 on libR-sys

**Comment by multimeric** [comment]
And we can't submit compiled decks ourselves, from CI, can we?

**Comment by yutannihilation** [comment]
I believe we can't. What do you mean?

**Comment by yutannihilation** [comment]
Confirmed. The error is reproducible with R 3.6 while the same command passes with the latest version of R.

https://github.com/yutannihilation/extendr-test-R-3.6/runs/7376904757?check_suite_focus=true

**Comment by multimeric** [comment]
> I believe we can't. What do you mean?

Oh, I just meant that maybe there's a way to submit pre-compiled docs without having the docs.rs build system compile them for us. But I can't find any such mechanism. I think your PR is a good solution.

**Comment by yutannihilation** [comment]
Ah, I see. If it were possible, we should build it by ourselves...

**Comment by Ilia-Kosenkov** [comment]
If `bindgen` can be used, I think it is a safe way -- docs are built infrequently (like, once per submission if I am not mistaken), so we can survive with extra build steps. I suggest we give it a shot.

It may be also worth re-visiting old bindings and updating them with `graphics` support if that is possible, as a separate issue.

**Comment by yutannihilation** [comment]
Thanks. Then let's use bindgen.

**Comment by multimeric** [comment]
What needs to be done to fix this?

**Comment by yutannihilation** [comment]
Oh, maybe we can just set `LIBRSYS_R_VERSION` envvar?

https://github.com/extendr/libR-sys#configuration

**Comment by multimeric** [comment]
Oh I think I understand now. The build server has an old version of R that doesn't include more recent features? Yeah, if `docs.rs` has support for setting env vars, then let's try it?

**Comment by multimeric** [comment]
I don't think the [metadata file](https://docs.rs/about/metadata) lets us set env vars, but could we maybe add a hack into the `build.rs` such that the existence of [`DOCS_RS`](https://docs.rs/about/builds#detecting-docsrs) makes it use a hardcoded version of R 3.6 that we bump whenever the docsrs build image get upgraded?

**Comment by yutannihilation** [comment]
I see. Thanks for investigation. Then, maybe we should go with the bindgey way as we discussed above?

**Comment by multimeric** [comment]
Does that mean generating the `libR-sys` source code from scratch each time? I don't really mind, but is that any better than checking for `DOCS_RS`?

**Comment by yutannihilation** [comment]
In my opinion, it would be better because we don't need to embed the logic just for docs.rs in the source code.

**Comment by multimeric** [comment]
Okay. I'm not sure how to do this, but a PR would be great.

**Comment by yutannihilation** [comment]
I'd vote for the option 4 (Remove or regenerate bindings for R 3.6 on libR-sys) above, but I don't have strong opinion here. I don't think any of the options is significantly good or bad than the others.

**Comment by yutannihilation** [comment]
> I'm not sure how to do this

I think you can just add `bindgen` feature to `[package.metadata.docs.rs]`.

**Comment by multimeric** [comment]
Do we not already have this? https://github.com/extendr/extendr/blob/13d81bfbd5ff38f7ec6c56a3059baae5846fa60d/extendr-api/Cargo.toml#L47

Why doesn't it work?

**Comment by yutannihilation** [comment]
Oh, sorry. I completely forgot I made the change. Then, it's just that the version is not published yet.

**Comment by multimeric** [comment]
So we need to make a new release?

**Comment by yutannihilation** [comment]
Yeah, this should be solved when we publish a new release. If you mean you want to publish it now, I have no idea whether we even have a criteria for releasing, sorry.

**Comment by multimeric** [comment]
Okay, I'll look into that.

As an aside, did you/we test if this `bindgen` solution works, using e.g. the docs.rs CLI? https://github.com/rust-lang/docs.rs#cli

**Comment by yutannihilation** [comment]
No, I didn't.

**Comment by multimeric** [comment]
Closed now that https://github.com/extendr/extendr/pull/426 was proven to solve this.
