### ISSUE TITLE
Switch from actions-rs to dtolnay/rust-toolchain?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#425]
c.f https://www.reddit.com/r/rust/comments/vyx4oj/actionsrs_organization_became_unmaintained/

**Comment by andy-thomason** [comment]
Seems like a sensible idea.

**Comment by yutannihilation** [comment]
It seems we'll have no choice but to switch.

https://github.com/extendr/extendr/issues/452

**Comment by CGMossa** [comment]
@yutannihilation Seems like a sensible solution. If you need support on this @yutannihilation let me know. Unfortunately I don't have the CI-skills to carry this on my own.

**Comment by yutannihilation** [comment]
Thanks, this should be easy. I will create pull requests.

**Comment by yutannihilation** [comment]
Hmm, it turned out it's not very easy. I'll investigate the failures...

**Comment by yutannihilation** [comment]
It seems I hit this problem.

https://github.com/KyleMayes/clang-sys/issues/154

**Comment by yutannihilation** [comment]
Done!
