### ISSUE TITLE
Use of declarative macros inside #[extendr] impl mystruct{...}

### ISSUE THREAD

**Issue by sorhawell** [extendr/extendr#428]
Dear extendr's. Thank you for making this wonderful tool.

I unsurprisingly use extendr to wrap and expose rust structs to the R world. These structs happen to have hundreds of methods with similar function signatures. I have tried to use a declarative macro, however this is not being picked up by the` [#extendr]impl{...}` procedural macro.

Here's a minimal toy example [minimal example](https://github.com/sorhawell/extendr_macro_issue/blob/main/src/rust/src/lib.rs) forked from the hellorextendr template.

Only monday methods is being exported to [extendr-wrappers.R](https://github.com/sorhawell/extendr_macro_issue/blob/main/R/extendr-wrappers.R) because it is explicitly implemented. All other weekday methods e.g. Friday are available on rust side, see test, but not exported.

I Imagine the `#[extendr]` is being evaluated first some how and there for is not picking up on `this is_it_x![]` macro.
Could there be some kind of workaround ?

All the best 

copy of minimal example code:
```rust
use extendr_api::prelude::*;

/// Return string `"Hello world!"` to R.
/// @export
#[extendr]
fn hello_world() -> &'static str {
    "Hello world!"
}

#[macro_export]
macro_rules! is_it_x{
    ($self:ident, ) => {};
    ($self:ident, $name:ident $($tail:tt)*) => {

            pub fn $name(&$self) -> bool {
                $self.day == stringify!($name)
            }

            is_it_x![$self, $($tail)*];

    };
}

struct DayOfWeek {
    day: String,
}

#[extendr]
impl DayOfWeek {
    pub fn new(s: &str) -> Self {
        DayOfWeek { day: s.to_string() }
    }

    pub fn monday(&self) -> bool {
        self.day == "monday"
    }

    is_it_x![self, tuesday wednesday thursday friday saturday sunday];
}

// Macro to generate exports.
// This ensures exported functions are registered with R.
// See corresponding C code in `entrypoint.c`.
extendr_module! {
    mod helloextendr;
    impl DayOfWeek;
    fn hello_world;
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        let dow = DayOfWeek::new(&"friday");

        println!("it is friday today:{}", dow.friday());
    }
}
```
It seems

**Comment by multimeric** [comment]
I believe the macro expansion actually works [outside in](https://rustc-dev-guide.rust-lang.org/macro-expansion.html#eager-expansion) (lazy), so in this case the `$[extendr]` macro will be evaluated before your `is_it_x!` macro. This isn't a decision made by extendr so much as by the Rust compiler, so there's not a great deal of help we can provide. You could maybe look into the [`eager` macro](https://docs.rs/eager/0.1.0/eager/macro.eager.html) which seems to offer a solution to this (somehow).

**Comment by sorhawell** [comment]
Thanks for advice! I think I will just write out every method or copy-paste the generated macro expansion in to the file.

I tried out the eager crate. Simply including it in Cargo.toml file makes rust analyzer go nuts with error messages about extendr. It does compile though, also when adding the eager beginners example.
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/8015271/185224712-60689a92-b755-457f-8376-d642a9189b4b.png">

But I could not make my recursive macro work. That breaks compilation.
[https://github.com/sorhawell/extendr_macro_issue/blob/eager/src/rust/src/lib.rs](try eager code)

**Comment by andy-thomason** [comment]
You can also make multiple impl blocks for the same type and so could potentially embed an entire impl in your macro. This way the procedural macro will be executed after the macro is executed. Just a thought.

**Comment by sorhawell** [comment]
Many thanks for the hints.


It seems there cannot be to #[extendr]-tagged impl blocks. Many conflicts.
There can me multiple non-tagged impl blocks, but these are not exported.
It is possible to place one #[extendr]-tagged impl block inside a macro, and all methods are exported.
macro
  inside #[extendr]-tagged impl block
  inside macro
  does not work either
  
 So it is possible to use one 'global' macro, but so far not possible to use nested macros.


`use extendr_api::prelude::*;

/// Return string `"Hello world!"` to R.
/// @export
#[extendr]
fn hello_world() -> &'static str {
    "Hello world!"
}

#[macro_export]
macro_rules! impl_dayofweek{
    ($self:ident, $($name:ident)*) => {
        #[extendr]
        impl DayOfWeek {
            pub fn new(s: &str) -> Self {
                DayOfWeek { day: s.to_string() }
            }

            pub fn monday(&self) -> bool {
                self.day == "monday"
            }

            $(
                pub fn $name(&$self) -> bool {
                    $self.day == stringify!($name)
                }
            )*
        }

        extendr_module! {
            mod helloextendr;
            impl DayOfWeek;
            fn hello_world;
        }

    };
}

struct DayOfWeek {
    day: String,
}

impl_dayofweek!(self, tuesday wednesday thursday friday saturday sunday);

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        let dow = DayOfWeek::new(&"friday");

        println!("it is friday today:{}", dow.friday());
    }
}
`
