### ISSUE TITLE
Compilation error when running from R

### ISSUE THREAD

**Issue by daniellga** [extendr/extendr#429]
Hi! I am trying to reproduce audio using the `cpal` crate from R. I added the `play` function and suddenly I am getting compiler errors when running from R. When I run `cargo test play_test` it works well. Do you know what's going on here?

Error:
```
─  DONE (audior)
Error in dyn.load(library_path) : 
  unable to load shared object '/mnt/wd/projects/audior/src/audior.so':
  /mnt/wd/projects/audior/src/audior.so: undefined symbol: snd_pcm_hw_params_get_period_size_min
Error in `value[[3L]]()`:
! Failed to generate wrapper functions.
✖ error in callr subprocess
```

lib.rs:
```
mod play_audio;

/// @export
#[extendr]
pub fn play(r_arr: RMatrix<f64>, sr: i32) {
    let arr: ArrayView2<f64> = ArrayView2::from_robj(&r_arr).expect("cannot convert Robj to ArrayView2");
    play_audio::play(&arr, sr as u32)
}

extendr_module! {
    mod audior;
    fn load;
    //fn stream;
    fn to_mono;
    fn get_duration;
    fn get_samplerate;
    fn resample;
    fn fft;
    fn realfft;
    fn get_window;
    fn play;
}
```

play_audio.rs:
```
use ndarray::ArrayView2;
use cpal::{Sample, SampleFormat, SupportedStreamConfig, SampleRate, BufferSize, StreamConfig};
use cpal::traits::{DeviceTrait, HostTrait, StreamTrait};

pub fn play(arr: &ArrayView2<f64>, sr: u32) {
    let channels = arr.nrows();
    let samples = arr.ncols();
    
    // convert to interleaved
    let mut data_interleaved = Vec::with_capacity(channels * samples);
    for i in 0..samples {
        for ch in 0..channels {
            data_interleaved.push(arr[[ch, i]] as f32);
        }
    }
    
    let host = cpal::default_host();
    let device = host.default_output_device().expect("no output device available");
    let config = StreamConfig {
        channels: channels as u16,
        sample_rate: SampleRate(sr), // Audio device default sample rate is set to 192000
        buffer_size: BufferSize::Default,
    };
    
    let err_fn = |err| eprintln!("an error occurred on the output audio stream: {}", err);

    let mut data_interleaved_iter = data_interleaved.into_iter();
    let mut next_value = move || {
        data_interleaved_iter.next().expect("cannot get next iter value")
    };

    let stream = device.build_output_stream(
        &config,
        move |data: &mut [f32], _: &cpal::OutputCallbackInfo| {
            write_data(data, channels, &mut next_value)
        },
        err_fn
        ).unwrap();

    fn write_data<T: Sample>(output: &mut [T], channels: usize, next_sample: &mut dyn FnMut() -> f32) {
        for frame in output.chunks_mut(channels) {
            for sample in frame.iter_mut() {
                let value: T = Sample::from(&next_sample());
                *sample = value
            }
        }
    }

    stream.play().unwrap();
    std::thread::sleep(std::time::Duration::from_millis(5000));
}

#[cfg(test)]
mod test_play {
    use extendr_api::NA_REAL;

    use crate::decode_symphonia;

    use super::*;
    use std::path::Path;
    
    #[test]
    fn test_play() {
        let fname = "../../test_files/mono.wav";
        let path = Path::new(fname);
        let filetype = Path::extension(path)
            .expect("couldn't extract the file extension")
            .to_str()
            .expect("cannot convert from &OsStr to &str");
        let decoded_arr = decode_symphonia::load(path, false, 0., NA_REAL, filetype);
        let sr = decode_symphonia::get_samplerate(path, filetype);

        play(&decoded_arr.view(), sr);
    }
}
```

**Comment by sorhawell** [comment]
Hi casual user here who perhaps can help. Maybe you can link to a git repository with all the files put together? I tried to recreate your project, but I think there are some unspecified aspects. How does the Cargo.toml file look like? Where are e.g. `to_mono` defined. How does all the R project boilerplate code look like?

For me it helped a lot to start from [https://github.com/extendr/helloextendr](https://github.com/extendr/helloextendr) and slowly build up from there

**Comment by andy-thomason** [comment]
I'm just speculating, but if this problem happens at runtime, you may need to make sure that `/mnt/wd/projects/audior/src/` is in `LD_LIBRARY_PATH`

**Comment by daniellga** [comment]
[This](https://github.com/daniellga/audiotest) simplified repo is supposed to represent the problem.

The problem happens when calling `rextendr::document()` so I assumed it is supposed to be a compilation problem, but I am not sure...

**Comment by Ilia-Kosenkov** [comment]
Hey @daniellga, a great example of extendr usage! The original message suggests that it is a linking issue -- something is missing that contains an implementation of  `snd_pcm_hw_params_get_period_size_min`. 
I downloaded your sample project and tried building it on Windows, and got a ton of linking errors. However, after modifying `Makevars.win` to include two extra libraries, `ole32` and `oleaut32`, I was able to successfully compile your project. I did not test method invocation because I do not know how things suppose to work 😅, but I can confirm the compilation works.

Did you try compiling a similar project without exposing it to R first? That way you can test your linker and dependency resolution.

**Comment by daniellga** [comment]
Hi @Ilia-Kosenkov ! I updated the tests.R file so it makes a simple test to the `play` function. Play an audio directly from a file is the next step in the project.

The only thing I tried before was compiling from rust and running the `play_test` function with cargo test (both cargo build and cargo test work). That test function is supposed to do the same as I am trying to do in R. Do you have any suggestion of what else can I try to do?

May I ask you how did you find it was needed to add ole32 and oleaut32?

**Comment by Ilia-Kosenkov** [comment]
You just google the missing implementations (function names). In the case of Windows, you usually land on the MSDN (because missing functions are usually some system dependencies), and there you immediately see what lib it comes from. Then trial & error :)

**Comment by Ilia-Kosenkov** [comment]
I get this 
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: StreamConfigNotSupported', src\play_audio.rs:44:11
Error in audiotest::play(audio, sr) : play panicked.
```

**Comment by Ilia-Kosenkov** [comment]
However, if I modify your test script like this
```R
# rextendr::document()
# devtools::load_all(".")

audio <- audiotest::load("../../../test_files/mono.wav") # decode audio into R Matrix
sr <- audiotest::get_samplerate("../../../test_files/mono.wav")
audio |>
    vctrs::vec_slice(10000:10010) |>
    print()
sr |> print()
# audiotest::play(audio, sr)
```

I get the following output
```
> source("tests.R")
             [,1]
 [1,]  0.41455078
 [2,]  0.44641113
 [3,]  0.46487427
 [4,]  0.46643066
 [5,]  0.44543457
 [6,]  0.39645386
 [7,]  0.32019043
 [8,]  0.22616577
 [9,]  0.12936401
[10,]  0.04324341
[11,] -0.02490234
[1] 44100
>
```

So I guess the data is read correctly, something wrong with playing.

**Comment by daniellga** [comment]
You are having the same problem when using cargo test? If yes, I think this problem you are having is probably windows related. On Linux I am managing to play the sound with cargo test. I will see on windows what I can do to fix this.

**Comment by Ilia-Kosenkov** [comment]
Oh, I did not test it using cargo, I did it from R :) I was more interested in how it interacts with R session. 
Actually, it also fails to play in testing
```
running 1 test
test play_audio::test_play::test_play ... FAILED

failures:

---- play_audio::test_play::test_play stdout ----
[[0.0, 0.0, 0.0, 0.0, 0.0, ..., -9.1552734375e-5, -6.103515625e-5, -3.0517578125e-5, 0.0, 3.0517578125e-5]], shape=[1, 294909], strides=[294909, 1], layout=CFcf (0xf), const ndim=2
44100
thread 'play_audio::test_play::test_play' panicked at 'called `Result::unwrap()` on an `Err` value: StreamConfigNotSupported', src\play_audio.rs:44:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    play_audio::test_play::test_play

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s
```

**Comment by sorhawell** [comment]
I managed to run the test and heard an evil laughter :)

Im seeing same error as @Ilia-Kosenkov

**Comment by Ilia-Kosenkov** [comment]
Same, I jumped off my chair because it went over the audio of a film I was watching. Now trying to run it directly from R.

**Comment by sorhawell** [comment]
copying the full test straight into a function and export that to R does work

**Comment by Ilia-Kosenkov** [comment]
Can't make it work from R session though, I guess there is some issue with the configuration of audio devices. I am not experienced enough in audio.

**Comment by sorhawell** [comment]
Me niether :) I still got the same error as you many times. I just fiddled and got lucky.

[https://github.com/sorhawell/audiotest/blob/main/tests/tests.R](https://github.com/sorhawell/audiotest/blob/main/tests/tests.R)

I guess the issue was but not entirely sure yet:
I notice the test is run in the play_audio submodule that does import/use some Traits and stuff which is not in lib.rs
Also proposed R functions are not doing exactly the same as the test, maybe there is something different.

**Comment by sorhawell** [comment]
There was something about the back and forth conversion in to R matrix and back. It is not exactly the same which comes back it seems. I avoided the problem by wrapping the original array object tuple struct, which is granted not super practical. But it works because it is guaranteed to be exactly the same type.

@daniellga  I guess you just have to look into making those conversions type-wise exactly reversible and it should work. Maybe sprinkle a clone here and there because we cannot take ownership of objects from the R side.


[https://github.com/sorhawell/audiotest/blob/main/tests/tests.R](https://github.com/sorhawell/audiotest/blob/main/tests/tests.R)
```
rextendr::document()
#devtools::load_all(".")

audiotest:::test_in_R()


ArrayBase = audiotest:::load2("./test_files/mono.wav", mono = TRUE, offset = 0.0, duration = NA_real_) # decode audio into R Matrix
ArrayBase$print()

> imma arraaaayy argh 
 [[0.0, 0.0, 0.0, 0.0, 0.0, ..., -9.1552734375e-5, -6.103515625e-5, -3.0517578125e-5, 0.0, 3.0517578125e-5]], shape=[1, 294909], strides=[294909, 1], layout=CFcf (0xf), const ndim=2

sr = audiotest::get_samplerate("./test_files/mono.wav")
audiotest:::play2(ArrayBase,sr)
```

"muhahahaha"

**Comment by daniellga** [comment]
> 

Unfortunately I am getting the same error with your repo...
```
Error in dyn.load(library_path) : 
  unable to load shared object '/mnt/wd/projects/audiotest/src/audiotest.so':
  /mnt/wd/projects/audiotest/src/audiotest.so: undefined symbol: snd_pcm_hw_params_get_period_size_min
```

**Comment by sorhawell** [comment]
Maybe start compile helloextendr and stepwise add features until it fails.

**Comment by daniellga** [comment]
I tried on windows and after adding some libraries it worked from R. Since it appears to be an OS related thing, I am gonna close this issue. Please feel free to reopen if you find a solution to my problem. Thank you all!
