### ISSUE TITLE
robj::try_into() fails for Result<ExternalPtr<MyStruct>> where MyStruct derived with #[extendr]

### ISSUE THREAD

**Issue by sorhawell** [extendr/extendr#431]
Dear extendries 

[I get an error which comes from this check](https://github.com/extendr/extendr/blob/72fa959d78d318f202f5fca0956defcf821c2740/extendr-api/src/wrapper/externalptr.rs#L161)

```running 1 test
test tests::it_works ... FAILED

failures:

---- tests::it_works stdout ----
[src/lib.rs:38] &robj = ExternalPtr.set_class(["MyStruct"]
thread 'tests::it_works' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedExternalPtrType(ExternalPtr.set_class(["MyStruct"], "helloextendr::MyStruct")', src/lib.rs:16:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I try to convert Robj to MyStruct but it seems to fail because ptr tag is 'MyStruct' and typename is "helloextendr::MyStruct"
robj::try_into() fails for Result<ExternalPtr<MyStruct>>.

[the unit test only covers a trivial type not a user-defined #[extendr]-exported struct](https://github.com/extendr/extendr/blob/60f232f0379777cc864de0851d456706456d1845/extendr-api/tests/externalptr_test.rs#L4)

all the best

[lib.rs](https://github.com/sorhawell/externalpointer/blob/main/src/rust/src/lib.rs)
[tests.R](https://github.com/sorhawell/externalpointer/blob/main/tests/testthat/test-MyStruct.R)
```rust
use extendr_api::prelude::*;

#[derive(Debug, Clone)]
#[extendr]
struct MyStruct(String); //could be any type

#[extendr]
impl MyStruct {
    pub fn new() -> Self {
        MyStruct("applepie".into())
    }

    //restore_from_robj must take Robj, not MyStruct as input
    pub fn restore_from_robj(robj: Robj) -> Self {
        let res: Result<ExternalPtr<MyStruct>> = robj.try_into(); // this fails
        let x = res.unwrap().0.clone();
        MyStruct(x)
    }
}

// Macro to generate exports.
extendr_module! {
    mod helloextendr;
    impl MyStruct;
}

#[cfg(test)]
mod tests {
    use super::*;
    use extendr_api::prelude::extendr_engine::{end_r, start_r};

    #[test]

    //build and install package to access it from rust side
    fn it_works() {
        start_r();
        let robj = R!("helloextendr:::MyStruct$new()").unwrap();
        dbg!(&robj);
        let mystruct = MyStruct::restore_from_robj(robj);
        assert_eq!(mystruct.0, "applpie".to_string());
        end_r();
    }
}
```

**Comment by Ilia-Kosenkov** [comment]
This indeed looks like an issue. I guess it arises here https://github.com/extendr/extendr/blob/27c781ed12a9269cd56d8bffbca47e89b2dd39ce/extendr-api/src/wrapper/externalptr.rs#L161-L165
Let me see if we can fix it easily

**Comment by Ilia-Kosenkov** [comment]
So, one potential solution for in-package usage is relying on `R_PACKAGE_NAME` env var, which should resolve to the package name if running in the package. Then we can test `tag` against `type_name`, `package_name::type_name` and `package_name:::type_name`. A 0th approximation to solving the problem.

**Comment by Ilia-Kosenkov** [comment]
I tried implementing a quick fix, but the problem is slightly more complex than I anticipated. I need to do a little bit more research.

**Comment by sorhawell** [comment]
I might have another quickfix I was concidering to try out. If given that no two exported structs can have the same name, then the R side class name without library is always unambigiguous. On rust side the typename is prefixed with crate and any path submodules in it as `mycrate::mymod::mysubmod::mystruct'. How about just keeping only the right most typename in the conparison?
On R side there is no footguns. On rust side there could be two 'mystructs' defined in different modules. The developer could accidentally export one mystruct to R, and converting Robj into the other mystruct. Therefore this conversion would be unsafe, but the required invariant would be straight forward to satisfy and any failure to do so would likely fail hard any unit test. So still a useful  sane tool for a developer.
try_into() or an equivalent function would be marked unsafe. And the read-before-use text would say: "make sure it is actually the same struct/type in rust code." .

Maybe I'm completely wrong, I guess I will find out :)

**Comment by Ilia-Kosenkov** [comment]
Sounds reasonable. However, what I think I encountered in your particular case is that we cannot rely on `Any` to determine type in different libs. Need to think about it and ask around :)

**Comment by sorhawell** [comment]
Maybe it will always be a very deep rabbit hole to produce an Robj-tag, that can proove the ExternalPointer is pointing to the exact correct struct. Likely the tag should take into account type-name, type-path, crate version, binary-hash, de/serialization and any malicious injections.

[I have made a quick fix that works in any normal case:](https://github.com/extendr/extendr/compare/master...sorhawell:extendr:extpointer)

[Here is a test ](https://github.com/sorhawell/externalpointer/blob/0c31c0839c3c1679657e93a1c48d9d72903aaaf5/src/rust/src/lib.rs#L70)where works for any types of the same name `get_back_the_right_struct` or the wrong name `try_the_wrong_struct - should panic`.
It does fail for a type of same name, but defined in another module: `try_the_worst_case_module`.

see test below.

I suggest making an unsafe function which can be used by a developer which both controls the R side and rust side. The safety to abide to is : "Do not downcast to the wrong struct by the same name."

```
rust % cargo test
   Compiling helloextendr v0.2.0 (/Users/sorenwelling/Documents/projs/externalpointer/src/rust)
    Finished test [unoptimized + debuginfo] target(s) in 0.64s
     Running unittests src/lib.rs (target/debug/deps/helloextendr-f9295376b626ce24)

running 3 tests
Error: object 'SomethingElse' not found
test tests::try_the_wrong_struct - should panic ... ok
test tests::get_back_the_right_struct ... ok
test tests::try_the_worst_case_module - should panic ... FAILED

failures:

---- tests::try_the_worst_case_module stdout ----
[src/lib.rs:104] &robj = ExternalPtr.set_class(["MyStruct"]
mystruct is NOT 42 yikes, it is: MyStruct(670098352)
note: test did not panic as expected

failures:
    tests::try_the_worst_case_module

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.21s
```

**Comment by Ilia-Kosenkov** [comment]
I see your point. The problem here is that we are providing an API to others and thus we have to be very precise about type conversion. 
We might consider two things here:
- indeed provide an unsafe function that will behave as, basically, `reinterpret_cast<>()` or something similar -- take the pointer and cast it to whatever you *belive* is correct, no guarantees;
- update current implementation to provide partial safety -- we can notify the user whether we were able to match the type
  -  *fully* (incl namespaces/crates)
  -  *partially* (we matched struct name but not the full qualification,  your case), so treat it carefully
  - *no match* -- equivalent to `Err()` case in the current implementation

- improve tag generation by embedding more metadata -- perhaps information about the type shape & size. That way we can allow reinterpreting the pointer to any type of the same shape and size

I do not have a lot of free time right now, but this thing is top-1 priority for me. Let me do some more research and I'll get back to you.

**Comment by sorhawell** [comment]
currently I use the Rpackage xptr to extract the pointer as a string (due to no u64 type) and then [this generic](https://github.com/sorhawell/minipolars/blob/7bb361aa5a94a8aa9284ab0d6e444e199db84553/src/rust/src/utils/wrappers.rs#L40) to reinterpret which works good enough for me.

```
pub unsafe fn strpointer_to_<T>(raw: &str) -> extendr_api::Result<&mut T> {
    let without_prefix = raw.trim_start_matches("0x");
    let z = usize::from_str_radix(without_prefix, 16)
        .map_err(|e| extendr_api::Error::Other(e.to_string()))?;

    //unsafe {
    let y = &mut *(z as *mut T);
    return Ok(y);
    //};
}
```

**Comment by Ilia-Kosenkov** [comment]
Ok so the root cause of the issue is simple (I don't know why I missed that!). Basically, you perform two incompatible operations (as of now). 
When you try to reconstruct an object from external ptr, you get into the `TryFrom<Robj> for ExtPtr<T>`, and here the type name is full because we use `std::any`. https://github.com/extendr/extendr/blob/72fa959d78d318f202f5fca0956defcf821c2740/extendr-api/src/wrapper/externalptr.rs#L151-L168

However, when you simply return a struct from `$new()` as `Self`, it gets converted to externalptr in a different place, leaving only the type name for `S3` compatibility.
https://github.com/extendr/extendr/blob/02d2150df4a986b65f3fb5851fe255072db1c585/extendr-macros/src/extendr_impl.rs#L137-L161

**Comment by Ilia-Kosenkov** [comment]
And I think I can fix this without breaking anything. Stay tuned.

**Comment by Ilia-Kosenkov** [comment]
Hey @sorhawell , can you try my branch https://github.com/Ilia-Kosenkov/extendr/tree/fix/externalptr in your use case? Does it solve your problem?

**Comment by sorhawell** [comment]
it seems I get the original error

`Err(
    ExpectedExternalPtrType(
        ExternalPtr.set_class(["MyStruct"],
        "helloextendr::MyStruct",
    ),
)`

[The issue is the same as in the beginning](https://github.com/Ilia-Kosenkov/extendr/blob/45e0bb11c8dcf4a1ee19d6d8e28a07044eb6f3c0/extendr-api/src/robj/rinternals.rs#L413)

``` fn check_external_ptr_type<T>(&self) -> bool {
        ...
        ///this line is still comparing type_name_only-tag with a path+type_name
            if tag.as_str() == Some(std::any::type_name::<T>()) {
         
      ...
    }```

**Comment by Ilia-Kosenkov** [comment]
Tags now are created with the correct type name. It is strange as I ran your test project against my branch and it worked. I also added a test to re-create your scenario. Can you check the PR?

**Comment by sorhawell** [comment]
I did not manage to make my cargo tests work. Not sure why, maybe it does not matter.
However running your tests works, and they seem reasonable.
But most importantly (to me) plugging the new ExternalPtr in my project works as is and passes all my tests.

**Comment by Ilia-Kosenkov** [comment]
Ah, so there is some progress! I'll check if I can reproduce the error on your test library. If you can think of another test case worth adding to the repo, let me know.

**Comment by Ilia-Kosenkov** [comment]
Your rust tests won't work, I get these errors: 
![image](https://user-images.githubusercontent.com/8782986/190458234-4a30e031-856a-4152-9989-9f26a88eb532.png)
The reason is your R session knows nothing about the package `{helloextendr}` and your `#[should_panic]` is triggered in the wrong place - at `R!();`

You can probably trick it into actually loading local package with something like `R1("pkgload::load_all(...)")`.

**Comment by sorhawell** [comment]
Oh I forgot. There is comment somewhere about it in the test. I built the package manually to perform the cargo test wit r_engine() a week ago. But I have likely not updated the manual build so I was testing against an old version.

**Comment by sorhawell** [comment]
cargo tests were alright, just needed to build package fully and not use rextendr::document().

@Ilia-Kosenkov 
> If you can think of another test case worth adding to the repo, let me know
I can rewrite the two other cargo tests into R tests as a fork of your PR next week.

**Comment by sorhawell** [comment]
@Ilia-Kosenkov 
I would like to write a test where the struct name is correct but submodule/path i wrong. The 'right'-thing of the extendr_api is to return an Err-value. How would we test that via "testthat" when extendr_api currently panics when returning Err-value to R. My personal solution to expose result-types in R is this simple generic (there is also a version no requiring Debug trait).

```
pub fn r_result_list<T, E>(x: Result<T, E>) -> extendr_api::prelude::list::List
where
    T: std::fmt::Debug + IntoRobj,
    E: std::fmt::Debug + std::fmt::Display,
{
    if x.is_ok() {
        extendr_api::prelude::list!(ok = x.unwrap().into_robj(), err = extendr_api::NULL)
    } else {
        extendr_api::prelude::list!(ok = extendr_api::NULL, err = x.unwrap_err().to_string())
    }
}
```

I know you're prefer to avoid such generic. Would pattern would you like to use to evaluate rust Err-values in R testthat?

**Comment by sorhawell** [comment]
during some casual readings in the extendr macro expansions I learn `try_into` is not the only way to convert "Robj of an ExternalPtr" to the Class of the external ptr.

Such a method was expanded for exported class  (replace Series with AnyClassName)
```
        impl<'a> extendr_api::FromRobj<'a> for &Series {
            fn from_robj(robj: &'a Robj) -> std::result::Result<Self, &'static str> {
                if robj.check_external_ptr("Series") {
                    Ok(unsafe {
                        std::mem::transmute(robj.external_ptr_addr::<Series>())
                    })
                } else {
                    Err("expected Series")
                }
            }
        }
        
 ```
 
[Rust docs suggests to use cast instead of transmute](https://doc.rust-lang.org/std/mem/fn.transmute.html) and that works here...
```

impl Series {
    pub fn inner_from_robj_clone(robj: &Robj) -> std::result::Result<Self, &'static str> {
        if robj.check_external_ptr("Series") {
            let x: Series = unsafe { &mut *robj.external_ptr_addr::<Series>() }.clone();
            Ok(x)
        } else {
            Err("expected Series")
        }
    }
}

   pub fn inner_from_robj_mut(robj: &Robj) -> std::result::Result<&mut Self, &'static str> {
        if robj.check_external_ptr("Series") {
            let x: &mut Series = unsafe { &mut *robj.external_ptr_addr::<Series>() };
            Ok(x)
        } else {
            Err("expected Series")
        }
    }
```

**Comment by sorhawell** [comment]
@Ilia-Kosenkov I think your PR is an improvement. It is though possible already today to reinterpret Robj into 'MyClass'  using above pattern.

**Comment by Ilia-Kosenkov** [comment]
Ok, I have updated the description of my PR. I forgot to ask a teammate for a review, so once someone goes through it, I will merge it. 
Any other changes that you think should be implemented should go as another PR.
