### ISSUE TITLE
#[default = "NULL"] doesn't work in `impl` block

### ISSUE THREAD

**Issue by AlanRace** [extendr/extendr#435]
The use of `#[default = "NULL"] ` in the following example, seems to be ignored. This works fine for individual functions, but not when the function is part of an `impl` block.

```rust
struct Person {
    pub name: String,
}

#[extendr]
impl Person {
    fn new(#[default = "NULL"] name: &str) -> Self {
        Self {
            name: name.to_string(),
        }
    }

    fn set_name(&mut self, name: &str) {
        self.name = name.to_string();
    }

    fn name(&self) -> &str {
        self.name.as_str()
    }
}
```

**Comment by Ilia-Kosenkov** [comment]
Thanks for reporting this, I will verify this later today. It would be nice to see the R wrappers generated for this code.

But note that R's `NULL` is not a valid value for an `&str` -- you need to use `Nullable<T>` for that.
You may also have problems with `NA_character_`, another possible default value for a `character` type. I'd recommend you to experiment with `Rstr`, a dedicated `NA`-aware wrapper type, or with `Nullable<Rstr>` if you want to explicitly allow `NULL`s.

**Comment by AlanRace** [comment]
Yeah I realised that after I posted, I was just trying to put something simple together. In my actual code the function signature is closer to this:

```rust
fn add(
        &mut self,
        name: &str,
        value: i32,
        normalise: bool,
        #[default = "NULL"] constraints: List,
    ) -> Result<bool> {
...
}
```

**Comment by AlanRace** [comment]
And the R wrappers for the `Person` example are as follows:

```R
Person <- new.env(parent = emptyenv())

Person$new <- function(name) .Call(wrap__Person__new, name)

Person$set_name <- function(name) invisible(.Call(wrap__Person__set_name, self, name))

Person$name <- function() .Call(wrap__Person__name, self)
```
And for my real use-case:

```R
Builder$add <- function(name, value, normalise, constraints) .Call(wrap__Builder__add, self, name, value, normalise, constraints)
```

**Comment by Ilia-Kosenkov** [comment]
Yep, there is an issue. To double check, can you put a default attribute on a parameter of a function that is not a part of impl block? You should see your default value in the generated wrappers.

**Comment by AlanRace** [comment]
I did this with the `hello_world` function, and it copied over the default fine (even if as you say above this makes no sense):

```R
#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function(message = NULL) .Call(wrap__hello_world, message)
```

If I manually add in the ` = NULL` to the wrapper (example below), it works as well, so I think the only issue is actually in the writing of the wrapper 

```R
Builder$add <- function(name, value, normalise, constraints = NULL) .Call(wrap__Builder__add, self, name, value, normalise, constraints)
```

**Comment by Ilia-Kosenkov** [comment]
Yep, I just wanted to double check. I'll try to address this as soon as possible, thanks for providing a detailed report!

**Comment by Ilia-Kosenkov** [comment]
Hey @AlanRace, I've made a PR with a fix, feel free to check it out in your scenario before it is merged.
