### ISSUE TITLE
Switch back the Windows toolchain from GNU to MSVC once again

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#437]
(See https://github.com/extendr/rextendr/issues/216 for more context)

## Overview

extendr switched the Windows toolchain from MSVC to GNU when R 4.2 was released. At that time, that was the best choice because we can get free from the headaches of cross-compilation. But, now we have two big news to consider:

1. the CRAN machines now have Rust installed ([ref](https://stat.ethz.ch/pipermail/r-package-devel/2022q4/008638.html))
2. R-univese now supports R-Rust packages without any additional setups (because [the GNU target is now pre-installed on the GHA runner thanks to jeroen](https://github.com/actions/runner-images/pull/6661))

So, while we wanted to avoid the cross-compilation, I think the benefit of using MSVC toolchain is over the pain.

## Feasibility

It was I that actually changed the toolchain on addressing the release of R 4.2. The details can be found at https://github.com/extendr/extendr/issues/396. The actual changes made to each repo are the following pull requests. If you see the diffs, you'll notice there's no changes on Rust code, mainly on the testing infrastructure and on the documents. So, I think it's not difficult to revert the toolchain.

* libR-sys: https://github.com/extendr/libR-sys/pull/103
* extendr: https://github.com/extendr/extendr/pull/376
* rextendr: https://github.com/extendr/rextendr/pull/187
* document about the toolchain setups: https://github.com/extendr/libR-sys/pull/94

### Does the GNU toolchain actually work?

I'll try releasing my string2path package with GNU toolchain on CRAN. Let's see how it goes.

### What were the difficulties of relying on the cross compilation?

The only thing I can remember is that the doc tests don't run on cross-compiling. Were there any big difficulties that we suffered from?

**Comment by yutannihilation** [comment]
@Ilia-Kosenkov 
Please let me know if you have any concern!

**Comment by multimeric** [comment]
Can you please explain the advantages of using the MSVC toolchain? Also, what was the cross compilation that was happening? What target architecture on what compiler architecture? Finally, will the doc tests work now, or will it stop them working?

**Comment by yutannihilation** [comment]
> Can you please explain the advantages of using the MSVC toolchain?

Since it's installed on the CRAN machine and the GHA runners, package authors can release there without providing precompiled binaries like I do.

> what was the cross compilation that was happening? What target architecture on what compiler architecture?

Sorry, I think I don't understand this question. Since the target is GNU, the GNU toolchain doesn't need cross-compile. The MSVC toolchain does. Does this answer to your question?

> will the doc tests work now, or will it stop them working?

It will stop. See https://github.com/extendr/extendr/issues/372

**Comment by yutannihilation** [comment]
I submitted my package to CRAN. I removed the fallback mechanism to the precompiled binary and the toolchain specification. Let's see how it goes...

The actual changes can be found here: https://github.com/yutannihilation/string2path/pull/39

**Comment by yutannihilation** [comment]
Confirmed at least all the existing tests pass either with the MSVC toolchain or with the GNU toolchain.

* extendr: https://github.com/extendr/extendr/pull/439
* rextendr: https://github.com/extendr/rextendr/pull/219

**Comment by Ilia-Kosenkov** [comment]
Looks good, I guess we can drop `gnu` toolchains. The only suggestion I have is to leverage `rust-nightly` and execute doc tests via `-Zdoctest-xcompile` when running on Windows, R-release and rust-nightly.

**Comment by yutannihilation** [comment]
My proposal here was to switch back from, i.e. drop, the GNU toolchain. But, as it turned out the current code works fine with both toolchains, I feel just removing the `+(toolchain)` specification in our `Makevars.win` template is enough. I mean, the guidance to the users will be something like:

* On R >= 4.2, the MSVC toolchain is recommended (because we mainly use it for our development), but the GNU toolchain should also work.
* On R < 4.2, only the MSVC toolchain can be used in order to compile 32-bit target.

**Comment by yutannihilation** [comment]
I think this pull request to update helloextendr is the last thing to close this issue. Anything I'm missing?

https://github.com/extendr/helloextendr/pull/16
