### ISSUE TITLE
Rtools43

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#442]
https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html

**Comment by Ilia-Kosenkov** [comment]
Running R 4.2.2 with rtools43 locally -- a lot of tests fail/crash, as if there is some ABI incompatibility. I guess it should be paired with R 4.3.x

**Comment by yutannihilation** [comment]
Yes, as the website says

> intended for R 4.3.0.

**Comment by yutannihilation** [comment]
Now it's supported by r-lib/actions, and R >= 4.3 now uses Rtools43 by default.

https://github.com/r-lib/actions/commit/740a0e7ce930b6357f16388c0b2acee8337adb01
