### ISSUE TITLE
Compiled Rust library contains symbols R doesn't like

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#46]
I have been trying to build an R package that can pass `R CMD check`: https://github.com/clauswilke/helloextendr

This doesn't currently work, because the compiled Rust library contains symbols that R doesn't like:

```
* checking compiled code ... NOTE
File ‘helloextendr/libs/helloextendr.so’:
  Found non-API calls to R: ‘R_CStackLimit’, ‘R_CleanTempDir’,
    ‘R_RunExitFinalizers’, ‘Rf_initialize_R’, ‘setup_Rmainloop’

Compiled code should not call non-API entry points in R.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```

I believe these are all functions that are needed to create a Rust binary calling R as a library. So we may need to take these out and put them into a separate crate, maybe called `extendr-standalone` or `extendr-bin`. Unfortunately we need these calls to run `cargo test`, so the tests would have to import that crate I assume.

**Comment by lebensterben** [comment]
There is no need to call any of these functions. They are not in public API and not meant to be called.

**Comment by clauswilke** [comment]
They're needed in the engine, which is needed to call R functions from a stand-alone Rust program:
https://github.com/extendr/extendr/blob/83857eccee8b0631022e5cb0eb8c6f35d78dbf38/extendr-api/src/engine.rs#L42-L73

Again, we have to distinguish between two use cases, an R package calling Rust and a Rust binary calling R.

**Comment by lebensterben** [comment]
That's right.
But the thing is, what's a possible use case for a Rust library that also functions as "a Rust binary calling R"

**Comment by lebensterben** [comment]
The sole purpose of "extendr" is to allow easy interop between R and Rust via R's C interface, so that we can write Rust code which acts as a library/package used by R.

A standalone Rusr binary which uses R for certain functionalities just seems irrelevant. After all it's "extendr" instead of "extendrust"

**Comment by clauswilke** [comment]
I disagree. At a minimum, you need this feature to be able to write Rust test code that you can run with `cargo test`. It's actually something I've run into with my [sinab](https://github.com/clauswilke/sinab) package. I had to stop writing meaningful unit tests because they all started depending on R api calls that I couldn't make from a standalone Rust binary. And then the only way to unit test is to write exported Rust functions that you can call from R and that mimic the Rust testing environment, and that's a huge overhead and annoyance.

**Comment by clauswilke** [comment]
In any case, the more I think about this the more a standalone crate for this particular functionality sounds good to me. Then people can use it when they need to and ignore otherwise. Maybe `extendr-engine` is the right name?

**Comment by lebensterben** [comment]
well, you're right for the testing and I haven't thought about this part. For my limited experience with R-Rust interop, I strictly limit the Rust side s.t. it solely acts as a native library that acts on native types. So it doesn't call foreign functions at all.

So the architecture I'm proposing is:

- A low-level binding layer
    - For Rust programs calling R, we have libR-sys
    - For R calling Rust library, we have extendr-macro that generates bindings
- A high-level translation layer
    - Turns a R data type to a wrapper type, which provides idiomatic interface for Rust developers. This is what I think extendr should do. And this should solely works on Rust side without crossing the FFI boundary.
    - For the other direction that making Rust data type usable to R, I don't is feasible.

**Comment by lebensterben** [comment]
For testing a R package written in Rust:

Crossing FFI boundary itself is "unsafe" in Rust terminology, and generally not "safe" in its literal meaning. Layering reduces the needs for such actions.

If a particular Rust function can be tested without invoking R FFI, it's preferred to not doing that at all. FFI just adds much more complications for debugging.

If something must invoke R FFI, say it has to call R to initialise certain R data, we may need to develop some testing frameworks. Instead of having a Rust test module calling R and then comes back to Rust side to finish the tests, it's probably easier to have a R program to initialise data and calls Rust.

**Comment by dasmoth** [comment]
Beyond testing, another reason you might want to call start_r in a Rust program would be to use some R libraries which don't have natural Rust equivalents.  Along the same lines as https://www.tweag.io/blog/2017-07-10-haskell-r-best-both-worlds/

**Comment by clauswilke** [comment]
A general principle of software engineering I've learned over the years is to not dismiss other people's use cases, even if they seem strange or incorrect to you. There's usually some other perspective that we haven't fully appreciated or thought through. If people want to call R from Rust standalone binaries, and if it's technically possible to do so, we should provide this feature, as long as it doesn't interfere with use cases that don't require it. Moving the engine into a separate crate accomplishes this, as far as I can see.

**Comment by lebensterben** [comment]
>Beyond testing, another reason you might want to call start_r in a Rust program would be to use some R libraries which don't have natural Rust equivalents.  Along the same lines as https://www.tweag.io/blog/2017-07-10-haskell-r-best-both-worlds/

@dasmoth I've thought about this possibility. But many good R package usually are implemented in C or C++. So in many cases it's easier to call those libraries from Rust, without the indirection of going through R.

**Comment by clauswilke** [comment]
I have created a PR (#50) that separates out the extendr engine from the extendr api.
