### ISSUE TITLE
Document how to create a new matrix

### ISSUE THREAD

**Issue by JosiahParry** [extendr/extendr#463]
At present there is no documentation that indicates how one can create a matrix. The example here is not clear. 

This request is for documentation and examples for how to make an extendr matrix. At present, matrices seem to be the most challenging extendr object to work with. 

https://github.com/extendr/extendr/blob/bae73e70ffa75f29c5e87719a66614134414a8cd/extendr-api/src/wrapper/matrix.rs#L7

**Comment by multimeric** [comment]
Can you elaborate on the way in which you think it's unclear? Is it just the lack of documentation for `new_matrix` that explains the `f` function?

**Comment by JosiahParry** [comment]
I think that is definitely the biggest hurdle. The use of the closures also feels odd and somewhat confusing—e.g. how do i really know if I'm getting the data input column or row order?

When using the creation function for the first time I had hoped for something similar to [ndarray::zeros](https://docs.rs/ndarray/0.3.0/ndarray/fn.zeros.html) that was there could be an "empty" matrix that can be filled iteratively. 

There also was no `From` implementation for a `Doubles ` or `Vec<Vec<f64>>` which I thought to be a natural thing to have.

**Comment by daniellga** [comment]
Hi!
I am not following... You want to know if the input data is of column or row order... What type is it you are trying to convert from? Because in R matrices are column order while in ndarray the default is row order afaik. You would have to know the memory layout of the element you are working with since I think `new_matrix` flattens the input.
I don't think it's possible to create a `From` implementation for Doubles because it would not be possible to pass the number of rows or columns as arguments.
`Vec<Vec<T>>>` is not an efficient structure to work with. I think extendr should not support it but instead encourage the use of the ndarray interface so you can use [ndarray::zeros](https://docs.rs/ndarray/0.3.0/ndarray/fn.zeros.html) and convert directly to an `RMatrix`.
The `new_matrix` implementation is actually simple, but I agree it really lacks documentation, specially examples.

**Comment by multimeric** [comment]
> how do i really know if I'm getting the data input column or row order?

`new_matrix` currently creates the input data one column at a time (ie, `(0, 0)` followed by `(0, 1)` followed by `(1, 0)`. I'm surprised that this matters but I'll include it in the documentation anyway.

> When using the creation function for the first time I had hoped for something similar to [ndarray::zeros](https://docs.rs/ndarray/0.3.0/ndarray/fn.zeros.html) that was there could be an "empty" matrix that can be filled iteratively.

I am firstly hesitant to rewrite functionality that already exists in `ndarray`. Also I think probably the best thing `extendr` can do here is encourage users to create matricies in the more idiomatic Rust way, which is by collecting iterables. I think it's rare that you truly need to start with an empty matrix. Which brings me to...

> There also was no From implementation for a Doubles  or Vec<Vec<f64>> which I thought to be a natural thing to have.

As mentioned, this doesn't make much sense to use as `From`, but I'm envisating that we could have `fn collect_rmatrix(&self, by_row: bool, n_row: usize)`. So you can then `[1, 2, 3, 4].collect_rmatrix(true, 2)`. This would be both idiomatic Rust and more user friendly than it is now.

**Comment by JosiahParry** [comment]
I don't _want to know_ the order. My meaning is that it is not as straightforward to determine if something is column major or row major using the closure interface. It does not matter that `new_matrix()` creates data one column at a time. But it important to know, as a user, if your data is being input row or column order. 


Collecting from an interable would be a nice thing to have. Here is an example of creating a euclidean distance matrix from mismatched sized Doubles.

```rust
#[extendr]
fn dbls_to_mat(x: Doubles, y: Doubles) -> RMatrix<f64> {
    let nr = x.len();
    let nc = y.len();

    let res_vec: Vec<Vec<f64>> = x.into_iter()
        .map(|x| y.into_iter()
            .map(|y|  (x - *y).0.powi(2).sqrt())
            .collect::<Vec<f64>>())
         .collect();

    RMatrix::new_matrix(
        nr, nc,
        | r, c | res_vec[r][c]
    )
}
```

Approaches like this are quite common for nested calculations I'd think. 

Using @multimeric's suggested `collect_rmatrix()` could be nice for `Vec<f64>` (RMatrix<Rfloat> doesn't work from my experience).

> I think this works below.. but you get the idea 

```rust
#[extendr]
fn dbls_to_mat(x: Doubles, y: Doubles) -> RMatrix<f64> {
    let nr = x.len();
    let nc = y.len();

    let res: RMatrix<f64> = x.into_iter()
        .flat_map(|x| y.into_iter()
            .map(|y|  (x - *y).0.powi(2).sqrt())
            .collect::<Vec<f64>>())
         .collect_rmatrix(by_row: true, n_row: nr, n_col: nc);
    res
}
```

**Comment by daniellga** [comment]
I think I would do something like this (I don't even know if it works, can't run rust where I am...):
```
#[extendr]
fn dbls_to_mat(x: Doubles, y: Doubles) -> RMatrix<f64> {
    let nr = x.len();
    let nc = y.len();

    RMatrix::new_matrix(
        nr, nc,
        | r, c | ((x[r] - y[c]).0).powi(2).sqrt()
    )
}
```
I think you just need to adjust r and c to make the matrix you want.
In this case the columns of the matrix would vary the y index. For example the first column of the matrix would have all the y distances compared to x[0].

**Comment by multimeric** [comment]
> I don't want to know the order. My meaning is that it is not as straightforward to determine if something is column major or row major using the closure interface. It does not matter that new_matrix() creates data one column at a time. But it important to know, as a user, if your data is being input row or column order.

I'm afraid I don't understand this distinction you're making. R's matrices are always stored in column major order. And the insertion order is column by column. What else are you after? Can you give an example?

**Comment by JosiahParry** [comment]
The insertion order is not always in column order. Here are som examples. 

``` r
x <- 1:9

# simple example
matrix(x, ncol = 3)
#>      [,1] [,2] [,3]
#> [1,]    1    4    7
#> [2,]    2    5    8
#> [3,]    3    6    9
matrix(x, ncol = 3, byrow = TRUE)
#>      [,1] [,2] [,3]
#> [1,]    1    2    3
#> [2,]    4    5    6
#> [3,]    7    8    9

# another example where using a for loop
m <- matrix(ncol = 3, nrow = 3)
for (i in 1:3) {
  m[i,] <- 1:3 * i
}

# see interior of listw2mat for a real world example
spdep::listw2mat
#> function (listw) 
#> {
#>     n <- length(listw$neighbours)
#>     if (n < 1) 
#>         stop("non-positive number of entities")
#>     cardnb <- card(listw$neighbours)
#>     if (any(is.na(unlist(listw$weights)))) 
#>         stop("NAs in general weights list")
#>     res <- matrix(0, nrow = n, ncol = n)
#>     for (i in 1:n) if (cardnb[i] > 0) 
#>         res[i, listw$neighbours[[i]]] <- listw$weights[[i]]
#>     if (!is.null(attr(listw, "region.id"))) 
#>         row.names(res) <- attr(listw, "region.id")
#>     res
#> }
#> <bytecode: 0x10d961d60>
#> <environment: namespace:spdep>
```

<sup>Created on 2023-01-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by multimeric** [comment]
To be clear, I meant:

> R's matrices are always stored in column major order. And the insertion order via **`new_matrix` in Rust** is column by column.

I understand that `R` has a `byrow` parameter. I still don't understand what you want here.

**Comment by JosiahParry** [comment]
> This request is for documentation and examples for how to make an extendr matrix. 

This issue is for better documentation on creating and filling an RMatrix. All other discussion is ancillary. 

The additional point is that using a closure to fill the matrix feels weird.

**Comment by daniellga** [comment]
The column order refer to the memory layout. Even though you insert in row order using byrow = TRUE. The matrix will be column major because the elements will be arranged contiguously in column order.
Also be aware that the ways you wrote dlbs_to_mat you are doing some unecessary allocations when you collect to a vec.
