### ISSUE TITLE
Differences between start_r in libR-sys and extendr-api

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#47]
I'm noticing some differences in the testing code in `libR-sys` and the deployed code in `extendr-api` when it comes to starting an R process. In particular:
https://github.com/extendr/libR-sys/blob/b141c83c9e4b7329253e4025182b87c54f69ea7e/src/lib.rs#L80-L88
vs:
https://github.com/extendr/extendr/blob/52270205e017dbcd27c829ce5998678e59210975/extendr-api/src/engine.rs#L64-L70

@CGMossa Could this cause some of the trouble you have compiling on Windows?

There's also this difference:
https://github.com/extendr/libR-sys/blob/b141c83c9e4b7329253e4025182b87c54f69ea7e/src/lib.rs#L78
vs:
https://github.com/extendr/extendr/blob/52270205e017dbcd27c829ce5998678e59210975/extendr-api/src/engine.rs#L59-L62

**Comment by jbabyhacker** [comment]
Regarding the stack limit. I believe this has to be set to a lower number and cannot be unlimited when compiling on windows.

**Comment by clauswilke** [comment]
This has been addressed in libR-sys: https://github.com/extendr/libR-sys/commit/76e46a754b82cdabfe77d027f5ac22390b871f08
