### ISSUE TITLE
Parsing errors with `R!`

### ISSUE THREAD

**Issue by CGMossa** [extendr/extendr#472]
I'm getting an abnormal amount of `ParseError` from `R!`.
This is the least controversial one:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(["\"\n        tmp <- tibble::as_tibble({{locs.clone()}})\n        \n        names(tmp) <- c(\"centroid\n\",\"id_farm \")\n        tmp\n    \""])', src\wild_boar_graph_model.rs:57:8
```

```rust
    let locs2 = R!("
        tmp <- tibble::as_tibble({{locs.clone()}})
        
        names(tmp) <- c("centroid","id_farm")
        tmp
    ").unwrap();
```

Also, `tibble::rowid_to_column` had issues, and `dplyr::rename` also gave parsing issues.
Not to exclude `%>%`.

**Comment by multimeric** [comment]
Does this relate to the fact that you're using double quotes inside double quotes? Maybe try a raw string literal `r#"..."#`?

**Comment by CGMossa** [comment]
Great point. I'll close this for now.
