### ISSUE TITLE
Remove CanBeNA for &str

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#483]
(I originally commented here: https://github.com/extendr/extendr/pull/477#issuecomment-1423452814)

I think the current implementation of `CanBeNA` for `&str` is broken. The intention of the following lines is that `&[b'N', b'A']` is on a different address from the regular "NA" string, but I'm afraid this is not guaranteed.

https://github.com/extendr/extendr/blob/974cddc4ee5a4c3ab10e8bf85772b74c0a182f32/extendr-api/src/na.rs#L50-L59

For example, this fails on Rust Playground (while it doesn't on my local Windows).

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0cd54f21fd4e30e94203942ef385e846

I might be wrong, but, as I don't see any possible fix on this, I now think we should remove `CanBeNA` for `&str`.

**Comment by multimeric** [comment]
Could we compare the pointer to the current R process's address of `NA_character_` instead? I guess it's not surprising that doing this comparison inside Rust is implementation specific.

**Comment by yutannihilation** [comment]
We can compare, but we cannot treat `R_NaString` (i.e., `NA_character_`) as a Rust string, because it's a C string.

**Comment by yutannihilation** [comment]
I withdrew #484 for now as it turned out a bit complex than I expected, and it seems manually allocating the string works.

https://github.com/extendr/extendr/pull/477/files#diff-4c22ae4d92a14ac236bff533c4ed348f50e9d70a1984e6ec1b9b2ac0cd48fda0

**Comment by multimeric** [comment]
I don't get this. Aren't we supposed to be checking against R's specific `NA_character_ address? How does allocating a new one ourselves help identify NA strings?

**Comment by yutannihilation** [comment]
`<&str>::na()` needs to return `&str` while `R_NaString` is a SEXP. Are you suggesting to use `R_CHAR(R_NaString)`? If so, I tried it, but for some reason I couldn't make it work (got `STATUS_ACCESS_VIOLATION` error).

> How does allocating a new one ourselves help identify NA strings?

We need a pointer that can be used as a sentinel value and is at the same time a valid `&str`. It seems this can be only achieved by manual allocation.

**Comment by yutannihilation** [comment]
> Aren't we supposed to be checking against R's specific `NA_character_` address? 

Sorry, I didn't answer to your question directly. In short, no. That's not how CanBeNA for &str works (and this trickiness is the very reason I wanted to get rid of this).

**Comment by multimeric** [comment]
So it's just an internal (in Rust only) sentinel that we use to represent NAs?

**Comment by yutannihilation** [comment]
Yes.

**Comment by yutannihilation** [comment]
> I tried it, but for some reason I couldn't make it work (got `STATUS_ACCESS_VIOLATION` error).

Specifically, I tried this.

``` rust
lazy_static! {
    static ref EXTENDR_NA_STRING: &'static str = unsafe {
        let ptr = R_CHAR(R_NaString) as *const u8;

        let v: &[u8] = std::slice::from_raw_parts(ptr, Rf_xlength(R_NaString) as usize);

        std::str::from_utf8_unchecked(v)
    };
}
```

It seems I don't hit the error as long as I test it with ` --test-threads=1`. This probably means the C string underlying `R_NaString` can be freed while Rust side still needs it. I guess this should never happen when we use extendr from R sessions, but this does matter just because extendr can be used outside of R packages. That's probably why extendr needed the internal sentinel value. Nowadays I'm getting to find this kind of limitation really frustrating.

**Comment by yutannihilation** [comment]
Let's close this for now.
