### ISSUE TITLE
Support List ALTREP (R 4.3)

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#503]
As `VECSXP` will be supported on R 4.3. I think this is mostly for consistency and not something that needs to be done in a hurry.

https://github.com/r-devel/r-svn/commit/96b4528daaaec5ad68843d4c20091151acb0cb02

**Comment by JosiahParry** [comment]
I am encountering this presently. I would love to be able to represent a single struct as a list vector in R. To do so I would utilize the ALTLIST altrep. However this is not implemented yet in extendr. 

See motivating repo [here](https://github.com/JosiahParry/vctrsrs)

**Comment by yutannihilation** [comment]
Oh, good to know the real use case, thanks. Please feel free to implement this. I guess it won't be very difficult.
