### ISSUE TITLE
Guide for pre-compiling binaries using GitHub Action CI

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#51]
(Sorry if this isn't the right place to ask)

As probably you already notice, the installation instruction is a bit complicated to users who just use a package that uses extendr, especially if they are on Windows.

https://github.com/extendr/libR-sys#installation

My experimental package prepares pre-compiled binaries for Windows so that the user can avoid compilation on their local.

c.f. "Precompiled binary for Windows" section of https://yutani.rbind.io/post/some-more-notes-about-using-rust-code-in-r-packages/

This is what [rwinlib](https://github.com/rwinlib) does for many C/C++ packages. I don't find any elegant way of doing this, but I think it's important to provide some easy way to install from GitHub in order for a pre-CRAN package to get used by ordinary R users. So, it's nice if you provide some guidance of how to setup GitHub Actions CI for this.

**Comment by clauswilke** [comment]
Definitely a valid question, but a bit too early. As of today we cannot reliably build packages on Windows (in particular 32-bit variants, see here: https://github.com/extendr/libR-sys/issues/9) and we also can't pass the R check without any notes (see e.g. here: https://github.com/clauswilke/helloextendr/runs/1466322075, look at the check output). Once we have resolved these issues we can start thinking about pre-building binaries.

If you want to follow the ongoing conversations, also check out the discord channel here: https://discord.gg/7hmApuc

**Comment by clauswilke** [comment]
If you would like to help, we need setup or improve github actions on the following repos:
https://github.com/extendr/libR-sys
https://github.com/extendr/extendr
https://github.com/extendr/rextendr
https://github.com/clauswilke/helloextendr

At a minimum, all should be tested at least once on each major OS and at least once on R release and R devel and on Rust stable and Rust nightly (we don't need all possible combinations, just like with ggplot2 we test R devel only for Ubuntu).

**Comment by yutannihilation** [comment]
> but a bit too early.

Oh, I see. Thanks for sharing the current status! I joined the discord (though my English typing skill is not enough for chatting fluently...)
