### ISSUE TITLE
GH Pages: Default pages return 404

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#510]
The default deployment of gh pages deploys sites to something like `https://<organization>.github.io/<repository>/`. 
There is also an option to host `https://<organization>.github.io/` which we also have. However, not a single `/<repository>` page works, neither `extendr` nor `libR-sys`.

**Comment by Ilia-Kosenkov** [comment]
Pinging @yutannihilation

**Comment by yutannihilation** [comment]
In my understanding, this isn't a bug, but a limitation of `cargo doc`. It generates the site with the structure of

```
❯ ls .\target\doc\  

    Directory: C:\Users\Yutani\Documents\GitHub\libR-sys\target\doc

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2023/03/06    21:45                implementors
d----          2023/03/06    21:45                libR_sys
d----          2023/03/06    21:45                src
d----          2023/03/06    21:45                static.files
-a---          2023/03/06    21:45              0 .lock
-a---          2023/03/06    21:45             33 crates.js
-a---          2023/03/06    21:45           4172 help.html
-a---          2023/03/06    21:45          54988 search-index.js
-a---          2023/03/06    21:45           4226 settings.html
-a---          2023/03/06    21:45             93 source-files.js
```

and I couldn't find the way to flatten the `libR-sys` or `extendr-api` directory.

**Comment by yutannihilation** [comment]
I mean, you might wonder if it's just changing this line to `./target/doc/extendr_api`, but then the site will be broken because it's without necessary CSS and JS files.

https://github.com/extendr/extendr/blob/b9fbacc9a044f9d3e04997e5949f386e24d158db/.github/workflows/docs.yml#L24

**Comment by Ilia-Kosenkov** [comment]
I saw other people complaining about similar issues. But I found no solution for Rust. Surprisingly, I sampled a couple of large Rust projects, and none seemed to have github pages deployed for projects, so there seems to be no good reference.

**Comment by eitsupi** [comment]
It seems helpful.
https://dev.to/deciduously/prepare-your-rust-api-docs-for-github-pages-2n5i

**Comment by Ilia-Kosenkov** [comment]
Yep, I suspected it was `index.html` issue. Now the problem is, in extendr we have 3 crates, to which one should we redirect? Can someone draft a simple `index.html` with like 3 links to each of the sub crate?

**Comment by multimeric** [comment]
Shouldn't each crate link to its own docs? I don't understand.

**Comment by eitsupi** [comment]
Indeed, there are three subdirectories in the GitHub Pages of this repository
https://extendr.github.io/extendr/extendr_api/
https://extendr.github.io/extendr/extendr_engine/
https://extendr.github.io/extendr/extendr_macros/

**Comment by yutannihilation** [comment]
Oh, thanks for the information. But, even if it's possible, is the dev version of the document is the most appropriate content for the root directory of the website? Aren't there anything that the users can find more useful? Just wondering.

**Comment by multimeric** [comment]
Conceivably yes, but in practise I would say everything we want to convey to the users should be in the rustdoc anyway. So I think redirecting to the crate index page is very sensible.

**Comment by Ilia-Kosenkov** [comment]
Oh that is clever! Let's see how the deployment looks!

**Comment by yutannihilation** [comment]
I tested on my local. It will look like this. Very simple one.

![image](https://user-images.githubusercontent.com/1978793/223123974-32280238-d4c6-4edc-836b-f8758a14b3b7.png)

**Comment by yutannihilation** [comment]
It's published now.

https://extendr.github.io/extendr/

**Comment by Ilia-Kosenkov** [comment]
Can we do the same to `libR-sys` and then close this issue?
