### ISSUE TITLE
How split rextendr lib.rs file into multiple files and export to R

### ISSUE THREAD

**Issue by junjunlab** [extendr/extendr#523]
Hi, if I have add1.rs and add2.rs rust functions in src directory with lib.rs file. How can I exprot them to R? I mean export functions to R from multiple .rs file if I have many codes with different functions in rust. This can be much readble for me.

add1.rs file: 
```
pub fn add1(x: i32, y: i32) -> i32 {
    x + y
}
```

add2.rs file: 
```
pub fn add2(x: i32, y: i32) -> i32 {
    x + y
}
```

and lib.rs file:
```
use extendr_api::prelude::*;

/// @export
#[extendr]
fn add(x: i32, y: i32) -> i32 {
    x + y
}

extendr_module! {
    mod testrsut;
    fn add;
}
```

**Comment by CGMossa** [comment]
I think this could be better documented. For now, let me give a quick description:

The `extendr_module!`-macro is the exporter. In it you mention the module name, and then the things you want to export from that module. Each rust module, could have such a macro definition in it. But then, you should be `use another_module` in the main one. 
Imagine it like a directed graph: The there is a root, which is the `lib.rs` module, and it has to link to the others. The others have to be `extendr_module`-modules also that define what to export from them.

**Comment by junjunlab** [comment]
So how should I write the code above, can you give a example? Thank you very much and for your answer.
