### ISSUE TITLE
Rcplx is broken on R-devel

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#524]
Originally filed at https://github.com/extendr/libR-sys/issues/149.

R-devel changed the definition of `Rcomplex` a few days ago (https://github.com/r-devel/r-svn/commit/862f9f816ff3ff3cb3f851603f19e99f60a98475) in order to match the C representation of complex with Fortran's representation (see https://bugs.r-project.org/show_bug.cgi?id=18430 for the details).

In short, `Rcomplex` is now a union, while the current exendr code assumes it's a struct. So, now extendr won't compile with the following error. We have to deal with this. I hope I can have time to fix this soon, but I'd appreciate if anyone can take a look because I've never used complex numbers...

```
error[E0560]: union `libR_sys::Rcomplex` has no field named `r`
  --> extendr-api\src\robj\into_robj.rs:93:20
   |
93 |         Rcomplex { r: 0., i: 0. }
   |                    ^ `libR_sys::Rcomplex` does not have this field
   |
   = note: available fields are: `__bindgen_anon_1`, `private_data_c`

error[E0560]: union `libR_sys::Rcomplex` has no field named `i`
  --> extendr-api\src\robj\into_robj.rs:93:27
   |
93 |         Rcomplex { r: 0., i: 0. }
   |                           ^ `libR_sys::Rcomplex` does not have this field
   |
   = note: available fields are: `__bindgen_anon_1`, `private_data_c`

error[E0784]: union expressions should have exactly one field
  --> extendr-api\src\robj\into_robj.rs:93:9
   |
93 |         Rcomplex { r: 0., i: 0. }
   |         ^^^^^^^^

error[E0609]: no field `r` on type `libR_sys::Rcomplex`
   --> extendr-api\src\robj\mod.rs:348:56
    |
348 |                     CPLXSXP => R_IsNA((*COMPLEX(sexp)).r) != 0,
    |                                                        ^ unknown field
    |
    = note: available fields are: `__bindgen_anon_1`, `private_data_c`
help: one of the expressions' fields has a field of the same name
    |
348 |                     CPLXSXP => R_IsNA((*COMPLEX(sexp)).__bindgen_anon_1.r) != 0,
    |                                                        +++++++++++++++++

error[E0609]: no field `r` on type `libR_sys::Rcomplex`
   --> extendr-api\src\scalar\rcplx_default.rs:105:28
    |
105 |         Rcplx(c64::new(val.r, val.i))
    |                            ^ unknown field
    |
    = note: available fields are: `__bindgen_anon_1`, `private_data_c`
help: one of the expressions' fields has a field of the same name
    |
105 |         Rcplx(c64::new(val.__bindgen_anon_1.r, val.i))
    |                            +++++++++++++++++

error[E0609]: no field `i` on type `libR_sys::Rcomplex`
   --> extendr-api\src\scalar\rcplx_default.rs:105:35
    |
105 |         Rcplx(c64::new(val.r, val.i))
    |                                   ^ unknown field
    |
    = note: available fields are: `__bindgen_anon_1`, `private_data_c`
help: one of the expressions' fields has a field of the same name
    |
105 |         Rcplx(c64::new(val.r, val.__bindgen_anon_1.i))
    |                                   +++++++++++++++++

Some errors have detailed explanations: E0560, E0609, E0784.
For more information about an error, try `rustc --explain E0560`.
error: could not compile `extendr-api` due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `extendr-api` due to 6 previous errors
```

**Comment by Ilia-Kosenkov** [comment]
I 'like' how they introduce a breaking change in a minor version.

**Comment by multimeric** [comment]
Yeah, was going to say.  Has anyone asked on the mailing list about this? Also isn't it a bit weird that the struct definition is part of the public interface when most of the other R structs are hidden?

**Comment by Ilia-Kosenkov** [comment]
According to this screenshot from the bug discussion, they have now to union definitions inside `Rcomplex`. Technically it changes nothing, but (even rustc notices that) we need to reference not `Rcomplex.r` but `Rcomplex.__bindgen_anon_1.r`.

**Comment by Ilia-Kosenkov** [comment]
> Also isn't it a bit weird that the struct definition is part of the public interface when most of the other R structs are hidden?

Well, R works over primitives, and the complex number is the only type that is not 'default' and its implementation can be opinionated. You cannot have many opinions on how to store an i32, but two f64 -- a different thing. Including alignment issues. Hence they expose it.

**Comment by yutannihilation** [comment]
I think the R core just doesn't consider this as a breaking change, considering there's no mention in the NEWS. But, yaah, I was wondering how this can be a non-breaking change to C/C++ users... Could any of you ask on the mailing list? I think I need more time to figure out what's going on.

Note that, as you can see the source code, the easiest fix for now would be to define `R_LEGACY_RCOMPLEX` to stick with the old definition, though I'm not sure how long this will be allowed.

**Comment by multimeric** [comment]
> Well, R works over primitives, and the complex number is the only type that is not 'default' and its implementation can be opinionated. You cannot have many opinions on how to store an i32, but two f64 -- a different thing. Including alignment issues. Hence they expose it.

But why not treat it like `SEXP` where all external interfaces just treat it as a pointer, and can't *do* anything with it other than using public function interfaces. Then you don't need to know the layout of the struct.

> 
According to this screenshot from the bug discussion, they have now two union definitions inside Rcomplex. Technically it changes nothing, but (even rustc notices that) we need to reference not Rcomplex.r but Rcomplex.__bindgen_anon_1.r.

Do you advise doing this, or is there a better way? I'm a bit out of my depth

> I think the R core just doesn't consider this as a breaking change, considering there's no mention in the NEWS. But, yaah, I was wondering how this can be a non-breaking change to C/C++ users... Could any of you ask on the mailing list? I think I need more time to figure out what's going on.

I'm happy to ask, but I'm not sure I have the vocabulary to explain it. Do I just say "the definition of `Rcomplex` has changed from a struct to a union, breaking our generated bindings"?

**Comment by Ilia-Kosenkov** [comment]
> But why not treat it like SEXP where all external interfaces just treat it as a pointer, and can't do anything with it other than using public function interfaces. Then you don't need to know the layout of the struct.

`SEXP` is a pointer, but `Rcomplex` is a struct, not a pointer to a struct stored somewhere (like `character` in R). When you pass it around, you still need to communicate to the CPU you are moving 128 bits of data, together.

> Note that, as you can see the source code, the easiest fix for now would be to define R_LEGACY_RCOMPLEX to stick with the old definition, though I'm not sure how long this will be allowed.

Actually, it feels like we need a set of features that describe what R version is used. E.g. if it is `R >= 4.3`. Then we could provide different implementations based on the breaking changes introduced.

**Comment by multimeric** [comment]
> Actually, it feels like we need a set of features that describe what R version is used. E.g. if it is R >= 4.3. Then we could provide different implementations based on the breaking changes introduced.

Don't we have config parameters that are set already based on the R version? Surely we can use those to handle this case. 

Also, if we define `R_LEGACY_RCOMPLEX` but we try to link to an R interpreter using the new unions, won't everything explode?

**Comment by yutannihilation** [comment]
> Actually, it feels like we need a set of features that describe what R version is used. E.g. if it is `R >= 4.3`.

Yes, that would be the proper fix. We can define a new `cfg` for R 4.3 here.

https://github.com/extendr/extendr/blob/master/extendr-api/build.rs

**Comment by multimeric** [comment]
Also, do you happen to know if this change is going to land in R 4.3.0, or is it in the version after that? Not sure if they have branches etc in the dev R.

**Comment by CGMossa** [comment]
It is possible in the libR package to define what version of r is being picked up. Those can be then picked up by extendr build.rs. But as far as I know, it is not possible to affect the features enabled 😕 from a build.rs.

Of course we can ask chat gpt and see if it knows a solution.

**Comment by yutannihilation** [comment]
> It is possible in the libR package to define what version of r is being picked up.

As you can see in the `build.rs`, it's defined as envvars.

**Comment by CGMossa** [comment]
I wasn't asking a question. As far as I know, you cannot set a feature cfg by an envvar.

I might be wrong though.

**Comment by multimeric** [comment]
I believe Yutani has linked above exactly the location where we already set cfg using an envvar. It seems to be using this logic: https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script

**Comment by CGMossa** [comment]
That's amazing. Thank you for teaching me thing. I truly never knew about this..

**Comment by yutannihilation** [comment]
Yes, I meant it. Sorry, my explanation was a bit too terse.

**Comment by Ilia-Kosenkov** [comment]
Can anyone explain why `R >= 4.1` is `use_r_ge_version_14`? Where does `14` come from?
https://github.com/extendr/extendr/blob/6e15390d2d4dbcd53878f4b31312c4fb68de25e6/extendr-api/build.rs#L21

**Comment by yutannihilation** [comment]
It's the version of the Graphics Device API.

https://github.com/extendr/libR-sys/blob/d113d56dd0c362ddf002e489b456face8c4c348d/bindings/bindings-linux-x86_64-R4.1.rs#L81

**Comment by multimeric** [comment]
Here's the mailing list thread. Nothing interesting yet: https://stat.ethz.ch/pipermail/r-devel/2023-April/082517.html.

I've just had the realisation that I'm probably embarrassing myself though, because the C compiler might actually insulate the user from this particular layout change. It seems likely that only Rust would be affected because it forces you to handle the union in a way that C probably doesn't, because it doesn't attempt to be safe in the same way.

**Comment by multimeric** [comment]
Yep, that seems to be the case!

**Comment by multimeric** [comment]
So what I'm thinking is this:
* Firstly, we wait until this patch actually hits a stable branch (?). The patch author pointed out to me that r-devel is unstable and that we shouldn't worry too much about it
* Secondly, once it does hit stable, we implement the `cfg` stuff discussed above
* Using this cfg flag, if we're on R > 4.4, we access the struct as `cplx.__bindgen_anon_1.i`. Otherwise we access fields as `cplx.i`. I will ask if they can rename the anonymous struct to make this less ugly
* Lastly, if and when https://github.com/rust-lang/rust/issues/49804 is implemented in stable Rust, we simplify our implementation using the changes

**Comment by multimeric** [comment]
As @CGMossa has pointed out, this has now hit the NEWS, meaning that it will be in R 4.3.0, so we're on to step 2.

**Comment by Ilia-Kosenkov** [comment]
I have a proposal -- currently, we use `use_r_ge_version_14`, which is tied to graphics API version. We should have a separate cfg for R versions. An example could be `r_ge_4_4` or `r_4_4_or_greater`. Ideally, we should rename graphics cfg to something like `r_graphics_ge_14`, but I am not sure if this is going to be painful for consumers.

**Comment by multimeric** [comment]
Yep, it looks like the `cfg` mechanism basically treats everything as a boolean, so it makes sense to have `GT`/`LT` config options since we can't do the numerical comparison within the Rust code. I agree with a `ge` -> `graphics` change.

**Comment by yutannihilation** [comment]
> An example could be `r_ge_4_4` or `r_4_4_or_greater`

The intention that I didn't chose the name like `r_4_1` was for not losing the context why we had to distinguish the version, but feel free to rename them.

> I am not sure if this is going to be painful for consumers.

These cfg are for internal logics, so I don't think this affects the users of extendr.

**Comment by Ilia-Kosenkov** [comment]
@multimeric, I believe here `ge` means `greater than or equal to`, and it is important to keep that this feature is enabled for graphics version `14` and higher. 
@yutannihilation, I did not suggest to remove it completely, only that if we have two `cfg`s both saying it is R version, it can be misleading. But separating it into `graphics` (what is used now) and an overall `R` version seems reasonable.

My only concern is that if somewhere someone relied on purely `libR-sys` and graphics `cfg`, their code will break if we change this. But on the other hand, we are in the pre-release phase, so we can occasionally break things.

**Comment by yutannihilation** [comment]
I now think the proper fix to this is to overwrite the definition in libR-sys. Although they have different names, C's `Complex` is also translated as a struct of two f64 fields. If I understand correctly, it's impossible to distinguish them over FFI anyway, because it's passed via a pointer without type information (if it were a tagged union, we could?). All we can care is their memory layouts, and it should be okay as long as their memory layouts agree, so I think this union is unnecessary.

```rust
#[repr(C)]
#[derive(Copy, Clone)]
pub union Rcomplex {
    pub __bindgen_anon_1: Rcomplex__bindgen_ty_1,
    pub private_data_c: __BindgenComplex<f64>,
}
```
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Rcomplex__bindgen_ty_1 {
    pub r: f64,
    pub i: f64,
}
```
```rust
#[derive(PartialEq, Copy, Clone, Hash, Debug, Default)]
#[repr(C)]
pub struct __BindgenComplex<T> {
    pub re: T,
    pub im: T,
}
```

**Comment by multimeric** [comment]
So both variants of the union are a struct with two fields that are `f64`? In that case I'm happy to just override bindgen here. It would make everything a lot easier for sure.

**Comment by multimeric** [comment]
To be quite honest I don't understand the point of the complex change in the first place. It's something to do with aliasing, and forcing the C compiler to handle something about the Fortran complex data type but it's weird to me that it doesn't actually change anything about the layout. This is what Tomas said on the mailing list:

> Not necessarily only gfortran, the problem arises anytime when an 
> Rcomplex value is (without explicit conversion) treated as C99 _Complex 
> double. The layout is (under some assumptions) the same, but not the 
> aliasing, so the information about that it can be treated as either 
> needs to be carried over. You would run into a similar problem when 
> calling say a library function expecting a C99 _Complex double, one 
> could argue it is not correct and one should do an explicit conversion, 
> but the question is how much code does it correctly. Then in theory 
> there could be LTO across C/Fortran/Rust and I can't rule out you 
> couldn't get to a similar situation (e.g. Rust calling Fortran). Ideally 
> really Rust should be able to translate this valid C11 code correctly.

> In case clarification is needed, the Fortran compiler will not see the 
> definition of Rcomplex at all, it will use complex numbers as defined in 
> Fortran, and in case of gfortran this is C99 _Complex at least on the 
> interface to C. The definition is for the C compiler, which compiles 
> code using ".r" and ".i" to access real and imaginary parts of complex 
> numbers. When compiling this code, the C compiler will be made aware 
> that values set via ".r" and ".i" may also be accessed as C99 _Complex 
> double objects. It will also store this information in object files, in 
> the intermediate representation used during link-time optimizations. The 
> link-time optimizer will then know that e.g. when passing Rcomplex from 
> (originally) C to COMPLEX*16 in (originally) Fortran, values set on the 
> C side via ".r" and ".i" are visible on the Fortran side in a 
> corresponding array of COMPLEX. Without knowing that, the link-time 
> optimizer could remove say stores to the ".r" and ".i" when calling to 
> Fortran, this is what has been actually seen to happen.

**Comment by yutannihilation** [comment]
Sorry, I forgot to say thank you for asking it on the mailing list. Yeah, I too don't understand it completely, but... I was thinking if it's really possible for Rust to handle a complex number over FFI at all after I found this description.

> Note that `Complex<F>` where `F` is a floating point type is only memory layout compatible with C’s complex types, not necessarily calling convention compatible. This means that for FFI you can only pass `Complex<F>` behind a pointer, not as a value.
https://docs.rs/num-complex/latest/num_complex/struct.Complex.html#representation-and-foreign-function-interface-compatibility

Though I don't understand what this exactly means either, I guess that "Rust calling Fortran" is the case; they probably pass values, considering they share the complex definition. If they are passed as a value, it might get optimized wrongly by the compiler. But, if they are passed as a pointer, it will be explicitly cast on Rust's side, so it won't be a problem.

**Comment by Ilia-Kosenkov** [comment]
Can we override the name and visibility of the generated `Rcomplex`? I think what we can do is just override its definition and then have some build-time test (like we already have in libR-sys) to verify that whatever gets bindgened from headers has an identical layout to our custom `Rcomplex(f64, f64)`.

**Comment by CGMossa** [comment]
@Ilia-Kosenkov I found out that there is a override mechanism in `bindgen`, it unfortunately only works for variables and functions.

Further this is going to be a little more painful. The type `Rcomplex` is used everywhere in the bindings. We cannot simply rename it to say `_Rcomplex`, because that would be the type we'd then have to pass around everywhere where `Rcomplex` is used (considering only the bindings here), ~ 138 references.

**Comment by Ilia-Kosenkov** [comment]
Can we define an impl for it? We can leave it as is but then provide a convenient API to work with, like accessing `re()` and `im()`, for instance. This will be a breaking change for `extendr`, but `libR-sys` will have the 'proper' implementation.

**Comment by CGMossa** [comment]
I'm attempting this over at https://github.com/extendr/libR-sys/pull/156
Feel free to provide comments and tasks on that PR continuously, as I've no idea when it is sufficiently done.

**Comment by CGMossa** [comment]
Fixed by https://github.com/extendr/libR-sys/pull/156
