### ISSUE TITLE
Links in Rust documentation are not converted to Roxygen.

### ISSUE THREAD

**Issue by bicarlsen** [extendr/extendr#534]
If a Rust function includes documentation with a link in typical markdown fashion, it is not converted to an R documentation link.
```rust
/// See [this URL](https://my-docs.com) for more.
fn my_fn() -> () { ... }
```
is translated to
```r
#' See [this URL](https://my-docs.com) for more.
my_fn <- function() .Call( ... )
```
in the `extendr-wrappers.R` file. Instead, it should be translated to
```r
#' See \href{https://my-docs.com}{this URL} for more.
my_fn <- function() .Call( ... )
```

**Comment by bicarlsen** [comment]
It appears the docs are build in the [`extendr-macros/wrappers > get_doc_string`](https://github.com/extendr/extendr/blob/8dc13d8ba87818e010542a4ac6977b5281dd98f5/extendr-macros/src/wrappers.rs#L139) function. Not sure the best way to go about the translation. Perhaps there is a way to parse the AST for markdown? If not, would a RegEx work?

**Comment by JosiahParry** [comment]
I don't think that is correct. Your expectation is for extendr to convert markdown to the appropriate `.Rd` tags (idk if that's what they're called). extendr will copy the text verbatim as is intended. For Roxygen to parse markdown ensure that the following is included in your `DESCRIPTION` file `Roxygen: list(markdown = TRUE). 

Have you made sure that is there? If so, then I think when you run `rextendr::document()` you will have the desired result in your `my_fn.Rd` file.

**Comment by bicarlsen** [comment]
I ran into this issue when writing a test for PR #528 ([See here](https://github.com/extendr/extendr/actions/runs/4709879451/jobs/8360330698)). And it seems that [the `DESCRIPTION` file](https://github.com/extendr/extendr/blob/master/tests/extendrtests/DESCRIPTION) already has `Roxygen: list(markdown = TRUE)`.

**Comment by yutannihilation** [comment]
Hi, thanks for the context. The mystery is solved. The error message says:

```
❯ checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'false.Rd':
    'https://github.com/extendr/extendr/issues/528'
  
  Missing link or links in documentation object 'raw_identifier_in_fn_args.Rd':
    'https://github.com/extendr/extendr/issues/528'
  
  Missing link or links in documentation object 'true.Rd':
    'https://github.com/extendr/extendr/issues/528'
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.
```

This is simply because your markdown syntax is wrong.

You wrote

``` r
#' See (Issue #582)[https://github.com/extendr/extendr/issues/528] for details.
```

but it should be

``` r
#' See [Issue #582](https://github.com/extendr/extendr/issues/528) for details.
```

https://github.com/extendr/extendr/pull/531/commits/6f7e53a887b8c3e0c346e3e56f2f398c30367304#diff-bb89d808cdf7e357a00c4e920ba42e1189e7471b473a0cfba10987a5e260aee9R99

**Comment by bicarlsen** [comment]
Ahhhh.... haha, my bad, thank you for the catch.

**Comment by JosiahParry** [comment]
Classic markdown.
