### ISSUE TITLE
implicit function param conversions leaks memory

### ISSUE THREAD

**Issue by sorhawell** [extendr/extendr#549]
extendr functions/method allow conveniently to set types in function param, to skip explicitly converting any Robj into something else. E.g. below `x: Strings` implicit call something like `robj.as_strings()` under the hood. However any conversion error will activate `throw_r_error`

`throw_r_error()` is easy to use, but known for leaking mem #278 . The history of alternatives are long and there is a broad spectrum of different opinions/patterns in the community. 

extendr relies on `throw_r_error` in this function header conversion. E.g. in this function Robj is converted to Strings. "use_try_from" can be true or false
```rust
#[extendr(use_try_from = true)]
fn give_me_string_vec(x: Strings) -> String {
    format!("thank you for Strings with length {} ...", x.len())
}
```

In this case the leakage is benign, only 3 integers or some Altrep thereof. For use cases where input is small, the user would find status quo completely acceptable.
```R
> polars:::give_me_string_vec(1:3)
Error in polars:::give_me_string_vec(1:3) : Expected Strings got Integers
```

however this will cause a 2Gb leak, which will not be recovered until Rsession is restarted
```R
(function() {
  for (i in 1:100) {
    print(i)
    x = sample(1:10,1e7,replace = TRUE)
    tryCatch(polars:::give_me_string_vec(x), error = \(err) NULL)
  }
})()
```

work arounds is to take any input as `Robj` and use `try_into` and return a result (#473) or panic!. Then there is no leakage.

**Comment by daniellga** [comment]
That's a problem... I use to avoid returning `Robj` so it's easier to identify the r type the function returns... Does the same happen if I use only `#[extendr]`?

**Comment by sorhawell** [comment]
This is a very nice show case. You may need to try floats instead of ints, as the latter may be passed as a very lightweight AltRep.

**Comment by sorhawell** [comment]
> That's a problem... I use to avoid returning `Robj` so it's easier to identify the r type the function returns... Does the same happen if I use only `#[extendr]`?

Everything is eventually converted into an Robj (or panic!) when return. I agree it looks prettier if signature not return Robj, but some more concrete type. But sometimes thats the most convenient, or if to explicit choose the conversion into Robj.

**Comment by multimeric** [comment]
> This is a very nice show case. Maybe floats instead of ints, as the latter may be passed as a very lightweight AltRep.

In the notebook I'm using `altrep[]` which coerces to a standard rep vector, [as discussed here](https://multimeric.github.io/altrepr/articles/altrepr.html#coercing-to-a-standard-integer-vector).

**Comment by multimeric** [comment]
I wonder if @yutannihilation or @Ilia-Kosenkov have some thoughts about the causes of these leaks. My first thought is that that the error message that we pass to `Rf_error()` is known to leak memory. I recall this came up in https://github.com/extendr/extendr/issues/278. 

It seems to me that we should be able to *allocate* the error message string in R memory, rather than in Rust as we are doing now. This would allow R to clean it up for us after Rust panics (I hope). There are a bunch of interesting R API C functions that feel like they should work here:

In `memory.h`:
```C
50:char*	R_alloc(R_SIZE_T, int);
51:long double *R_allocLD(R_SIZE_T nelem);
52:char*	S_alloc(long, int);
53:char*	S_realloc(char *, long, long, int);
55:void *  R_malloc_gc(size_t);
56:void *  R_calloc_gc(size_t, size_t);
57:void *  R_realloc_gc(void *, size_t);
```

In `RS.h`:
```C
47:extern void *R_chk_calloc(R_SIZE_T, R_SIZE_T);
48:extern void *R_chk_realloc(void *, R_SIZE_T);
```

`S_alloc` seems like a good candidate because it returns a char pointer?

**Comment by CGMossa** [comment]
Why not use these?
https://github.com/hadley/r-internals/blob/master/strings.md#creating-from-c-strings
Atleast they might presumably also be UTF-8.
This is what we use to allocate strings.

**Comment by multimeric** [comment]
I might be missing some other obvious function for this purpose, but all the functions listed on that page make an R character vector out of an existing C string. What we want to do is rather to call `Rf_error`, which *takes* a C string, which we have to allocate in Rust: https://github.com/hadley/r-internals/blob/master/error-eval.md. Not sure if `Rf_errorcall` helps here.

**Comment by multimeric** [comment]
Okay, it seems that calling `Rf_error` at all is known to use `longjmp` which (for reasons I don't understand) prevents C++ destructors being called. I assume this also affects us but I'm not certain. My next question (especially to those who understand this better), is why can't we just drop everything when before we long jump?

**Comment by sorhawell** [comment]
I have made another leak benchmark with 96 test cases.
[rust functions](https://github.com/sorhawell/does_it_leak/blob/main/src/rust/src/lib.rs)
[R testcode](https://github.com/sorhawell/does_it_leak/blob/main/tests/test_does_it_leak.R)
[results](https://github.com/sorhawell/does_it_leak/blob/main/tests/leak_result.txt)

Conclusion based on this test: 
 - that implicit conversions will leak on any Error. If using an AltVec (non-expanded) or single int/double it is not a lot.
 - To my horror/surprise .unwrap() appears just as bad Error as implicit conversion !? I thought unwind was suppose to clean up?!
 - When Return some encoded Error to R it never* leaks, because it just another value returned to R.

*seem first big string leaks in testcase-row1 is a burn-in fluke.

**Comment by sorhawell** [comment]
> is why can't we just drop everything when before we long jump?

Empirically I tried to drop everything but did not succeed. I was able to mitigate memory leakage though.

Wildcard explanation: Maybe the issue is in R/R C-api before rust. Maybe inputs are protected or something in start of `.Call()` but some unprotect procedure is skipped in the end due to longJmp.

**Comment by sorhawell** [comment]
Interesting idea to try to allocate in R the error string. I guess leaking the error string is annoying but acceptable. BaseR likely leaks more anyways here and there. Leaking large inputs is the baddie.

**Comment by daniellga** [comment]
> 

For that bonus observation, are you taking into account what the doc says below?

![image](https://user-images.githubusercontent.com/43149605/236588891-e115cdfa-494d-49eb-b26a-842cf5322f8e.png)

**Comment by yutannihilation** [comment]
@multimeric 
> It seems to me that we should be able to _allocate_ the error message string in R memory, rather than in Rust as we are doing now.

cpp11 holds a fixed size of memory for error messages. I think this is nicer than worrying about how to allocate and free every time. 

https://github.com/r-lib/cpp11/blob/3c36f7f48a4998c0cd0abb2fc964b24393eafe21/inst/include/cpp11/declarations.hpp#L30-L34C12

But, my guess is extendr's main problem is that it doesn't drop the `Error` that holds the `Robj`. You can probably `drop(e)` before calling `throw_r_error()`.

https://github.com/extendr/extendr/blob/ca001033e371ff3f52022cea72aa534f2958f041/extendr-api/src/error.rs#L20-L27

**Comment by multimeric** [comment]
> cpp11 holds a fixed size of memory for error messages. I think this is nicer than worrying about how to allocate and free every time.

Well there's no harm in trying to allocate the error message in R right? We won't have to free it ourselves.

> But, my guess is extendr's main problem is that it doesn't drop the Error that holds the Robj. You can probably drop(e) before calling throw_r_error().

Yep this could be right, although why wouldn't it be dropped? Maybe I'm misunderstanding the process here. I thought we threw the error using `Rf_error`, which caused everything to unwind, and be dropped? Why would it drop other objects but not the error using the mechanism that we have?

**Comment by yutannihilation** [comment]
> `Rf_error`, which caused everything to unwind, and be dropped?

This is different from my understanding. Does this help?

https://github.com/rust-lang/project-ffi-unwind/blob/master/faq.md#how-does-cross-language-unwinding-differ-from-cross-language-setjmplongjmp

**Comment by multimeric** [comment]
I'm sure you understand, but I'm afraid that link doesn't clear things up for me. Can you list the sequence of events that happens when we `Rf_error`?

**Comment by yutannihilation** [comment]
> It should never be assumed that drop will be called for objects in intermediate frames traversed by a longjmp, but this may occur on certain platforms. Rust provides no guarantee either way (which is why this is considered [Undefined Behavior](https://github.com/rust-lang/project-ffi-unwind/blob/master/spec-terminology.md#UB)).

**Comment by multimeric** [comment]
> Cross-language unwind, however, will be defined such that Drop objects whose frames are unwound are guaranteed droped

I can't really reconcile this with the above statement. Is this not cross-language? Which frames are intermediate here?

**Comment by yutannihilation** [comment]
Sorry, I think I don't have enough knowledge to answer your questions. I just show the references that you might find something useful to you there.

**Comment by Ilia-Kosenkov** [comment]
I have some stupid questions:
- Why do we even return an `Robj` as part of the `TryFrom` errors? What does it solve?
- We can separately address the issue when we expect `Vec<T>`, but we pass an altrep of a different type, and we first materialize it and then try to convert. The memory might still leak, but it will be the altrep generator that leaks, not the whole materialized vector. 

I am unfortunately very, very far away from stack unwindings and long jumps, so it is hard for me to contribute to the discussion.

**Comment by multimeric** [comment]
Okay, here is some information I have gathered.

Firstly, we know that `Rf_error` long jumps :

> Rf_error will longjmp and so any code following will not be executed; however, most compilers do not detect this when providing warnings) [[1](https://github.com/hadley/r-internals/blob/master/error-eval.md#errors-and-evaluation)]

longjmp- type functions are defined as:

> a function that causes a "jump" in control flow by deallocating some number of stack frames without performing any additional "clean-up" such as running destructors [[2](https://blog.rust-lang.org/inside-rust/2021/01/26/ffi-unwind-longjmp.html#longjmp-and-its-ilk)]

This is cemented by:

> It should never be assumed that drop will be called for objects in intermediate frames traversed by a longjmp, but this may occur on certain platforms. Rust provides no guarantee either way (which is why this is considered [Undefined Behavior](https://github.com/rust-lang/project-ffi-unwind/blob/master/spec-terminology.md#UB)). Cross-language unwind, however, will be defined such that Drop objects whose frames are unwound are guaranteed droped. [[3](https://github.com/rust-lang/project-ffi-unwind/blob/master/faq.md#how-does-cross-language-unwinding-differ-from-cross-language-setjmplongjmp)]

I think what this actually means, upon re-reading this a number of times, is that currently Rust cannot be assumed to run destructors across a long jump, and that supporting destructors *is a goal of the project-ffi-unwind project*.

Considering all this, I believe that the current behaviour which is to not drop anything ourselves, is wrong.

**Comment by multimeric** [comment]
@Ilia-Kosenkov 

> Why do we even return an Robj as part of the TryFrom errors? What does it solve?

Do you mean why do we store a `Robj` in the `Error` enum? It's solely for the error message I think. But anyway even if we removed this, it sounds like everything else we have allocated will leak so we might as well solve this more methodically.

> We can separately address the issue when we expect Vec<T>, but we pass an altrep of a different type, and we first materialize it and then try to convert. The memory might still leak, but it will be the altrep generator that leaks, not the whole materialized vector.

I must have missed this. Why do we materialize the altrep if we can check its type without doing that?

**Comment by CGMossa** [comment]
This is really earth shattering information.

I'd just like to point out that we need to `R_ReleaseObject` the `OWNERSHIP` static object in `ownership` module as well. 

This functionality is not present at the moment. I'll start thinking about it. I think we can just extract what happens in the `garbage_collect` method for nuking everything, before the no-return longjump of `Rf_error`. Note that this step should clear all `Robj`, as they are protected upon creation / cloning etc.

**Comment by yutannihilation** [comment]
> I'd just like to point out that we need to `R_ReleaseObject` the `OWNERSHIP` static object in `ownership` module as well.

This is not important to the main topic here anyway, but I believe the `OWNERSHIP` object is what is supposed to never be released (but the objects that are referenced by it can be).

**Comment by multimeric** [comment]
Oh, why do we not need to drop it?

**Comment by yutannihilation** [comment]
Because I believe it's supposed to never be released. Anyway, again, it's not related to the main concern here. Sorry for the noise.

**Comment by multimeric** [comment]
Wait but it's not noise. I fully intended to drop it. Is it some part of Rust or R that forbids us from dropping it?

**Comment by yutannihilation** [comment]
Maybe you are confusing releasing the protection provided by the `OWNERSHIP` with releasing the `OWNERSHIP` itself? I'm not sure, but I think you'll see segfault when you execute the wrapper R function second time if you delete the `OWNERSHIP` at the first time, because, as [you've already seen](https://github.com/extendr/extendr/issues/468#issuecomment-1532380850), any `Robj` will try to get protected.

**Comment by multimeric** [comment]
Okay I see, `OWNERSHIP` is static so it will just exist inside the extension's DLL from the point at which it's `dyn.load`ed, separately from the function calls.

Also this is possibly common knowledge but I just now realised that we catch all panics with this hook around each C function, and put them in an `Error` (which is then `Rf_error`'ed: https://github.com/extendr/extendr/blob/8dc13d8ba87818e010542a4ac6977b5281dd98f5/extendr-macros/src/wrappers.rs#L110-L112

This means that a literal `panic!` call will leak memory through the same mechanisms as have been discussed.

**Comment by multimeric** [comment]
I wonder also if this `R_UnwindProtect` stuff is relevant here? https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Condition-handling-and-cleanup-code.

In theory it's supposed to give us the chance to clean up memory in case of an long jump, but I can't make sense of how to use it or if it's relevant. Although Soren's PR provides alternative ways to handle errors, I would kind of still like to sort out `Rf_error()` handling since we want to provide it as an option.

**Comment by multimeric** [comment]
Actually no, I think we're all in agreement that `Rf_error` is a bad idea, and we should avoid it at all costs. Further, as I've discovered, even `Rcpp` avoids calling `Rf_error`: 
https://github.com/RcppCore/Rcpp/blob/71e64b0513ce358535575dccc4fdf5c841701619/vignettes/rmd/Rcpp-attributes.Rmd#L217-L224

I think we now need to go all-in on https://github.com/extendr/extendr/pull/473.

**Comment by yutannihilation** [comment]
> I wonder also if this `R_UnwindProtect` stuff is relevant here?

`R_UnwindProtect` is what gives you a chance to clean up memory in the `clean()` callback function before the longjmp by an R error is actually called, but I think you already have the chance because you know when `Rf_error()` is called. So, I think it doesn't help you much. If you know what to release, you should be able to do it with or without `R_UnwindProtect()`, and you probably cannot if you don't know.

> we're all in agreement that `Rf_error` is a bad idea

Yes, I agree.

**Comment by sorhawell** [comment]
I guess #473 only adresses if user wanted to return a user generated result UserResult: Result<T,E> where E,T: IntoRobj to R-side. Implicit conversions and other extendr-internals could produce a Result also Result<UserResult,U> where U: IntoRobj before encoding into one Robj and returning to R.

**Comment by multimeric** [comment]
Yes, and we want to cover all these scenarios. As I was saying in the discord, we will have to use the macro to define how each function should handle errors, and this should affect all errors, not just user generated ones.

**Comment by multimeric** [comment]
I re-built my test notebook because it was suspiciously defying all my attempts to fix this in extendr. The main change I made is that I generate each input vector using `rnorm`, so everything is guaranteed to be "fresh" and uncached. Not sure why this matters, but it gives very different results: https://github.com/multimeric/ExtendrMemoryLeaking/blob/master/MemoryLeak2.md#memoryleak2.

The main thing to note is that it *only* leaks when `try_from` is disabled, and when it's enabled it never leaks. Unfortunately I have no idea how that makes sense, because both flags lead to the same code path where we call `Rf_error()`. I'm not sure if anyone can suggest what is happening here because right now it seems like it's not an urgent issue when it doesn't leak as much as initially thought.

**Comment by sorhawell** [comment]
> The main thing to note is that it only leaks when try_from

the tests I posted above I think found that try_from was leaking just as much .
Interesting to see where the difference is.

**Comment by sorhawell** [comment]
[Test case 33-64 uses try_from with various functions and inputs](https://github.com/sorhawell/does_it_leak/blob/main/tests/leak_result.txt). The right-most column is my corrected leakage value. There appear to be leakage in half of the cases  which is the same as using unwrap manually.

Only bypassing extendr conversions completely and returning errors encoded inside the Robj shows no leakage in all tests cases.

**Comment by multimeric** [comment]
It's weird that the failed conversions are what do it. Admittedly they aren't something I tested in my notebook.

Maybe the common theme is that all errors that contain a Robj do leak (conversions, but also my first notebook showed this outside of a conversion). If so, it really seems like Yutani's simple fix (dropping the error Robj) should work. But also, then I don't understand is why the `panic!()` (`throw_1` in my second notebook) also fails.

**Comment by sorhawell** [comment]
> It's weird that the failed conversions are what do it.

As I chose to define it, in my test cases if a conversion succeed (that is when a function is passed the right param type) there is not any Err no throw_r_error() is called.

Maybe one way to move forward is use cargo expand and copy paste the expansion of the `#[extendr]` macro. Then try to fiddle with scopes and drop to see if leaking in any way is possible to avoid when using throw_r_error(). If so, likely the extendr-macro can be updated. If not, throwing errors should only be done on R side.

**Comment by yutannihilation** [comment]
I wrote a blog post that gathers information I had to learn in order to understand the problem. Hope this helps a bit.

https://yutani.rbind.io/post/r-rust-protect-and-unwinding/

**Comment by sorhawell** [comment]
thx I learned alt so these [protect and unprotect](https://github.com/extendr/extendr/blob/ca001033e371ff3f52022cea72aa534f2958f041/extendr-api/src/ownership.rs#L24) functions in extendr I see now can protect and then unprotect multiple Robj's in any order because it is not calling directly C-api protect/unprotect, but store them in a hashmap.

**Comment by sorhawell** [comment]
I think I have a solution to rearrange the sequence of operations in the proc macro expanded `wrap__xyz` and the memory leakage goes to near zero bytes (amortized).

### this simple function
```rust
#[extendr]
fn string_to_string(x: String) -> String {
    x.len().to_string()
}
```
### gets expanded to  this
```rust
#[no_mangle]
#[allow(non_snake_case, clippy::not_unsafe_ptr_arg_deref)]
pub extern "C" fn wrap__implicit_string(x: extendr_api::SEXP) -> extendr_api::SEXP {
    unsafe {
        use extendr_api::robj::*;
        let _x_robj = extendr_api::new_owned(x);
        extendr_api::handle_panic(
            "implicit_string panicked.\0",
            || {
                extendr_api::Robj::from(
                        implicit_string(
                            extendr_api::unwrap_or_throw(<String>::from_robj(&_x_robj)),
                        ),
                    )
                    .get()
            },
        )
    }
}
```
The current expansion will panic! on conversion error and if some function (not possible in this example) would return an Err(E). Then this panic! is caught again `handle_panic` which calls `throw_r_error()`. I would strongly recommend anyways to use the idiomatic Result-pattern in rust code and not using panic! as a replacement for try-catch.

Anyways if we can't trust panic-unwind to drop and unprotect allocations before calling throw_r_error, we can use rust-Result to make the sequence of operations (param conversion, call user function, output conversion) non-fallible. Then we can drop as much as possible, and then examine the final nested Result object and call `throw_r_error()`.

```rust
#[no_mangle]
#[allow(non_snake_case, clippy::not_unsafe_ptr_arg_deref)]
pub extern "C" fn wrap__string_to_string(x: extendr_api::SEXP) -> extendr_api::SEXP {
    let z = unsafe {
        use extendr_api::robj::*;
        let _x_robj = extendr_api::new_owned(x);
        //safe_handle_panics is only a last guard against user induced panics!.
        let result = safe_handle_panic(
            "sry your user function panicked, not extendr.\0",
            || -> std::result::Result<Robj, Robj> {
                //convert user param1
                let param1_result = <String>::from_robj(&_x_robj).map_err(|err| err.into_robj());

                // run user func, but bubble all params first
                let user_f_out = string_to_string(param1_result?);

                //user_f_out could be a result ... vanilla extendr will cause a panic on Err then
                let user_out_after_conversion = extendr_api::Robj::from(user_f_out);

                //hurray user function ran without errors, this is the final value
                Ok(user_out_after_conversion)
            },
        );
        result
    };
    //drop(x);
    // let zz = extendr_api::handle_panic("stuff happended", || {
    //     z.expect("user error/conv").expect("user panic")
    // });
    match z {
        Ok(Ok(zz)) => {
            return unsafe { zz.get() };
        }
        _ => {
            //drop(z); // not really needed for some reason
            extendr_api::throw_r_error("an error happended");
            unreachable!("nope");
        }
    }
}

pub fn safe_handle_panic<F, R>(err_str: &str, f: F) -> std::result::Result<R, String>
where
    F: FnOnce() -> R,
    F: std::panic::UnwindSafe,
{
    std::panic::catch_unwind(f).map_err(|err| format!("any is {:?}", err))
}
```

**Comment by sorhawell** [comment]
I believe #555 solves the leaking.
