### ISSUE TITLE
Cannot include `Rfloat` in function signature with `#[extendr]` macro

### ISSUE THREAD

**Issue by JosiahParry** [extendr/extendr#550]
Here is a reprex:

```rust
#[extendr]
fn add_na_aware(x: Doubles, y: Rfloat) -> Doubles {
    x
        .into_iter()
        .map(|xi| {
            let is_na = xi.is_na();

            if is_na {
                Rfloat::from(-99_f64)
            } else {
                xi + y
            }
        })
        .collect::<Doubles>()
}
```

When providing an argument with type `Rfloat` in the function signature that has the `#[extendr]` macro, the function cannot be compiled. No such issue exists when using `f64` but does for `Rfloat`. I feel like these are "mostly" functionally equivalent.

See error message: 

```
error[E0599]: no function or associated item named `from_robj` found for struct `Rfloat` in the current scope   --> src/lib.rs:37:1
```

**Comment by Ilia-Kosenkov** [comment]
How about `#[extendr(use_try_from = true)]`?

**Comment by JosiahParry** [comment]
😮‍💨 yah, that works! I'll never be able to remember to use that one!
