### ISSUE TITLE
Switch Github Actions to ubuntu-20.04

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#56]
The GH Actions scripts currently use ubuntu-latest, which is ubuntu-18.04. Over the next few weeks, this will switch over to ubuntu-20.04 (https://github.com/actions/virtual-environments/issues/1816), and then this line will break:
https://github.com/extendr/extendr/blob/5ebf0ab1dfc6e9574fe80526dca97ecf8377223b/.github/workflows/test.yml#L24

I think it would be best to switch over to ubuntu-20.04 explicitly now. You can see a workflow for that version here:
https://github.com/clauswilke/helloextendr/blob/main/.github/workflows/R-CMD-check.yaml
Notably, it doesn't require any setup for libclang, it just works.

cc @hobofan @CGMossa

**Comment by yutannihilation** [comment]
I addressed this in #53. If you want a separate pull request, I'll create another one. Anyway, it's now confirmed Ubuntu 20.04 works by the checks on my pull request :tada:  https://github.com/extendr/extendr/pull/53/checks?check_run_id=1471818079

**Comment by clauswilke** [comment]
I have merged #53. Does that close this issue?

**Comment by yutannihilation** [comment]
I believe yes.
