### ISSUE TITLE
New version based on libR-sys 0.6.0?

### ISSUE THREAD

**Issue by eitsupi** [extendr/extendr#567]
Are there any plans for releases?

**Comment by eitsupi** [comment]
#580

Please do not release a version based on libR-sys 0.5.0.

**Comment by eitsupi** [comment]
Any chance to the new release?

**Comment by yutannihilation** [comment]
+1 for cutting a new release, not only because libR-sys is too outdated, but also because #555  is so critical.

@Ilia-Kosenkov @CGMossa @andy-thomason @multimeric 
Any thoughts?

**Comment by CGMossa** [comment]
I'd be so thankful if you made a release.

**Comment by multimeric** [comment]
Fine with me. Can we ensure the changelog is up to date so I can better understand the new release?

**Comment by Ilia-Kosenkov** [comment]
Please go ahead, but +1 to checking changelog & running full CI once again (if it has not recently been executed). Thanks!

**Comment by yutannihilation** [comment]
Thanks. The changelog looks good to me. Please let me know if you have any concern.

https://github.com/extendr/extendr/blob/master/CHANGELOG.md

**Comment by yutannihilation** [comment]
I updated the version to v0.6.0 (https://github.com/extendr/extendr/pull/637). I think this is ready to publish the release now. Please let me know if there's any concern.

**Comment by CGMossa** [comment]
I think you should publish it as is.
I looking around, I released that there are a ton of improvements that I didn't make PRs for.

Of course this can be a message to someone else.

**Comment by yutannihilation** [comment]
Done! Thanks for all your help.

https://crates.io/crates/extendr-api/0.6.0
https://crates.io/crates/extendr-macros/0.6.0
https://crates.io/crates/extendr-engine/0.6.0

**Comment by eitsupi** [comment]
THanks!
