### ISSUE TITLE
Support `PartialOrd` trait for R scalars

### ISSUE THREAD

**Issue by JosiahParry** [extendr/extendr#570]
At present, there is no way to compare the max or min of two `Rfloat`s. To do this, we need to grab the inner f64.  For example using an `Rfloat` `x` and `y` and return an Rfloat this is done: 

`Rfloat::from(x.0.min(y.0))`

Consider treating `NA` as `NaN` so no comparison is done.

**Comment by yutannihilation** [comment]
> To do this, we need to grab the inner f64.

Nitpicking. As you probably know, `f64` is not `Ord` either. Do you mean `PartialOrd`? Or, are you suggesting implementing `.min()`?

**Comment by Ilia-Kosenkov** [comment]
Moved this discussion from discord. Yep, the idea is `PartialOrd` & treating `NA`s as `NaN`s are treated.
