### ISSUE TITLE
Should not use libR-sys 0.5.0

### ISSUE THREAD

**Issue by eitsupi** [extendr/extendr#580]
See mlverse/tok#4

One of the flavors on CRAN seems to fail to build libR-sys 0.5.0.

**Comment by yutannihilation** [comment]
`  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /data/gannet/ripley/R/packages/tests-MKL/tok/src/.cargo/registry/src/github.com-1ecc6299db9ec823/libR-sys-0.5.0/build.rs:637:40`

This line:

https://github.com/extendr/libR-sys/blob/a1047c2cd9a2909c2a48ed615657dd18ff18d4fb/build.rs#L637C1-L637C58

**Comment by yutannihilation** [comment]
Maybe `.canonicalize()` added in this pull request make some problem on [the Fedora machine](https://www.stats.ox.ac.uk/pub/bdr/Rblas/README.txt)? If so, I think we can opt-out the canonicalization for non-Windows platforms.

https://github.com/extendr/libR-sys/pull/154

But, as other Fedora machines pass without problems, it might be a problem on the machine setup.

**Comment by yutannihilation** [comment]
Just released my package with libR-sys 0.5.0. Let's see if this fails as well.

https://cran.r-project.org/web/checks/check_results_string2path.html (v0.1.4 is the version)

**Comment by yutannihilation** [comment]
Hmm, strange. I got the acceptance email, but my package is still in the pretest queue for 10 hours. It seems something is wrong on CRAN servers.

**Comment by eitsupi** [comment]
Thanks for taking a look at this!

I did a little research and couldn't find any mention of a problem of `canonicalize()` on Linux.
Is it possible that `r_paths.library` did not exist in the first place instead of `canonicalize()`'s problem? If so, would libR-sys 0.4.0 be expected to not work?
Could you consider using `unwrap_or_default` or something instead of `unwrap` there?

(Perhaps this issue needs to be transferred to extendr/libR-sys?)

**Comment by yutannihilation** [comment]
> Is it possible that `r_paths.library` did not exist

Yeah, it's the only possibility I could come up with. libR-sys assumes the library is on `{R_HOME}/lib`, but it might not be always true. I have no idea in what case R's shared libs are placed in some different location.

https://github.com/extendr/libR-sys/blob/e1a740e25b91a028617afe52e54bc476b45870c1/build.rs#L203C28-L203C28

**Comment by yutannihilation** [comment]
> If so, would libR-sys 0.4.0 be expected to not work?

That's the question. It might work without `rustc-link-search` if the path is included in some other way.

https://doc.rust-lang.org/cargo/reference/environment-variables.html#dynamic-library-paths

**Comment by CGMossa** [comment]
We could piggyback on `R CMD config - -cppflags`, or atleast print that our as debug, as it will give you the directories R thinks the libraries are located at.

**Comment by yutannihilation** [comment]
Thanks, but we cannot debug the CRAN servers.

**Comment by yutannihilation** [comment]
Congratulations! I hit the same error, which means I'm entitled to ask this on the mailing list.

https://cran.r-project.org/web/checks/check_results_string2path.html

**Comment by Ilia-Kosenkov** [comment]
Am I correct that there are two fedora builds that are already successful for version 0.1.4? Meaning that it is MKL that is misconfigured? Also, let's update `build.rs` with more meaningful errors, opting in for more `.expect()` or similar calls.

**Comment by yutannihilation** [comment]
> Am I correct that there are two fedora builds that are already successful for version 0.1.4?

Yes.

> Meaning that it is MKL that is misconfigured?

I think so, but I'm not fully sure.

**Comment by dfalbel** [comment]
Ohh, that sounds reasonable. 
I think what we really wanted instaed of `canonicalize` is something like `normalizePath("path", mustWork = FALSE)` then. This also explains why it didn't error with previous versions that didn't call canonicalize.

**Comment by Ilia-Kosenkov** [comment]
Any voluteers to fix it and release `libR-sys 0.5.1`? :)

**Comment by yutannihilation** [comment]
I will!

Btw, what this means is that `rustc-link-search` (and probably `rustc-link-lib`) are unnecessary if we target only R packages? I'll implement a quick workaround for now, but I think libR-sys needs some cleanup.

**Comment by yutannihilation** [comment]
> Btw, what this means is that `rustc-link-search` (and probably `rustc-link-lib`) are unnecessary if we target only R packages?

I'm almost certain now. You don't need it except for embedded usages. Does anyone really use extendr for embedded usage?

**Comment by yutannihilation** [comment]
The fixed version is on CRAN now. Let's see if the MKL error disappears.

https://cran.r-project.org/web/checks/check_results_string2path.html

**Comment by yutannihilation** [comment]
Now that CRAN is back to normal and I don't see the failure on the MKL check, I think it's now safe to say the fix is confirmed. I created the pull request to bump the version. If this gets approved, I'll merge this and publish v0.5.1 to crates.io.

https://github.com/extendr/libR-sys/pull/175

**Comment by yutannihilation** [comment]
Not in a hurry, but can anyone approve this pull request?

https://github.com/extendr/libR-sys/pull/175
