### ISSUE TITLE
breaking change to Rfloat and Rint

### ISSUE THREAD

**Issue by sorhawell** [extendr/extendr#584]
I believe merged PR #573 introduced an unannouced breaking change to extendr.
The inner fields of the Rfloat and Rint abstractions have been made private.

It is no longer possible to access to the inner values of Rfloat and Rint.

This matters e.g. for `polars` which performs custom conversions.
What is the new way to access the inner value?

```
  Compiling r-polars v0.1.0 (/Users/sorenwelling/Documents/projs/r-polars/src/rust)
   error[E0616]: field `0` of struct `Rfloat` is private
     --> src/conversion_r_to_s.rs:71:35
      |
   71 |                         let x = x.0.to_bits() as i64;
      |                                   ^ private field
   
   error[E0616]: field `0` of struct `Rfloat` is private
     --> src/conversion_r_to_s.rs:93:66
      |
   93 |                     .map(|x| if x.is_na() { None } else { Some(x.0) })
      |                                                                  ^ private field
   
   error[E0616]: field `0` of struct `Rint` is private
      --> src/conversion_r_to_s.rs:133:66
       |
   133 |                     .map(|x| if x.is_na() { None } else { Some(x.0) })
       |                                                                  ^ private field
   
   error[E0616]: field `0` of struct `Rfloat` is private
      --> src/utils/mod.rs:100:32
       |
   100 |                 Ok(Some(rvalue.0))
       |                                ^ private field
       |
      ::: src/series.rs:396:28
       |
   396 |                 Float64 => apply_output!(r_iter, strict, allow_fail_eval, Doubles, Float64Chunked),
       |                            ----------------------------------------------------------------------- in this macro invocation
       |
       = note: this error originates in the macro `handle_type` which comes from the expansion of the macro `apply_output` (in Nightly builds, run with -Z macro-backtrace for more info)
   
   error[E0616]: field `0` of struct `Rint` is private
      --> src/utils/mod.rs:111:28
       |
   111 |             let val = rint.0;
       |                            ^ private field
       |
      ::: src/series.rs:397:26
       |
   397 |                 Int32 => apply_output!(r_iter, strict, allow_fail_eval, Integers, Int32Chunked),
       |                          ---------------------------------------------------------------------- in this macro invocation
       |
       = note: this error originates in the macro `handle_type` which comes from the expansion of the macro `apply_output` (in Nightly builds, run with -Z macro-backtrace for more info)
       ```

**Comment by Ilia-Kosenkov** [comment]
This was intentional and in-line with other scalars. For now, there is an `.inner()` method to handle this, but in the future it will likely be marked `unsafe`, since it is by nature unsafe.

**Comment by Ilia-Kosenkov** [comment]
Checks for `na` are, weird, all primitives can be safely cast into respective `Option<T>`

**Comment by sorhawell** [comment]
Some arguemnts why users should be able to access `.inner()`

 - extendr currently does not support all thinkable conversions e.g. bit64 conversions, integerish conversions.
 - Some conversion are opinionated not all projects will agree. Customization is good.
 - A big project will tend to want to own their conversions it self to maximize control.

**Comment by JosiahParry** [comment]
I too rely on the use of .inner() and would be sad to see it go.

**Comment by daniellga** [comment]
The weird part for me is that the new inner method is part of a trait instead of part of the struct. It is a weird design choice imo. because of this, it is difficult to find this inner method in docs.

**Comment by JosiahParry** [comment]
I think having it as a trait makes sense given that this is a method that is shared by all Scalar structs. Navigating Rust docs alone is tough. I think it wouldn't be a terribly crazy idea to have a user guide that attempts to collect doc in a user friendlier way
