### ISSUE TITLE
Fail in github actions for macos - `clang: error: no such file or directory: '=-L./rust/target/release'`

### ISSUE THREAD

**Issue by daniellga** [extendr/extendr#589]
I am having a fail process running on extendr 0.4.0 exclusively for macos. Would you mind checking what's happening here?

actions run: https://github.com/daniellga/harmonium/actions/runs/5959477303
repo: https://github.com/daniellga/harmonium

![image](https://github.com/extendr/extendr/assets/43149605/fb98b5e2-27a7-4e55-9ac7-b56eca4a7fe4)

![image](https://github.com/extendr/extendr/assets/43149605/c2ebf134-3d85-4453-80a9-0c3a6559d012)

Thanks!

**Comment by CGMossa** [comment]
Didn't you solve this already?

**Comment by daniellga** [comment]
> Didn't you solve this already?

I solved a ton of other errors and this is the only one left and I have no idea what's happening here and can't reproduce it (or don't know how to) since I don't have a mac...

**Comment by daniellga** [comment]
Turned out to be a typo error in makevars file :(... sorry to bother...

**Comment by CGMossa** [comment]
Thank God you figured it out
