### ISSUE TITLE
Serde for R lists

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#60]
It would be nice to provide conversion to/from structs using `#[derive(Serialize, Deserialize)]`

This should be fairly straightforward to do if anyone felt like a challenge.

eg.

```
#[derive(Serialize, Deserialize)]
struct Fred {
  x: String,
  y: f64,
}

fn consume_list(list: Robj) -> Fred {
   // Call from_robj on every member of Fred.
   Robj::from_list::<Fred>(&list).unwrap()
}

fn produce_list(fred: Fred) -> Robj {
  // Call from<Robj> on every member of Fred.
  Robj::to_list(&fred)
}
```
Note that the default behaviour on structs is to convert to/from
an EXTPTRSXP.

**Comment by clauswilke** [comment]
One issue to consider: Each additional external dependency slows down compile time. Maybe this should be implemented as an optional compile-time feature that is off by default? I'd argue the same for the code that requires ndarray.

**Comment by yutannihilation** [comment]
If we care about the compilation time, maybe we can use a feature flag for serde? For ndarray, there might be other choices as Rust has many math libraries (nalgebra, cgmath, euclid, glam...), which I always get lost about which one to choose...

**Comment by lebensterben** [comment]
>If we care about the compilation time, maybe we can use a feature flag for serde? For ndarray, there might be other choices as Rust has many math libraries (nalgebra, cgmath, euclid, glam...), which I always get lost about which one to choose...

@yutannihilation for serious linear algebra, you still need Eigen or Armadillo.

**Comment by andy-thomason** [comment]
We need an Eigen for Rust soo badly :grimacing:  Oh for the time to do this. **sigh**.

**Comment by andy-thomason** [comment]
I agree that fewer default dependencies are bad. **ndarray* should be non-default, but supported. Yes, indeed serde should be a feature.

**Comment by lebensterben** [comment]
We can benefit from some tricks mentioned here to "pre-build" dependencies:

https://github.com/rust-lang/cargo/issues/2644

For example, for the skeleton template setup, it's already a valid rust crate and can be built. The dependencies can be reused unless the user called cargo-clean.
