### ISSUE TITLE
Example of using Dataframe row 

### ISSUE THREAD

**Issue by rdavis120** [extendr/extendr#612]
I was wondering if there is an example of how to extract a row of a dataframe into a struct in rust; such as after the dataframe was returned from r.  Below is an example:

Thanks. 

```rust
use extendr_api::prelude::*;

fn main() {
    #[derive(Debug)]
    struct Iris {
        sepal_length: f64,
        sepal_width: f64,
        petal_length: f64,
        petal_width: f64,
        species: String,
    }

    extendr_engine::start_r();

    let df: Dataframe<Iris> = eval_string("head(iris)").unwrap().try_into().unwrap();
    
    // how to convert Dataframe to Vec of struct, or extract an individual row as an Iris struct?
    // let x: Vec<Iris> = df.try_into().unwrap();

    extendr_engine::end_r();
}
```

**Comment by rdavis120** [comment]
Thank you for the response.  I was able to do something like this but since I already set the struct type of the Dataframe when I created it, I figured there might be an easier way without having to rewrite the column type in the as_ calls.

```rust
  df.as_list().unwrap().dollar("sepal_length").unwrap().as_real_iter() ....
```

**Comment by Ilia-Kosenkov** [comment]
There is a more 'Rust' way, I will try to come up with something more elegant later today / tomorrow.

**Comment by Ilia-Kosenkov** [comment]
Ok, now I am convinced we completely lack proper support for `DataFrames` access in `extendr`. It can be improved of course, especially to support scenarios similar to yours, but I cannot promise when this can be added and in which form.

In the meantime, you can `as_list()` on your dataframe and then iterate over name/value pairs, and then zip iterators to get iterator over a row.

**Comment by rdavis120** [comment]
Ok. I think we can close this for now.
