### ISSUE TITLE
make type error for ARM aarch64 u8/i8

### ISSUE THREAD

**Issue by eitsupi** [extendr/extendr#628]
From https://github.com/pola-rs/r-polars/pull/377#issuecomment-1731195728

```log
 error[E0308]: mismatched types
   --> /home/runner/.cargo/git/checkouts/extendr-f64cf2fdda5197e8/ee8d375/extendr-api/src/lib.rs:630:17
    |
630 |         Rprintf(PRINTF_NO_FMT_CSTRING.as_ptr(), cs.as_ptr());
    |         ------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |         |
    |         arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: function defined here
   --> /home/runner/work/r-polars/r-polars/src/rust/target/aarch64-unknown-linux-gnu/release-optimized/build/libR-sys-d7c4c89c6e4571b8/out/bindings.rs:876:12
    |
876 |     pub fn Rprintf(arg1: *const ::std::os::raw::c_char, ...);
    |            ^^^^^^^

error[E0308]: mismatched types
   --> /home/runner/.cargo/git/checkouts/extendr-f64cf2fdda5197e8/ee8d375/extendr-api/src/lib.rs:638:18
    |
638 |         REprintf(PRINTF_NO_FMT_CSTRING.as_ptr(), cs.as_ptr());
    |         -------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |         |
    |         arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: function defined here
   --> /home/runner/work/r-polars/r-polars/src/rust/target/aarch64-unknown-linux-gnu/release-optimized/build/libR-sys-d7c4c89c6e4571b8/out/bindings.rs:879:12
    |
879 |     pub fn REprintf(arg1: *const ::std::os::raw::c_char, ...);
    |            ^^^^^^^^
```

After #566, extendr doen't seem able to built for aarch64.
Please see remacs/remacs#1393 for details.

**Comment by yutannihilation** [comment]
Is this what can be solved by updating your libR-sys to v0.6.0?

I think this is already addressed by https://github.com/extendr/libR-sys/pull/160. Actually, the latest document shows the signature with `c_char`.

https://docs.rs/libR-sys/latest/libR_sys/fn.REprintf.html

**Comment by CGMossa** [comment]
Are we limiting the number of targets in the doc.rs? Hmm, I will have to
check.

You should be able to press target and then select the aforementioned
target when browsing the docs.

**Comment by yutannihilation** [comment]
Hmm, sorry, it seems I'm misunderstanding the problem. Please forget my comment above.

**Comment by eitsupi** [comment]
> Is this what can be solved by updating your libR-sys to v0.6.0?

I do not know.
Perhaps this repo should add a test to that builds to aarch64 Linux target.......

**Comment by yutannihilation** [comment]
@eitsupi 
I believe https://github.com/extendr/extendr/pull/629 should fix this problem, but I don't have an easy way to confirm it. Could you check if this actually solve https://github.com/pola-rs/r-polars/pull/377#issuecomment-1731195728?

**Comment by eitsupi** [comment]
It seems working fine, thanks!
https://github.com/pola-rs/r-polars/actions/runs/6275026696/job/17041599473?pr=377

**Comment by yutannihilation** [comment]
Great!
