### ISSUE TITLE
The `result_list` feature seems broken

### ISSUE THREAD

**Issue by eitsupi** [extendr/extendr#650]
See https://github.com/pola-rs/r-polars/issues/418#issuecomment-1783983375

**Comment by CGMossa** [comment]
Thanks for reporting this. Even if I don't know how this works, I think I can just fix the compilation error with the suggestions provided.

What I'm utterly surprised by, how this got missed by our extensive testing. To me, that's the real issue.

I'll look at this rather soon than later.

**Comment by eitsupi** [comment]
Thank you for your reply.
Yes, I don't know much about testing in this repository, but I think this feature flag is probably untested...

**Comment by yutannihilation** [comment]
For reference, the feature was added by this pull request. This did add a doc test, but didn't touch the CI settings, so I think the test is never executed in actual.

https://github.com/extendr/extendr/pull/473
