### ISSUE TITLE
Feature: Minimal feature to reduce size

### ISSUE THREAD

**Issue by JosiahParry** [extendr/extendr#671]
One of the stipulations of publishing a package on CRAN is that the tarball must be 5 mb or less. It would be quite nice if there was a `minimal` feature of extendr that allows the minimal set of features with the minimal set of dependencies. 

As it stands I'm unable to tell what is actually included in when no features are specified https://github.com/extendr/extendr/blob/master/extendr-api/Cargo.toml. In my case, and I suspect the vast majority of use cases, I only need conversion to and from R types. In my current case ([arcpbf](https://github.com/R-ArcGIS/arcpbf/)), I do not need anything _but_ those types.

**Comment by yutannihilation** [comment]
> As it stands I'm unable to tell what is actually included in when no features are specified

By default, no optional feature is included. So, that's minimal in terms of feature selection.

Among your dependencies, libR-sys might be a bit too huge and can be improved.

```
$ du -sh vendor/*
301K    vendor/anyhow
371K    vendor/bytes
85K     vendor/either
939K    vendor/extendr-api
93K     vendor/extendr-macros
774K    vendor/itertools
4.2M    vendor/libR-sys
199K    vendor/once_cell
148K    vendor/paste
239K    vendor/proc-macro2
148K    vendor/prost
125K    vendor/prost-derive
177K    vendor/quote
2.0M    vendor/syn
340K    vendor/unicode-ident
```

**Comment by CGMossa** [comment]
Right, so an xtask to generate bindings could be a way forward, because then libR sys would be minimal...

**Comment by yutannihilation** [comment]
I'm afraid it won't. In my understanding, xtask is useful for generating bindings outside of the compilation process, so it doesn't reduce the number of bindings shipped with libR-sys. I think preference behind libR-sys is being maximum, not minimum.

**Comment by eitsupi** [comment]
> One of the stipulations of publishing a package on CRAN is that the tarball must be 5 mb or less.

I am sure CRAN understands that this is difficult to meet when vending Rust source code.
prqlr's last few submissions have been 12MB, but most of that capacity has been submitted with the explanation that it is vending Rust crates, and no interaction with CRAN has occurred. I have not had any other interaction with CRAN.
<https://cran.r-project.org/src/contrib/Archive/prqlr/>
