### ISSUE TITLE
Return module metadata from DLL

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#69]
As described in this comment https://github.com/extendr/extendr/pull/40#issuecomment-742401070 by @andy-thomason:

We have code in the #[extendr_module] generator to register
functions with R using the standard DLL mechanism.

https://github.com/extendr/extendr/blob/2d2cbcfef8e930457ba2b03478be446d64d823b5/extendr-macros/src/lib.rs#L334-L354

It would be nice to add functions to provide metadata, including doc strings, to a function that
could return them to R.

```
extern "C" fn __get_module_metadata() -> Robj {
  ...
  data_frame!(name=..., args=..., doc=...)
}
```

This way we could use the rextendr code to generate functions, NAMESPACE and documentation
for all the functions and methods.

For regular functions, name is just the name called by R.
For methods and traits, the name is qualified: `Fred::new()`

The doc string is available as an attribute of the function but will need
to be translated to the roxygen2 format.

**Comment by clauswilke** [comment]
@hobofan Are you interested in taking this on?

**Comment by hobofan** [comment]
Yes, I'll be looking into it, but I'll probably have quite a few questions about it 😅

**Comment by andy-thomason** [comment]
We should probably replace the `init__` functions with `metadata__` and `CallMethod`

```
pub struct CallMethod {
    pub call_symbol: std::ffi::CString,
    pub func_ptr: *const u8,
    pub num_args: i32,
}
```

with something like

```
pub struct CallArg {
    docstring: String,
    name: String,
    type: String,
}
```
pub struct CallMetadata {
    docstring: String,
    call_symbol: String,
    func_ptr: *const u8,
    args: Vec<CallArg>,
}
```

A bit more bloaty, but richer.

We can move your R generating code to `extendr_api` and expose an R entrypoint to generate the
R source code (including doc strings) from outside the library.

This way we can run the generating code from inside R, which has many advantages.

I'm open to alternative suggestions.

**Comment by clauswilke** [comment]
I think this is good in principle. It should work well when writing stand-alone packages that use extendr.

However, if I understand correctly it will require the use of `extendr_module!` and this will cause problems for `rust_source` and `rust_function` in rextendr. So maybe implement your proposal **and** keep generating the wrapper functions from `#[extendr]` calls, as we're currently doing.

The reason problems will arise in rextendr is as follows:
- in `rust_function()`, we'll have to write regular expressions to parse Rust code to find the name of the function, so we can generate and inject the appropriate `extendr_module!` call.
- in `rust_source()`, we'll have to write regular expressions to parse Rust code to find the `extendr_module!` call a user has placed there to figure out the name of the module, so we can call the appropriate entry point. (Unless the entry point doesn't contain the name of the module; not sure if that would be possible. It sounds dangerous to me, since then two separate calls to `extendr_module!` would create linking issues.)

**Comment by clauswilke** [comment]
No longer needed/addressed with the new metadata framework.
