### ISSUE TITLE
Fix bump.sh and publish.sh for new crate structure

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#70]
I have added a new crate extendr-engine (#50) to remove the engine part from the default api. However, the scripts `bump.sh` and `publish.sh` don't reflect this change yet.

**Comment by andy-thomason** [comment]
Claus has suggested bumping the version right after the publish. This will help us to distinguish versions that are pulled from github.

**Comment by clauswilke** [comment]
I like the [versioning recommendations](https://r-pkgs.org/release.html#release-version) in the R packages book, which is to add a dev version (e.g., .9000) right after a package has been published, and then bump to the next non-dev version upon release. Is this possible with the Rust versioning system?

**Comment by clauswilke** [comment]
I think in Rust we have to go `0.1.10` -> `0.1.11-alpha` -> `0.1.11` instead of `0.1.10` -> `0.1.10.9000` -> `0.1.11`.

https://docs.rs/semver/0.11.0/semver/

**Comment by clauswilke** [comment]
Or maybe we should just delete these two scripts and transition to `cargo workspaces`: 
https://crates.io/crates/cargo-workspaces

`cargo workspaces version` can bump versions.

`cargo workspaces publish` can publish to crates.io.

**Comment by yutannihilation** [comment]
> `cargo workspaces version` can bump versions.

Sorry, I forgot to comment that this doesn't handle the versions specified with `path`. So we need some tweaks about these lines:

https://github.com/extendr/extendr/blob/41772722a01062b064320c98d687e3eae889790a/extendr-api/Cargo.toml#L13-L14

Btw, be careful when you try this command as this immediately commits and pushes the new version to remotes... When I tried this, I wasn't the member of extendr so the attempt was just rejected... `--no-git-commit` seems to save us.

**Comment by clauswilke** [comment]
If you have some experience with this tool, could you write up a workflow and add to the README, where it currently talks about `bump.sh` and `publish.sh`?

**Comment by yutannihilation** [comment]
After experimenting a bit more, I think `cargo workspaces version` is currently broken. I'll try to fix it there, but I'm not sure if it gets done before the next release.

**Comment by yutannihilation** [comment]
Sorry, it turned out it's just I didn't understand the usage... I think I can write up a workflow soon.
