### ISSUE TITLE
`throw_r_error` may crash R session

### ISSUE THREAD

**Issue by eitsupi** [extendr/extendr#716]
The polars package seems to occasionally crash due to the following location.
https://github.com/extendr/extendr/blob/fb88c799126ba93795b070db2bdfc94c4aeb0d6b/extendr-api/src/thread_safety.rs#L59

For example: pola-rs/r-polars#993

```r
> library(polars)
> as_polars_df(mtcars)$select(pl$col("mpg", "cyl")$to_struct()$map_elements(\(x) x$mpg))
[src/series.rs:387:17] x = Struct(
    [
        Field {
            name: "mpg",
            dtype: Float64,
        },
        Field {
            name: "cyl",
            dtype: Float64,
        },
    ],
)
thread '<unnamed>' panicked at src/series.rs:388:17:
not yet implemented: this input type is not implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/series.rs:55:1:
explicit panic
thread '<unnamed>' panicked at /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/b26adfe/extendr-api/src/thread_safety.rs:59:49:
called `Result::unwrap()` on an `Err` value: NulError(36, [117, 115, 101, 114, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 112, 97, 110, 105, 99, 107, 101, 100, 58, 32, 109, 97, 112, 95, 101, 108, 101, 109, 101, 110, 116, 115, 0])
thread '<unnamed>' panicked at src/rdataframe/mod.rs:87:1:
explicit panic
thread '<unnamed>' panicked at /usr/local/cargo/git/checkouts/extendr-569c02e1a164cdf5/b26adfe/extendr-api/src/thread_safety.rs:59:49:
called `Result::unwrap()` on an `Err` value: NulError(30, [117, 115, 101, 114, 32, 102, 117, 110, 99, 116, 105, 111, 110, 32, 112, 97, 110, 105, 99, 107, 101, 100, 58, 32, 115, 101, 108, 101, 99, 116, 0])
fatal runtime error: failed to initiate panic, error 5
fish: Job 1, 'R' terminated by signal SIGABRT (Abort)
```

**Comment by CGMossa** [comment]
Found it.
There are lines that look like this
```rs
                    let err_string = format!("user function panicked: {}\0",#r_name_str);
``` 
in the extendr branch/commit that you guys are using. I also believe this is on main. Let me investigate..

**Comment by JosiahParry** [comment]
Should be closed by #718

**Comment by yutannihilation** [comment]
Just curious. That line was introduced by https://github.com/extendr/extendr/pull/555 by @sorhawell, which was merged July last year. I thought r-polars started to use it soon after that (or even before that in their folk). Why hasn't no one notice the bug until today...?

**Comment by CGMossa** [comment]
The true culprit is this https://github.com/extendr/extendr/commit/244c044acb9720d975034d84cfdf4111f386bfca which is done by me.

I did notice it after some time, and added it to my fork... But I didn't really understand the implication of all of this, until now..

**Comment by yutannihilation** [comment]
Ah, got it. Thanks for the details.

**Comment by eitsupi** [comment]
I have confirmed the fix. Thank you for your quick response!
