### ISSUE TITLE
Make ndarray optional

### ISSUE THREAD

**Issue by hobofan** [extendr/extendr#72]
Thought I'd open up a separate issue for this, as it has come up in comments repeatedly (and is in the Roadmap of the README).

This would probably a good first step towards feature flags (which is also a concern in #60), which I guess also would need to get some support in `rextendr`.

**Comment by andy-thomason** [comment]
Yes. This is a good idea. I'm very much in favour of keeping dependencies low.

Do you want to submit a PR?

**Comment by clauswilke** [comment]
I like this in principle. Just one word of warning: There is no way of automatically testing optional features. You'll have to test them explicitly by calling `cargo test` separately on each crate (not once on the workspace) and turning on the optional features from the command line. Nothing that can't be done, but it'll substantially complicate our testing architecture.

Some projects write fairly complex test scripts to do this. It's easy enough on unix, but I don't know if it'll run on windows also. Maybe it will in mingw.

You can see this approach in the ndarray test setup: 
https://github.com/rust-ndarray/ndarray/blob/3a2040d916dd892a76cf7f219c1510cf8e48f34a/.github/workflows/ci.yml#L34
https://github.com/rust-ndarray/ndarray/blob/master/scripts/all-tests.sh
But they test only on linux.
