### ISSUE TITLE
Parsing f64 to i32 where the number overflows i32 causes to get the max value instead NA or overflow

### ISSUE THREAD

**Issue by latot** [extendr/extendr#720]
Hi all!, I found this by accident, but is not good...:

```R
library(rextendr)
code <- r"(
#[extendr]
fn hello(x: i32) {
    println!("{x}");
}
)"

rust_source(code = code)

hello(8314042901901001)
2147483647
```

No idea if other type has this behavior, but I think this should never happens.

Thx!

**Comment by Ilia-Kosenkov** [comment]
I think we break here https://github.com/extendr/extendr/blob/dd1b050ac4df203de2196bce206caad2c3820cb0/extendr-api/src/robj/try_from_robj.rs#L41C17-L48C18

**Comment by Ilia-Kosenkov** [comment]
Yep, we can fix that.

``` r
library(rextendr)
code <- r"(
#[extendr(use_try_from = true)]
fn hello(x: i32) {
    println!("{x}");
}
)"

rust_source(code = code)
#> ℹ build directory: 'C:/Users/.../AppData/Local/Temp/Rtmpgzv1Yf/file43c07e48656d'
#> ✔ Writing 'C:/Users/.../AppData/Local/Temp/Rtmpgzv1Yf/file43c07e48656d/target/extendr_wrappers.R'
hello(8314042901901001)
#> Error in hello(8314042901901001): Expected an integer or a float representing a whole number, got 8314042901901001.0
```

<sup>Created on 2024-04-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by latot** [comment]
wouldn't it be better keep it true as default? or is there a reason for it?

**Comment by Ilia-Kosenkov** [comment]
We did not finish the migration fully yet (unfortunately), so not all scenario & type combinations support `use_try_from = true`. But it should be safe to enable it for functions that are not in `impl` block.

**Comment by latot** [comment]
Wouldn't it be safer not use  ```as``` in that sections on the code?
