### ISSUE TITLE
Result handling on return.

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#73]
After a bit of experimentation. I think we should implement Result<T, E> in the following way:

```
library(rextendr)

res = rust_function(
  code = "fn rust_error(val: i32) -> Result<i32, Box<dyn Error>> {
     if val == 0 {
         Err("val is zero!".into())
     } else {
         Ok(val)
     }
  }",
)

res <- rust_error(input)
if (inherits(res, "rust.error")) {
  # handle error (res is actually a string)
} else {
  # use res
}
```

What do you think as R users?

**Comment by andy-thomason** [comment]
This will open us up to use the ? operator in rust code.

**Comment by andy-thomason** [comment]
We should also have an option to handle input errors in the same way.

```
// rust
#[extendr(use_rust_param_error=true)]
fn myfun(val: i32) {
}

# R
stopifnot(class(myfun("xyz")), "rust.param.error")
```

**Comment by andy-thomason** [comment]
Should Result also have a:

```
#[extendr(use_rust_result_error=true)]
fn myfun(val: i32) {
}
```

And default to throwing an R error?

**Comment by clauswilke** [comment]
I 100% agree with having a `Result` type available that allows us to use `?` in the Rust code and not think about what that does specifically.

I'm less convinced by turning the various error objects into R strings. Honestly, anything but the default of throwing an R error seems overkill. R functions can catch the error if they want to. It's unlikely this is a feature a lot of R users would want or expect, and so I'd focus my efforts elsewhere at this time.

**Comment by lebensterben** [comment]
R's way of handling error in C API is to have caller provide a string buffer for the callee to write in. (And this buffer has fixed size which avoids heap allocation.)

On Rust side it's perfectly idomatic to use Result type. But when the Result is passed to R, I think one easy way of implementation is to fill the error buffer with the Error.

That is to say, the R side receives a list, where contains slots for both correct result and potential error message.

Since Rust doesn't support long jump, calling R_error directly in Rust will potentially leave heap allocated memory not freed (depending on the implementation).

So a safe way to circumvent this is to have R to interpret the Result from Rust, and throw error/warning accordingly.

**Comment by lebensterben** [comment]
And btw, I don't think we  need the Result\<T, Box\<dyn Error>>. 

I suggest to use a type synonym of
`type Result<T> = Result<T, String>`

This hides implementation details, is easy to implement, and can be extended later.

**Comment by clauswilke** [comment]
> Since Rust doesn't support long jump, calling R_error directly in Rust will potentially leave heap allocated memory not freed (depending on the implementation).

An alternative would be to keep all memory allocation in the worker thread that does the actual execution of the rust function, and to transmit any errors to the outer thread via a panic. Since the worker thread is cleaned up upon panic, the outer thread should be safely able to perform the long jump.

**Comment by lebensterben** [comment]
Let's keep it simple. Panic across FFI boundary itself is very hard to deal with. Keeping track of what is not freed upon a panic takes some effort.

**Comment by lebensterben** [comment]
One experience from my experience with Rust-R interop before.

I had Rust directly returns a wrapper struct of Rust's Result type. The wrapper struct contains two fields, one is the pointer to the correct value, another is the pointer to the error expressed as string.

When the C wrapper received the wrapped Result, it return the correct value to R, or throw an error when the error string is null.

Not it gets tricky. If C wrapper just throw the error, it terminates, and the heap allocated string buffer is not freed. So the solution is to have Rust side to export some callback functions to free those heap allocated memory.

If we just use R's approach of sending a buffer to write, things get super easy. It's stack allocated, and is freed automatically.

**Comment by clauswilke** [comment]
To be clear, though: Only memory allocation via Rust's mechanisms is a problem. You can always allocate through `R_alloc()` and R will reclaim the memory after the ffi call ends: 
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Transient-storage-allocation

There's really no difference between a C function calling `R_alloc()` and a Rust function calling `R_alloc()`.

**Comment by lebensterben** [comment]
But for performance, I don't want to call R_alloc. And the biggest concern I have over the current implementation is, like I said before, there's completely no point of having Rust to run an instance of embedded R.

**Comment by andy-thomason** [comment]
The motivation for creating an R object with a class was to make handling errors which do not throw a bit safer.

We may want to have both options.

1) Returning an error calls Rf_error (use_rust_param_error=false)
2) Returning an error returns a rust.error class object (with printing support in rextendr).

The latter should ensure that memory allocation is safe, the first is not guaranteed.
