### ISSUE TITLE
Extendr fails unit tests on R devel

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#79]
The test suite does not currently run without error on R devel. See e.g. here:
https://github.com/extendr/extendr/runs/1579358171

This is not related to whether or not libR-sys is compiled with bindgen or uses precompiled bindings.

**Comment by clauswilke** [comment]
This is the error:
```
Error: Error in `::`(base, quote) : could not find function "::"
Calls: .OptRequireMethods
Execution halted
error: test failed, to rerun pass '-p extendr-api --lib'
test args::tests::test_args ... 
Error: Process completed with exit code 1.
```
Since it happens when testing the extendr engine, and the engine tests do nothing but start R, we can infer that this happens in the startup code. The fact that the error mentions `.OptRequireMethods` points in the same direction. This function is called at R startup from `setup_Rmainloop()`, here:
https://github.com/wch/r-source/blob/7e99b9a77e4ec0ca3e0ae645f45dcc5717ccf6fb/src/main/main.c#L978-L989

This is the function definition itself:
https://github.com/wch/r-source/blob/d22ee2fc0dc8142b23eed9f46edf76ea9d3ca69a/src/library/profile/Common.R#L88-L96

**Comment by clauswilke** [comment]
This is the code that likely causes the error:
https://github.com/extendr/extendr/blob/39f1c311a2d331ec4650b34a72f8d0c7713f5e4f/extendr-engine/src/lib.rs#L41-L54

@ltierney Can I ping you on this? We're trying to set up an R main loop from Rust. Things work fine in R release but we get this strange error about a missing function `"::"` in R devel. Has anything changed recently in how R starts up that might explain this? Anything else we could change? We're just calling `Rf_initialize_R()` and then `setup_Rmainloop()`, so there's not much we could do differently.

**Comment by ltierney** [comment]
We recently moved :: and ::: from closures to BUILTIN primitives. Not
sure why that would affect embedding.

On Sat, 19 Dec 2020, Claus Wilke wrote:

> 
> This is the code that likely causes the error:
> https://github.com/extendr/extendr/blob/39f1c311a2d331ec4650b34a72f8d0c7713
> f5e4f/extendr-engine/src/lib.rs#L41-L54
> 
> @ltierney Can I ping you on this? We're trying to set up an R main loop from
> Rust. Things work fine in R release but we get this strange error about a
> missing function "::" in R devel. Has anything changed recently in how R
> starts up that might explain this? Anything else we could change? We're just
> calling Rf_initialize_R() and then setup_Rmainloop(), so there's not much we
> could do differently.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AA55UVAYW55E4HBOBV3KQ23SVQQU7A5CNFSM4VBXXSQ2YY3PNVWWK3TUL52HS4
> DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFSN6RTA.gif]
> 
> 
>

-- 
Luke Tierney
Ralph E. Wareham Professor of Mathematical Sciences
University of Iowa                  Phone:             319-335-3386
Department of Statistics and        Fax:               319-335-3017
    Actuarial Science
241 Schaeffer Hall                  email:   luke-tierney@uiowa.edu
Iowa City, IA 52242                 WWW:  http://www.stat.uiowa.edu

**Comment by yutannihilation** [comment]
> We recently moved :: and ::: from closures to BUILTIN primitives.

This commit?

https://github.com/wch/r-source/commit/5cf2557f4bd68aa863dbc3c5580c61de490c1093

**Comment by yutannihilation** [comment]
@clauswilke
Sorry, I don't follow the recent progress on this repo, but maybe we are using the bindings precomputed on R-relase for R-devel?

**Comment by clauswilke** [comment]
@yutannihilation No, I set up a test that generates fresh bindings for this exact reason:
https://github.com/extendr/extendr/runs/1579358072

**Comment by yutannihilation** [comment]
Ah, I see.

**Comment by clauswilke** [comment]
So presumably this would be a minimal example in C. I currently have only R release on my laptop and this works fine there. Can either of you try this with R devel?

```C
/* file: embed.c
Compile with (on Mac):
> gcc -I/Library/Frameworks/R.framework/Resources/include -L/Library/Frameworks/R.framework/Resources/lib -lR embed.c

Run with (on Mac):
> R_HOME=/Library/Frameworks/R.framework/Resources/ ./a.out 
*/

#include <Rembedded.h>
#include <stdio.h>

int main() {
    char* argv[] = {"R", "--slave", "--no-save"};

    printf("Initializing R\n");
    Rf_initialize_R(3, argv);
    
    printf("Setting up main loop\n");
    setup_Rmainloop();
    
    printf("Done\n");
    return 0;
}
```

**Comment by yutannihilation** [comment]
It can compile with clang, but cannot with GCC. Am I missing something...?

``` console
❯ sudo docker run --rm -it -v "${PWD}:/tmp/test" rocker/r-devel gcc -I/usr/share/R/include -L/usr/lib/R/lib -lR /tmp/test/embed.c
/usr/bin/ld: /tmp/ccJO6TGg.o: in function `main':
embed.c:(.text+0x42): undefined reference to `Rf_initialize_R'
/usr/bin/ld: embed.c:(.text+0x53): undefined reference to `setup_Rmainloop'
collect2: error: ld returned 1 exit status
```

**Comment by yutannihilation** [comment]
Anyway, this seems to work. Not sure if more recent changes matter. (Btw, I used `rocker/r-devel` above, but found its R version is too old...)

```sh
sudo docker run --rm -it -v "/tmp/test:/tmp/test" rocker/r-ver:devel bash

# n docker image
apt update && apt install -y clang r-base-dev
clang -I/usr/share/R/include -L/usr/lib/R/lib -lR /tmp/test/embed.c
R_HOME=/usr/lib/R ./a.out
```

``` console
root@0a0de7bc611b:/# clang -I/usr/share/R/include -L/usr/lib/R/lib -lR /tmp/test/embed.c
root@0a0de7bc611b:/# R_HOME=/usr/lib/R ./a.out
Initializing R
Setting up main loop
Done
root@0a0de7bc611b:/# R --version
R Under development (unstable) (2020-12-06 r79580) -- "Unsuffered Consequences"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.


```

**Comment by yutannihilation** [comment]
> Am I missing something...?

An expert told me that I needed to put `-lR` to the tail (c.f. https://stackoverflow.com/a/11894098). Now the compilation succeeds, and it works without errors.

``` console
root@93aed37b5959:/# gcc -I/usr/share/R/include -L/usr/lib/R/lib /tmp/test/embed.c -lR
root@93aed37b5959:/# R_HOME=/usr/lib/R ./a.out
Initializing R
Setting up main loop
Done
```

**Comment by clauswilke** [comment]
Ok, looks like this will require more digging. I don't think the problem is that your R devel is too old, I've looked at the most recent commits to R devel and they don't look related to this issue. Maybe it's something else the Rust program is doing, like modifying the C stack limit or calling these functions from a separate Rust thread. I'll set up a github repo to test this out.

**Comment by clauswilke** [comment]
@yutannihilation @ltierney I can reproduce the embedding error with a simple C program using R devel 2020-12-18 r79646:
https://github.com/clauswilke/extendr-engine-tests/runs/1582370155?check_suite_focus=true

The C program is basically the one I posted above. See here:
https://github.com/clauswilke/extendr-engine-tests/blob/main/embed.c

**Comment by ltierney** [comment]
You are picking up the wrong `libR.so` shared library at runtime (look at what `ldd` tells you). One way to get the right one is with

```
env LD_LIBRARY_PATH=${R_HOME}/lib ./a.out
```

**Comment by clauswilke** [comment]
Ah, this makes sense, thanks! The GitHub Action images have R release pre-installed, so it's probably picking that up. 

In our actual builds of the Rust R bindings, the build script is supposed to pick up the correct library location (see e.g. here: https://github.com/extendr/libR-sys/runs/1580025711?check_suite_focus=true#step:4:1096) but apparently there's a known problem with that not properly working.

**Comment by clauswilke** [comment]
Thanks @yutannihilation @ltierney, this is now resolved.

**Comment by yutannihilation** [comment]
Cool. It didn't occur to me that it picks up the wrong `libR.so`... Thank you for your help, @ltierney!
