### ISSUE TITLE
how to use `&[T]` and is `&mut [T]` possible

### ISSUE THREAD

**Issue by jtlandis** [extendr/extendr#794]
Hello Devs! cool package!

I've been reading @yutannihilation [blog](https://yutani.rbind.io/post/2021-06-14-unofficial-introduction-to-extendr-2-type-conversion-between-r-and-rust/#wait-didnt-you-say-we-cant-do-this) when I came across this statement:

> Please note that this isn’t the reference to the original R object, just that to the copied values. If you really want no copying, you should use the “proxy” types, which I’ll cover in the next post.

This got me wondering to what`&[T]` does to the underlying R data when passed into an Rust function. The above quote makes it sound like that the data tied to the object passed into this function is copied.

This also got me wondering if there was any way to get `&mut [T]` to possibly mutate the R object in memory.

I'm trying to get a better understanding of how `extendr` relates to R objects and when memory is copied.

**Comment by CGMossa** [comment]
Every R-object may provide direct access to the underlying data via the C-API. We take advantage of that in extendR, by taken what the C-API provides, and turning it into slices `& [T]` / `&mut [T]`. There is no copying there. However, other types, like owned types such as `Vec<T>` will necessarily copy the data from an `Robj` to itself (say `Vec<i32>`). 

So yes, with extendR, you can have in-place mutation of variables. The only thing we disallow is the mutation of strings, but not the mutation of character vectors. There is a subtle technicality there.

**Comment by Ilia-Kosenkov** [comment]
Then we have dedicated vector wrappers like `Doubles` or `Integers` that wrap R vectors in a `NA`-aware fashion, no copying involved.

But be careful with ALTREP vectors like `1:100`, if you take an `&[f64]`, ALTREP will be materialized.

**Comment by jtlandis** [comment]
Could you provide an example of in-place mutation?

I was trying something very simple but I was getting build errors:

```{extendr}
/// @param x integer vector
/// @export
#[extendr]
pub fn mut_first(x: &mut [i32]) {
  x[0] += 3;
}
```
```{bash}
   error[E0599]: no function or associated item named `from_robj` found for mutable reference `&mut [i32]` in the current scope
     --> src/lib.rs:21:1
      |
   21 | #[extendr]
      | ^^^^^^^^^^ function or associated item not found in `&mut [i32]`
      |
      = note: this error originates in the attribute macro `extendr` (in Nightly builds, run with -Z macro-backtrace for more info)
      ```

**Comment by CGMossa** [comment]
Okay. A few things: it has been 8-9 months since the last release, and a lot of things have changed in extendr. I'm aiming for this PR next to make the above code possible: https://github.com/extendr/extendr/pull/790

If you want to use the version of extendr that's available on `git`, you can modify the `Cargo.toml` like so
```toml
[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr.git", branch = "master" }
```
(remember to call `cargo update` in the terminal for things to update). 

Now, to do what you want here, on the published to crates.io extendr, I think something similar to this is necessary:

```rs
#[extendr]
pub fn mut_first(x: Robj) {
  let mut x = x;
  use extendr_api::AsTypedSlice;
  let mut x: &mut [i32] = x.as_typed_slice_mut().unwrap();
  x[0] += 3;
}
```
Hopefully this works, I've basically written it from me memory.

**Comment by CGMossa** [comment]
I have tried it out using `rextendr`:

```r
rextendr::rust_function("
pub fn mut_first(x: Robj) {
  let mut x = x;
  use extendr_api::AsTypedSlice;
  let mut x: &mut [i32] = x.as_typed_slice_mut().unwrap();
  x[0] += 3;
}
")
x<- 1:20
mut_first(x)
x
 [1]  4  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
```

**Comment by jtlandis** [comment]
Thank you for such a quick reply! I'll be looking more into the methods [on the Robj](https://extendr.github.io/extendr/extendr_api/robj/struct.Robj.html#method.as_integer_slice_mut) to explore further.

Before I close this issue, I am also curious if `tracemem` works with `extendr`. In our discussions, the owned Vec<T> type would force a copy, correct? So shouldn't the below code indicate the data has been copied?

``` r
rextendr::rust_function(
  "
  pub fn add2_slice(x: &[i32], y: &[i32]) -> Vec<i32> {
    x.iter().enumerate().map(|(i, x)| x + y[i]).collect()
  }
  "
)
x <- c(1L, 2L, 3L)
y <- c(4L, 5L, 6L)
```

```r
tracemem(x)
#> [1] "<0x7ff5f2271c08>"
```

``` r
tracemem(y)
#> [1] "<0x7ff5f14a0788>"
```

``` r
add2_slice(x, y)
#> [1] 5 7 9
```

<sup>Created on 2024-06-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by CGMossa** [comment]
There isn't enough outputs here for me to see the effect of a copy.
Although, I'm not sure it is as a copy as much as another allocation..

**Comment by jtlandis** [comment]
Thank your for all your input!

**Comment by CGMossa** [comment]
You're welcome. Feel free to come again... We have a Discussion section,
and we have a lively discord too.

**Comment by CGMossa** [comment]
```r
> x <- c(1L, 2L, 3L)
> y <- c(4L, 5L, 6L)
> tracemem(x)
[1] "<0x1692df848>"
> tracemem(y)
[1] "<0x16929d988>"
> xy <- add2_slice(x, y)
> xy
[1] 5 7 9
> tracemem(xy)
[1] "<0x168ff5448>" # new address
> tracemem(x)
[1] "<0x1692df848>" # same as x before
> tracemem(y)
[1] "<0x16929d988>" # same as y before 
```
