### ISSUE TITLE
Update libR-sys to properly support R 4.2

### ISSUE THREAD

**Issue by andyquinterom** [extendr/extendr#797]
The following PR https://github.com/extendr/libR-sys/pull/246 on libR-sys ensures support for
R 4.2. We should update the dependency to this revision of libR-sys

**Comment by CGMossa** [comment]
Please make that PR, and I'll approve it.

**Comment by andyquinterom** [comment]
@CGMossa There you go :D https://github.com/extendr/extendr/pull/798
