### ISSUE TITLE
R CRAN package

### ISSUE THREAD

**Issue by andy-thomason** [extendr/extendr#8]
The CRAN package should have the following features:

A function to install cargo.
A function to build a skeleton project (wrapping cargo new).

Optionally:

An inline rust code builder.

Any other suggestions welcome, please comment.

**Comment by dasmoth** [comment]
One thing that might be worth keeping in the back of the mind: interactive development.  I've previously used `devtools::install()` for a reasonably quick rebuild-and-reload cycle when working on packages with C extensions.  This does work with extendr (so long as you add the usual `.onUnload` boilerplate, but annoyingly, because `devtools` makes a copy of the package before trying to install it, so you lose your Cargo cache and end up with a full rebuild of all the required rust libs every time.  Not the end of the world, of course, but maybe worth thinking if there's a good way to keep a persistent Cargo cache.

**Comment by andy-thomason** [comment]
I'm keen to avoid devtools if possible as it is just enormous. I think it is a good choice
for small stand-alone projects, but to build a whole ecosystem on it would make for
very high install times.

We only need something to fetch cargo on all platforms and create a skeleton directory
along the lines of the "hello" and "vector" (in a branch) examples.

Inline rust would be nice, however...

**Comment by dasmoth** [comment]
Agreed, definitely wouldn't want something like this to depend on `devtools`.

Rather, I was using it as an example of a workflow where packages get rebuilt and reinstalled -- ideally quickly!  There are probably others (I think RStudio does something similar-ish, but don't use that myself).

**Comment by andy-thomason** [comment]
We should set up a repo for the CRAN package to get started and get it critiqued by someone like Hadley or Dirk.

**Comment by andy-thomason** [comment]
Conversely, we should encourage the use of R as a plotting and analysis tool in Rust. For example to
plot stats from websites.

**Comment by andy-thomason** [comment]
I've made a start on the R package in a branch. I've chosen a subset of the RCpp functionality to implement.

**Comment by dbdahl** [comment]
I just wanted to encourage work on this issue and offer to try to help.  This project (in general) and an Rcpp-like R package on CRAN (in particular) are very interesting to me.  Following the example of Jeroen Ooms's gifski package on CRAN (https://cran.r-project.org/package=gifski), my salso package on CRAN (https://cran.r-project.org/package=salso) and a few other as-of-yet unreleased R packages use Rust for fast computations.  They works quiet well and I'm very happy with the result, but I seem to have to write a bunch of wrapper functions that Rcpp avoids for R packages based on C++.  I would love to have something similar for R packages based on Rust.  I am not a professional developer, but my experience level with Rust and C are moderate such that I could certainly help test such a package.

**Comment by andy-thomason** [comment]
Thanks @dbdahl  Progress is slow as I'm having to do this out of hours and have conflicting open source projects to juggle.

I liked Jeroen's article and was inspired by it.

I'm hoping that we will have a very low overhead for package generation once the R package is complete.

**Comment by lebensterben** [comment]
I'm also working with R-Rust interop, though not directly via extendr. I will also make my contributions when I get time.

**Comment by andy-thomason** [comment]
Feel free to use libR-sys in other projects. It has been left deliberately vanilla for this purpose.

**Comment by clauswilke** [comment]
On the topic of interactive development, if you remove `target` from `make clean` and build the R package from within RStudio with the "Install and Restart" option then rebuilds are very fast.

**Comment by andy-thomason** [comment]
I'm going to close this for tidiness as we now have rexrendr thanks to Claus.
