### ISSUE TITLE
CHANGES IN R-devel C-LEVEL FACILITIES 

### ISSUE THREAD

**Issue by schochastics** [extendr/extendr#806]
I got one of those dreaded emails about removing  package from CRAN due to check issues.

```
checking compiled code ... WARNING
File ‘timeless/libs/timeless.so’:
  Found non-API calls to R: ‘ENVFLAGS’, ‘FRAME’, ‘HASHTAB’, ‘PRCODE’,
    ‘PRENV’, ‘PRSEEN’, ‘PRVALUE’, ‘Rf_findVarInFrame3’, ‘SET_BODY’,
    ‘SET_CLOENV’, ‘SET_ENCLOS’, ‘SET_ENVFLAGS’, ‘SET_FORMALS’,
    ‘SET_PRCODE’, ‘SET_PRENV’, ‘SET_PRVALUE’, ‘STRING_PTR’, ‘SYMVALUE’,
    ‘XLENGTH_EX’
These entry points may be removed soon:
‘PRSEEN’, ‘SYMVALUE’

Compiled code should not call non-API entry points in R.
```
Here is the corresponding r devel news: <https://developer.r-project.org/blosxom.cgi/R-devel/NEWS>
The package in question is [timeless](https://github.com/schochastics/timeless).

Given that  the only compiled code I have is via extendr, I assume the issue originates in that package? Unfortunately my C is not good enough to investigate myself.

**Comment by JosiahParry** [comment]
Yes. I got 3 of these myself this morning see my email that I suspect will go with 0 replies :/ https://stat.ethz.ch/pipermail/r-devel/2024-June/083499.html

**Comment by JosiahParry** [comment]
Created issues at #807 and #808

**Comment by CGMossa** [comment]
Hello @schochastics. Thank you for your issue report. We'll take a look at this.

**Comment by yutannihilation** [comment]
@CGMossa @JosiahParry 
Congratulations on the new release.

Just in case, as I commented on https://github.com/extendr/extendr/pull/809#issuecomment-2190310378, I really recommend you to actually remove `PRSEEN` and `SYMVALUE`, which they clearly say "may be removed soon". The removal from R's header file means extendr cannot be compiled when `non-api` feature is enabled.

**Comment by schochastics** [comment]
Thanks for all your efforts!really appreciated
