### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#85]
I saw a lot of irrelevant changes on #84 due to auto-formatting. Can we follow the default of `cargo fmt` and check it on CI?

c.f. https://github.com/dimforge/nalgebra/blob/d8fa3ff24147dee0c0b481881aad1c2890fad942/.circleci/config.yml#L13-L22

**Comment by clauswilke** [comment]
Works for me.

**Comment by andy-thomason** [comment]
Go for it. It is slightly irritating as the tests will fail frequently for formatting when you
just want to check some functionality.

**Comment by andy-thomason** [comment]
We are overdue a project tidy-up with a few more modules.

Maybe we should make the Robj methods into traits. We could then implement them
for a simpler Robj type.
