### ISSUE TITLE
Integration tests create GitHub merge chicken-and-egg problem

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#89]
The integration tests contain a separate R package that uses extendr just like any stand-alone package would. It pulls the latest extendr sources from GitHub. This creates a chicken-and-egg problem if the integration tests depend on some new extendr feature that hasn't been pushed to the main branch on GitHub yet.

I ran into this when I bumped libR-sys to version 0.2.0. You can see that the latest commit before the merge failed the CI tests: https://github.com/extendr/extendr/pull/88/commits/42b5ccb15b418a645201151eed3f327c6ab75382. However, the actual merge into master had all tests succeed: https://github.com/extendr/extendr/commit/cecc67f37a425b97fc441854bee678501d247eed.

I don't currently see a way to fix this. The offending lines in the code are here:
https://github.com/extendr/extendr/blob/cecc67f37a425b97fc441854bee678501d247eed/tests/extendrtests/src/rust/Cargo.toml#L19-L21
We might think to simply use relative paths within the repo here, but that won't work because the entire `extendrtests` folder gets copied into a temp directory when the integration tests are run, and thus relative paths break.

I'm not sure there's anything that can be done, so this issue may primarily serve as an explanation and reminder of what is happening.

**Comment by clauswilke** [comment]
Here's a workflow that is a bit cumbersome but should at least work without having to merge failing tests. It requires two steps.

First, in you PR, in the three lines I highlighted above, point the extendr sources to the fork/branch that contains the new feature, e.g.:
```
 extendr-api = { git = "https://github.com/clauswilke/extendr", branch = "new-feature" } 
```
This should then allow the tests to succeed. Merge this PR. **Important: Do not delete the branch after merging!** It's still being used.

Second, make another PR that reverts the extendr sources back to the main extendr repo, and, if all tests pass, merge. Now, if you want, you can delete the branches you created for both PRs.

**Comment by andy-thomason** [comment]
You should be able to use many different sources of packages together,
In theory, **cargo publish** should modify the `Cargo.toml ` to leave just the package.

I usually use a standard layout of the project:

```
/home/myuser/extendr/extendr
/home/myuser/extendr/libR-sys
```

Which allows us to use relative paths, github refs and crates:
```
 libR-sys = { path = "../../libR-sys", version="xx.yy.zz" } 
```

This way it should build using the path in development and the crate for production.

Of course, without the workspace, we rely on this directory structure.

**Comment by clauswilke** [comment]
I understand how to use relative paths in `Cargo.toml`. The problem I'm describing here arises with the integration tests I set up here: https://github.com/extendr/extendr/tree/master/tests/extendrtests which consist of a separate R package. When that R package is build and tested on GitHub Actions, it is first copied into a temporary location, and any relative paths to outside the R package break at that point.
