### ISSUE TITLE
R integration tests issue on linux 

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [extendr/extendr#92]
After updating GitHub Actions to include all OSs and all required architectures, I noticed that all linux R integration tests produce a `Note`, complaining about the size of some package subfolder:
https://github.com/extendr/extendr/runs/1603463755?check_suite_focus=true#step:14:111
https://github.com/extendr/extendr/runs/1603463765?check_suite_focus=true#step:14:111
https://github.com/extendr/extendr/runs/1603463770?check_suite_focus=true#step:14:111
https://github.com/extendr/extendr/runs/1603463775?check_suite_focus=true#step:14:109

This, however, happens neither for MacOS nor for Windows builds (both architectures):
https://github.com/extendr/extendr/runs/1603463728?check_suite_focus=true#step:14:203
https://github.com/extendr/extendr/runs/1603463746?check_suite_focus=true#step:14:98

Don't know if it is important, but I find it strange that only one OS consistently produces notes when tested.

**Comment by clauswilke** [comment]
Those can be safely ignored. It's the folder containing the compiled library, and it's a bit bigger on Linux than on other OSes. It would be Ok on CRAN as is, but since we're not submitting the integration tests to CRAN it matters even less.

**Comment by Ilia-Kosenkov** [comment]
Ok, thanks for the explanation.
